SELECT * FROM PRODUCTION.MART_SPEAKERS.ACCESS_SPEAKERS;



SELECT * FROM PRODUCTION.MART_SPEAKERS.SALESFORCE_SPEAKERS;

--aacrid, session date and session time combined, dedupe


SELECT COUNT(*) FROM PRODUCTION.REPL_SALESFORCE.CONTACTS WHERE MAILING_STATE = 'Puerto Rico';


SELECT MAILING_COUNTRY, COUNT(*) FROM PRODUCTION.REPL_SALESFORCE.CONTACTS GROUP BY MAILING_COUNTRY ORDER BY 2 DESC;




SELECT
    COUNT(*)
FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_DATA_TERM_BACKUP AS A
    JOIN PRODUCTION.REPL_SALESFORCE.CONTACTS AS B
        ON A."SALESFORCE ID" = B.ID
WHERE A."TERM YEAR" = 2022 AND B.MAILING_STATE = 'Puerto Rico' AND A."ITEM NAME" = 'Active Membership';


SELECT
    *
FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_DATA_TERM_BACKUP;




SELECT
    MAILING_COUNTRY,
    COUNT(*)
FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_DATA_TERM_BACKUP AS A
    JOIN PRODUCTION.REPL_SALESFORCE.CONTACTS AS B
        ON A."SALESFORCE ID" = B.ID
WHERE A."TERM YEAR" = 2023 AND A."ITEM NAME" = 'Active Membership'
GROUP BY B.MAILING_COUNTRY
ORDER BY 1;


SELECT
    MAILING_STATE,
    COUNT(*)
FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_DATA_TERM_BACKUP AS A
    JOIN PRODUCTION.REPL_SALESFORCE.CONTACTS AS B
        ON A."SALESFORCE ID" = B.ID
WHERE A."TERM YEAR" = 2023 AND A."ITEM NAME" = 'Active Membership'
GROUP BY B.MAILING_STATE
ORDER BY 1;


SELECT DISTINCT MAILING_STATE FROM PRODUCTION.REPL_SALESFORCE.CONTACTS;



SELECT DISTINCT PAY_METHOD FROM IMISDATA.DBO.DUES;

SELECT * FROM PRODUCTION.REPL_SALESFORCE.EVENTS WHERE "EVENT_NAME" LIKE '%Roundtable%';


SELECT * FROM PRODUCTION.MART_MEETING_REGISTRATION.MEETING_REGISTRATIONS WHERE EVENT_ID = 'a4jRm000000aVbZIAU';

SELECT * FROM PRODUCTION.MART_MEETING_REGISTRATION.MEETING_REGISTRATIONS_BACKUP AS MR WHERE  MR.EVENT_ID = 'a4jRm000000aVbZIAU';


with Cons AS (
SELECT
    *
FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_DATA_TERM_BACKUP AS A
    JOIN PRODUCTION.REPL_SALESFORCE.CONTACTS AS B
        ON A."SALESFORCE ID" = B.ID
WHERE A."TERM YEAR" = 2023 AND A."ITEM NAME" = 'Active Membership'),
Con AS (
    SELECT
        *
    FROM Cons
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONTACT
    ON Cons.ID = CONTACT."Id"
)
SELECT * FROM Con LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
    ON ACC."Id" = Con."AccountId"
WHERE ACC."Name" NOT LIKE '%Test%' AND "Item Name" = 'Active Membership';







SELECT 	CON."Member_Type__c" 	, count(CON."Id")	 FROM 	CONTACT AS CON JOIN "ACCOUNT" AS ACC ON ACC."Id" = CON."AccountId" JOIN RECORDTYPE AS RT ON RT."Id" = CON."RecordTypeId" WHERE 	NOT (ACC."Name" LIKE '%AACR Test%') 	AND RT."Name" IN ('Member')--,'Prior Member') 	AND CON."Membership_Status__c" IN ('Current')-- ','Suspended') GROUP BY CON."Member_Type__c"