/*Name TBH, annual meeting 24 report mart etc */

/*
Sort DESC by last updated/reg date etc
Dedupe by SOURCE_ENTITY_ID
WHERE eventid = 'a4j8W000000OLXcQAO'
 */


with AM_CSI AS (
SELECT * FROM PRODUCTION.BOOMI_MDH_STAGE.BOOMI_CSI_CONTACT_EVENT_STAGE WHERE EVENTID = 'a4j8W000000OLXcQAO' ORDER BY UPDATE_DATE DESC
)
SELECT COUNT(DISTINCT SOURCE_ENTITY_ID) FROM AM_CSI;

SELECT COUNT(DISTINCT SOURCE_ENTITY_ID) FROM PRODUCTION.BOOMI_MDH_STAGE.BOOMI_CSI_CONTACT_EVENT_STAGE WHERE EVENTID = 'a4j8W000000OLXcQAO' ORDER BY UPDATE_DATE DESC;


 


CREATE SCHEMA TEST.MART_CSI_AM_REG;

CREATE VIEW TEST.MART_CSI_AM_REG.MART_CSI_AM_REG_v AS
with AM_CSI AS (
SELECT 
    *, 
    ROW_NUMBER() OVER(PARTITION BY SOURCE_ENTITY_ID ORDER BY UPDATE_DATE DESC) AS RN 
FROM PRODUCTION.BOOMI_MDH_STAGE.BOOMI_CSI_CONTACT_EVENT_STAGE WHERE EVENTID = 'a4j8W000000OLXcQAO' ORDER BY UPDATE_DATE DESC
)
SELECT 
    STAGE_ID,
    SOURCE_ID,
    SOURCE_ENTITY_ID,
    SOURCE_IDENTIFIER_NAME_ID,
    AACR_ID,
    NAME,
    NAME_PREFIX,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    NAME_SUFFIX,
    NICKNAME,
    PREFERRED_PHONE,
    PREFERRED_EMAIL,
    RACE,
    GENDER,
    PRONOUNS,
    DATE_OF_BIRTH,
    MEMBERSHIP_ID,
    MEMBERSHIP_TYPE,
    MEMBERSHIP_STATUS,
    COMPANY_BUSINESS_ACCOUNT_NAME,
    COMPANY_BUSINESS_ACCOUNT_ID,
    WORK_EMAIL_IDENTIFIER,
    WORK_EMAIL_TYPE,
    WORK_EMAIL_ADDRESS,
    WORK_EMAIL_DOMAIN,
    WORK_EMAIL_DOMAIN_BUSINESS_ID,
    WORK_EMAIL_USER,
    WORK_EMAIL_IS_OPT_OUT,
    PERSONAL_EMAIL_IDENTIFIER,
    PERSONAL_EMAIL_TYPE,
    PERSONAL_EMAIL_ADDRESS,
    PERSONAL_EMAIL_DOMAIN,
    PERSONAL_EMAIL_DOMAIN_BUSINESS_ID,
    PERSONAL_EMAIL_USER,
    PERSONAL_EMAIL_IS_OPT_OUT,
    OTHER_EMAIL_IDENTIFIER,
    OTHER_EMAIL_TYPE,
    OTHER_EMAIL_ADDRESS,
    OTHER_EMAIL_DOMAIN,
    OTHER_EMAIL_DOMAIN_BUSINESS_ID,
    OTHER_EMAIL_USER,
    OTHER_EMAIL_IS_OPT_OUT,
    WORK_PHONE_IDENTIFIER,
    WORK_PHONE_TYPE,
    WORK_PHONE_NUMBER,
    WORK_PHONE_CONTACT_NAME,
    WORK_PHONE_IS_OPT_OUT,
    WORK_PHONE_HAS_SMS,
    MOBILE_PHONE_IDENTIFIER,
    MOBILE_PHONE_TYPE,
    MOBILE_PHONE_NUMBER,
    MOBILE_PHONE_CONTACT_NAME,
    MOBILE_PHONE_IS_OPT_OUT,
    MOBILE_PHONE_HAS_SMS,
    HOME_PHONE_IDENTIFIER,
    HOME_PHONE_TYPE,
    HOME_PHONE_NUMBER,
    HOME_PHONE_CONTACT_NAME,
    HOME_PHONE_IS_OPT_OUT,
    HOME_PHONE_HAS_SMS,
    OTHER_PHONE_IDENTIFIER,
    OTHER_PHONE_TYPE,
    OTHER_PHONE_NUMBER,
    OTHER_PHONE_CONTACT_NAME,
    OTHER_PHONE_IS_OPT_OUT,
    OTHER_PHONE_HAS_SMS,
    MAILING_ADDRESS_IDENTIFIER,
    MAILING_ADDRESS_TYPE,
    MAILING_ADDRESS_SUBTYPE,
    MAILING_ADDRESS_LINE_1,
    MAILING_ADDRESS_LINE_2,
    MAILING_CITY,
    MAILING_STATE,
    MAILING_POSTAL_CODE,
    MAILING_COUNTRY_NAME,
    MAILING_COUNTRY_CODE,
    OTHER_ADDRESS_IDENTIFIER,
    OTHER_ADDRESS_TYPE,
    OTHER_ADDRESS_SUBTYPE,
    OTHER_ADDRESS_LINE_1,
    OTHER_ADDRESS_LINE_2,
    OTHER_CITY,
    OTHER_STATE,
    OTHER_POSTAL_CODE,
    OTHER_COUNTRY_NAME,
    OTHER_COUNTRY_CODE,
    BADGENO,
    EVENTID,
    PARTICIPANTID,
    REGISTRATION_CATEGORY,
    CREATE_DATE,
    UPDATE_DATE,
    CREATE_USER,
    UPDATE_USER,
    BATCHNO
FROM AM_CSI
WHERE RN = 1;

CREATE SCHEMA PRODUCTION.MART_CSI_AM24_REG;

CREATE OR REPLACE VIEW PRODUCTION.MART_CSI_AM24_REG.AM24_REG_v
AS
with AM_CSI AS (
SELECT 
    *, 
    ROW_NUMBER() OVER(PARTITION BY SOURCE_ENTITY_ID ORDER BY UPDATE_DATE DESC) AS RN 
FROM PRODUCTION.BOOMI_MDH_STAGE.BOOMI_CSI_CONTACT_EVENT_STAGE WHERE EVENTID = 'a4j8W000000OLXcQAO' ORDER BY UPDATE_DATE DESC
)
SELECT 
    STAGE_ID,
    SOURCE_ID,
    SOURCE_ENTITY_ID,
    SOURCE_IDENTIFIER_NAME_ID,
    AACR_ID,
    NAME,
    NAME_PREFIX,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    NAME_SUFFIX,
    NICKNAME,
    PREFERRED_PHONE,
    PREFERRED_EMAIL,
    RACE,
    GENDER,
    PRONOUNS,
    DATE_OF_BIRTH,
    MEMBERSHIP_ID,
    MEMBERSHIP_TYPE,
    MEMBERSHIP_STATUS,
    COMPANY_BUSINESS_ACCOUNT_NAME,
    COMPANY_BUSINESS_ACCOUNT_ID,
    WORK_EMAIL_IDENTIFIER,
    WORK_EMAIL_TYPE,
    WORK_EMAIL_ADDRESS,
    WORK_EMAIL_DOMAIN,
    WORK_EMAIL_DOMAIN_BUSINESS_ID,
    WORK_EMAIL_USER,
    WORK_EMAIL_IS_OPT_OUT,
    PERSONAL_EMAIL_IDENTIFIER,
    PERSONAL_EMAIL_TYPE,
    PERSONAL_EMAIL_ADDRESS,
    PERSONAL_EMAIL_DOMAIN,
    PERSONAL_EMAIL_DOMAIN_BUSINESS_ID,
    PERSONAL_EMAIL_USER,
    PERSONAL_EMAIL_IS_OPT_OUT,
    OTHER_EMAIL_IDENTIFIER,
    OTHER_EMAIL_TYPE,
    OTHER_EMAIL_ADDRESS,
    OTHER_EMAIL_DOMAIN,
    OTHER_EMAIL_DOMAIN_BUSINESS_ID,
    OTHER_EMAIL_USER,
    OTHER_EMAIL_IS_OPT_OUT,
    WORK_PHONE_IDENTIFIER,
    WORK_PHONE_TYPE,
    WORK_PHONE_NUMBER,
    WORK_PHONE_CONTACT_NAME,
    WORK_PHONE_IS_OPT_OUT,
    WORK_PHONE_HAS_SMS,
    MOBILE_PHONE_IDENTIFIER,
    MOBILE_PHONE_TYPE,
    MOBILE_PHONE_NUMBER,
    MOBILE_PHONE_CONTACT_NAME,
    MOBILE_PHONE_IS_OPT_OUT,
    MOBILE_PHONE_HAS_SMS,
    HOME_PHONE_IDENTIFIER,
    HOME_PHONE_TYPE,
    HOME_PHONE_NUMBER,
    HOME_PHONE_CONTACT_NAME,
    HOME_PHONE_IS_OPT_OUT,
    HOME_PHONE_HAS_SMS,
    OTHER_PHONE_IDENTIFIER,
    OTHER_PHONE_TYPE,
    OTHER_PHONE_NUMBER,
    OTHER_PHONE_CONTACT_NAME,
    OTHER_PHONE_IS_OPT_OUT,
    OTHER_PHONE_HAS_SMS,
    MAILING_ADDRESS_IDENTIFIER,
    MAILING_ADDRESS_TYPE,
    MAILING_ADDRESS_SUBTYPE,
    MAILING_ADDRESS_LINE_1,
    MAILING_ADDRESS_LINE_2,
    MAILING_CITY,
    MAILING_STATE,
    MAILING_POSTAL_CODE,
    MAILING_COUNTRY_NAME,
    MAILING_COUNTRY_CODE,
    OTHER_ADDRESS_IDENTIFIER,
    OTHER_ADDRESS_TYPE,
    OTHER_ADDRESS_SUBTYPE,
    OTHER_ADDRESS_LINE_1,
    OTHER_ADDRESS_LINE_2,
    OTHER_CITY,
    OTHER_STATE,
    OTHER_POSTAL_CODE,
    OTHER_COUNTRY_NAME,
    OTHER_COUNTRY_CODE,
    BADGENO,
    EVENTID,
    PARTICIPANTID,
    REGISTRATION_CATEGORY,
    CREATE_DATE,
    UPDATE_DATE,
    CREATE_USER,
    UPDATE_USER,
    BATCHNO
FROM AM_CSI
WHERE RN = 1;


SELECT COUNT(AACR_ID) FROM PRODUCTION.MART_CSI_AM24_REG.AM24_REG_V WHERE AACR_ID = '';

SELECT
    DISTINCT PROGRAM_STATUS_NAME
FROM PRODUCTION.REPL_CTI.INVITED_SPEAKERS_CHAIRS;

SELECT
    *
FROM PRODUCTION.REPL_CTI.INVITED_SPEAKERS_CHAIRS
WHERE PROGRAM_STATUS_NAME LIKE '%Accepted%';
--ORDER BY PROGRAM_STATUS_NAME ASC;


--manuscript id, title, abstract (maybe summary as well?)



SELECT CON."Name"
FROM PRODUCTION.MART_MEETING_REGISTRATION.MEETING_REGISTRATIONS_BACKUP AS MR
LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON
ON MR.CONTACT_ID = CON."Id"
LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_EVENT__C AS EV
ON MR.EVENT_ID = EV."Id"
WHERE EV."Name" = 'AACR Annual Meeting 2024' AND CON."Name" LIKE '%Aimee%';


SELECT DISTINCT COMP_CODE FROM PRODUCTION.MART_MEETING_REGISTRATION.MEETING_REGISTRATIONS_BACKUP WHERE EVENT_ID = 'a4j8W000000OLXcQAO';