/*Contacts *:1 Contact Dimension Tag, include Dimension Tag object (has dimension tag name) */
SELECT //NO CONTACT TABLE
    A.*,
    B.*
FROM PRODUCTION.REPL_SALESFORCE.CONTACT_DIMENSION_TAGS AS A
    LEFT JOIN PRODUCTION.REPL_SALESFORCE.DIMENSION_TAGS AS B
        ON A.DIMENSION_TAG = B.ID
LIMIT 2;


/*Accounts *:1 Account Dimension Tag */
SELECT
    ACCTS.*,
    ADT.TAG
    ADT.ID AS "ACCOUNT_DIMENSION_TAG_ID",
    ADT.DIMENSION_TAG
FROM PRODUCTION.REPL_SALESFORCE.ACCOUNTS AS ACCTS
    LEFT JOIN PRODUCTION.REPL_SALESFORCE.ACCOUNT_DIMENSION_TAGS AS ADT
        ON ACCTS.ID = ADT.OBJECT_LOOKUP;


/*Opportunities *:1 Opportunity Dimension Tag */
SELECT
    OPS.*,
    ODT.TAG
    ODT.ID AS "OPPORTUNITY_DIMENSION_TAG_ID", /*MIGHT NEED MORE FIELDS HERE*/
    ODT.DIMENSION_TAG
FROM PRODUCTION.REPL_SALESFORCE.OPPORTUNITIES AS OPS
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY_DIMENSION_TAG__C AS ODT
        ON OPS.ID = ODT."Object_Lookup__c"
LIMIT 100;





SELECT * FROM PRODUCTION.REPL_SALESFORCE.CONTACT_DIMENSION_TAGS;




/*Playing around with CONTACTS table/self-join*/

SELECT
    NAME,
    ID,
    REPORTS_TO_ID
FROM PRODUCTION.REPL_SALESFORCE.CONTACTS
WHERE REPORTS_TO_ID IS NOT NULL
LIMIT 1000;


SELECT
    A.NAME AS "Contact Name",
    B.NAME AS "Reports to Name"
FROM PRODUCTION.REPL_SALESFORCE.CONTACTS AS A
    LEFT JOIN PRODUCTION.REPL_SALESFORCE.CONTACTS B
        ON A.ID = B.REPORTS_TO_ID
WHERE B.NAME IS NOT NULL
ORDER BY RANDOM()
LIMIT 1000;


/*
CREATE OR REPLACE VIEW TEST.TEST_AREA.MART_CONTACT_DIMENSION_TAGS (
    CDT.ID
    CDT.OWNER_ID
    CDT.IS_DELETED
    CDT.NAME
    CDT.LAST_ACTIVITY_DATE
    CDT.CONVERSION_TAG
    CDT.DIMENSION_TAG
    CDT.OBJECT_LOOKUP
    CDT.REMOVAL_REQUESTED_BY
    CDT.REQUEST_FOR_REMOVAL
    CDT.TAG
    CDT.VISIBILITY
    CDT.CONTACT_ID
    CDT.SRC_SYS_ID
    CDT.SRC_RECORD_ID
    CDT.SRC_CREATED_DATE
    CDT.CREATED_BY_ID
    CDT.SRC_LAST_UPDATED_DATE
    CDT.LAST_MODIFIED_BY_ID
    CDT.SRC_START_DATE
    CDT.SRC_END_DATE
    CDT.IS_TEST
    CDT.TEST_METADATA
    CDT.DW_ID
    CDT.DW_CREATED_DATE
    CDT.DW_LAST_UPDATED_DATE
    CDT.DW_START_DATE
    CDT.DW_END_DATE
    CDT.AACR_ID
    CDT.MASTER_ID
    CDT.IS_MASTERED
    CDT.IS_CONFORMED
    CDT.EXCEPTION_CODES
    CDT.SYSTEM_MODSTAMP
    DT.ID
    DT.OWNER_ID
    DT.IS_DELETED
    DT.NAME
    DT.RECORD_TYPE_ID
    DT.DESCRIPTION
    DT.OBJECT_API_NAME
    DT.TYPE
    DT.LAST_ACTIVITY_DATE
    DT.MARKETING_EXPORT
    DT.STATUS
    DT.SRC_SYS_ID
    DT.SRC_RECORD_ID
    DT.SRC_CREATED_DATE
    DT.CREATED_BY_ID
    DT.SRC_LAST_UPDATED_DATE
    DT.LAST_MODIFIED_BY_ID
    DT.SRC_START_DATE
    DT.SRC_END_DATE
    DT.IS_TEST
    DT.TEST_METADATA
    DT.DW_ID
    DT.DW_CREATED_DATE
    DT.DW_LAST_UPDATED_DATE
    DT.DW_START_DATE
    DT.DW_END_DATE
    DT.AACR_ID
    DT.MASTER_ID
    DT.IS_MASTERED
    DT.IS_CONFORMED
    DT.EXCEPTION_CODES
    DT.SYSTEM_MODSTAMP
) AS 
SELECT
    A.*,
    B.*
FROM PRODUCTION.REPL_SALESFORCE.CONTACT_DIMENSION_TAGS AS A
    LEFT JOIN PRODUCTION.REPL_SALESFORCE.DIMENSION_TAGS AS B
        ON A.DIMENSION_TAG = B.ID;




ACCOUNTS 

CREATE OR REPLACE VIEW TEST.TEST_AREA.MART_ACCOUNT_DIMENSION_TAGS (
    "ADT.ID",
    "ADT.OWNER_ID",
    "ADT.IS_DELETED",
    "ADT.NAME",
    "ADT.LAST_ACTIVITY_DATE",
    "ADT.OBJECT_LOOKUP",
    "ADT.TAG",
    "ADT.DIMENSION_TAG",
    "ADT.REMOVAL_REQUESTED_BY",
    "ADT.REQUEST_FOR_REMOVAL",
    "ADT.VISIBILITY",
    "ADT.ACCOUNT_ID",
    "ADT.SRC_SYS_ID",
    "ADT.SRC_RECORD_ID",
    "ADT.SRC_CREATED_DATE",
    "ADT.CREATED_BY_ID",
    "ADT.SRC_LAST_UPDATED_DATE",
    "ADT.LAST_MODIFIED_BY_ID",
    "ADT.SRC_START_DATE",
    "ADT.SRC_END_DATE",
    "ADT.IS_TEST",
    "ADT.TEST_METADATA",
    "ADT.DW_ID",
    "ADT.DW_CREATED_DATE",
    "ADT.DW_LAST_UPDATED_DATE",
    "ADT.DW_START_DATE",
    "ADT.DW_END_DATE",
    "ADT.AACR_ID",
    "ADT.MASTER_ID",
    "ADT.IS_MASTERED",
    "ADT.IS_CONFORMED",
    "ADT.EXCEPTION_CODES",
    "ADT.SYSTEM_MODSTAMP",
    "DT.ID",
    "DT.OWNER_ID",
    "DT.IS_DELETED",
    "DT.NAME",
    "DT.RECORD_TYPE_ID",
    "DT.DESCRIPTION",
    "DT.OBJECT_API_NAME",
    "DT.TYPE",
    "DT.LAST_ACTIVITY_DATE",
    "DT.MARKETING_EXPORT",
    "DT.STATUS",
    "DT.SRC_SYS_ID",
    "DT.SRC_RECORD_ID",
    "DT.SRC_CREATED_DATE",
    "DT.CREATED_BY_ID",
    "DT.SRC_LAST_UPDATED_DATE",
    "DT.LAST_MODIFIED_BY_ID",
    "DT.SRC_START_DATE",
    "DT.SRC_END_DATE",
    "DT.IS_TEST",
    "DT.TEST_METADATA",
    "DT.DW_ID",
    "DT.DW_CREATED_DATE",
    "DT.DW_LAST_UPDATED_DATE",
    "DT.DW_START_DATE",
    "DT.DW_END_DATE",
    "DT.AACR_ID",
    "DT.MASTER_ID",
    "DT.IS_MASTERED",
    "DT.IS_CONFORMED",
    "DT.EXCEPTION_CODES",
    "DT.SYSTEM_MODSTAMP"
) AS 
SELECT
    A.*,
    B.*
FROM PRODUCTION.REPL_SALESFORCE.ACCOUNT_DIMENSION_TAGS AS A
    LEFT JOIN PRODUCTION.REPL_SALESFORCE.DIMENSION_TAGS AS B
        ON A.DIMENSION_TAG = B.ID;


CREATE OR REPLACE VIEW TEST.TEST_AREA.MART_OPPORTUNITY_DIMENSION_TAGS (
    "ODT.Id",
    "ODT.OwnerId",
    "ODT.IsDeleted",
    "ODT.Name",
    "ODT.CreatedDate",
    "ODT.CreatedById",
    "ODT.LastModifiedDate",
    "ODT.LastModifiedById",
    "ODT.SystemModstamp",
    "ODT.LastActivityDate",
    "ODT.Dimension_Tag__c",
    "ODT.Object_Lookup__c",
    "ODT.Removal_Requested_By__c",
    "ODT.Request_for_Removal__c",
    "ODT.Tag__c",
    "ODT.Visibility__c",
    "ODT.OpportunityID__c",
    "ODT.Tag_Unique__c",
    "DT.ID",
    "DT.OWNER_ID",
    "DT.IS_DELETED",
    "DT.NAME",
    "DT.RECORD_TYPE_ID",
    "DT.DESCRIPTION",
    "DT.OBJECT_API_NAME",
    "DT.TYPE",
    "DT.LAST_ACTIVITY_DATE",
    "DT.MARKETING_EXPORT",
    "DT.STATUS",
    "DT.SRC_SYS_ID",
    "DT.SRC_RECORD_ID",
    "DT.SRC_CREATED_DATE",
    "DT.CREATED_BY_ID",
    "DT.SRC_LAST_UPDATED_DATE",
    "DT.LAST_MODIFIED_BY_ID",
    "DT.SRC_START_DATE",
    "DT.SRC_END_DATE",
    "DT.IS_TEST",
    "DT.TEST_METADATA",
    "DT.DW_ID",
    "DT.DW_CREATED_DATE",
    "DT.DW_LAST_UPDATED_DATE",
    "DT.DW_START_DATE",
    "DT.DW_END_DATE",
    "DT.AACR_ID",
    "DT.MASTER_ID",
    "DT.IS_MASTERED",
    "DT.IS_CONFORMED",
    "DT.EXCEPTION_CODES",
    "DT.SYSTEM_MODSTAMP"
) AS
SELECT
    A.*,
    B.*
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY_DIMENSION_TAG__C AS A
    LEFT JOIN PRODUCTION.REPL_SALESFORCE.DIMENSION_TAGS AS B
        ON A."Dimension_Tag__c" = B.ID;

 */



/******************* Actual commands below *************************************************** */
/*
CREATE OR REPLACE VIEW PRODUCTION.MART_CONTACT_DIMENSION_TAGS.CONTACT_DIMENSION_TAGS (
    "CDT.ID",
    "CDT.OWNER_ID",
    "CDT.IS_DELETED",
    "CDT.NAME",
    "CDT.LAST_ACTIVITY_DATE",
    "CDT.CONVERSION_TAG",
    "CDT.DIMENSION_TAG",
    "CDT.OBJECT_LOOKUP",
    "CDT.REMOVAL_REQUESTED_BY",
    "CDT.REQUEST_FOR_REMOVAL",
    "CDT.TAG",
    "CDT.VISIBILITY",
    "CDT.CONTACT_ID",
    "CDT.SRC_SYS_ID",
    "CDT.SRC_RECORD_ID",
    "CDT.SRC_CREATED_DATE",
    "CDT.CREATED_BY_ID",
    "CDT.SRC_LAST_UPDATED_DATE",
    "CDT.LAST_MODIFIED_BY_ID",
    "CDT.SRC_START_DATE",
    "CDT.SRC_END_DATE",
    "CDT.IS_TEST",
    "CDT.TEST_METADATA",
    "CDT.DW_ID",
    "CDT.DW_CREATED_DATE",
    "CDT.DW_LAST_UPDATED_DATE",
    "CDT.DW_START_DATE",
    "CDT.DW_END_DATE",
    "CDT.AACR_ID",
    "CDT.MASTER_ID",
    "CDT.IS_MASTERED",
    "CDT.IS_CONFORMED",
    "CDT.EXCEPTION_CODES",
    "CDT.SYSTEM_MODSTAMP",
    "DT.ID",
    "DT.OWNER_ID",
    "DT.IS_DELETED",
    "DT.NAME",
    "DT.RECORD_TYPE_ID",
    "DT.DESCRIPTION",
    "DT.OBJECT_API_NAME",
    "DT.TYPE",
    "DT.LAST_ACTIVITY_DATE",
    "DT.MARKETING_EXPORT",
    "DT.STATUS",
    "DT.SRC_SYS_ID",
    "DT.SRC_RECORD_ID",
    "DT.SRC_CREATED_DATE",
    "DT.CREATED_BY_ID",
    "DT.SRC_LAST_UPDATED_DATE",
    "DT.LAST_MODIFIED_BY_ID",
    "DT.SRC_START_DATE",
    "DT.SRC_END_DATE",
    "DT.IS_TEST",
    "DT.TEST_METADATA",
    "DT.DW_ID",
    "DT.DW_CREATED_DATE",
    "DT.DW_LAST_UPDATED_DATE",
    "DT.DW_START_DATE",
    "DT.DW_END_DATE",
    "DT.AACR_ID",
    "DT.MASTER_ID",
    "DT.IS_MASTERED",
    "DT.IS_CONFORMED",
    "DT.EXCEPTION_CODES",
    "DT.SYSTEM_MODSTAMP"
) AS 
SELECT
    A.*,
    B.*
FROM PRODUCTION.REPL_SALESFORCE.CONTACT_DIMENSION_TAGS AS A
    LEFT JOIN PRODUCTION.REPL_SALESFORCE.DIMENSION_TAGS AS B
        ON A.DIMENSION_TAG = B.ID;


***CONTACT DIMENSION TAGS BACKUP***
SELECT
    A.*,
    B.*
FROM PRODUCTION.REPL_SALESFORCE.CONTACT_DIMENSION_TAGS AS A
    LEFT JOIN PRODUCTION.REPL_SALESFORCE.DIMENSION_TAGS AS B
        ON A.DIMENSION_TAG = B.ID;


CREATE OR REPLACE VIEW PRODUCTION.MART_ACCOUNT_DIMENSION_TAGS.ACCOUNT_DIMENSION_TAGS (
    "ADT.ID",
    "ADT.OWNER_ID",
    "ADT.IS_DELETED",
    "ADT.NAME",
    "ADT.LAST_ACTIVITY_DATE",
    "ADT.OBJECT_LOOKUP",
    "ADT.TAG",
    "ADT.DIMENSION_TAG",
    "ADT.REMOVAL_REQUESTED_BY",
    "ADT.REQUEST_FOR_REMOVAL",
    "ADT.VISIBILITY",
    "ADT.ACCOUNT_ID",
    "ADT.SRC_SYS_ID",
    "ADT.SRC_RECORD_ID",
    "ADT.SRC_CREATED_DATE",
    "ADT.CREATED_BY_ID",
    "ADT.SRC_LAST_UPDATED_DATE",
    "ADT.LAST_MODIFIED_BY_ID",
    "ADT.SRC_START_DATE",
    "ADT.SRC_END_DATE",
    "ADT.IS_TEST",
    "ADT.TEST_METADATA",
    "ADT.DW_ID",
    "ADT.DW_CREATED_DATE",
    "ADT.DW_LAST_UPDATED_DATE",
    "ADT.DW_START_DATE",
    "ADT.DW_END_DATE",
    "ADT.AACR_ID",
    "ADT.MASTER_ID",
    "ADT.IS_MASTERED",
    "ADT.IS_CONFORMED",
    "ADT.EXCEPTION_CODES",
    "ADT.SYSTEM_MODSTAMP",
    "DT.ID",
    "DT.OWNER_ID",
    "DT.IS_DELETED",
    "DT.NAME",
    "DT.RECORD_TYPE_ID",
    "DT.DESCRIPTION",
    "DT.OBJECT_API_NAME",
    "DT.TYPE",
    "DT.LAST_ACTIVITY_DATE",
    "DT.MARKETING_EXPORT",
    "DT.STATUS",
    "DT.SRC_SYS_ID",
    "DT.SRC_RECORD_ID",
    "DT.SRC_CREATED_DATE",
    "DT.CREATED_BY_ID",
    "DT.SRC_LAST_UPDATED_DATE",
    "DT.LAST_MODIFIED_BY_ID",
    "DT.SRC_START_DATE",
    "DT.SRC_END_DATE",
    "DT.IS_TEST",
    "DT.TEST_METADATA",
    "DT.DW_ID",
    "DT.DW_CREATED_DATE",
    "DT.DW_LAST_UPDATED_DATE",
    "DT.DW_START_DATE",
    "DT.DW_END_DATE",
    "DT.AACR_ID",
    "DT.MASTER_ID",
    "DT.IS_MASTERED",
    "DT.IS_CONFORMED",
    "DT.EXCEPTION_CODES",
    "DT.SYSTEM_MODSTAMP"
) AS 
SELECT
    A.*,
    B.*
FROM PRODUCTION.REPL_SALESFORCE.ACCOUNT_DIMENSION_TAGS AS A
    LEFT JOIN PRODUCTION.REPL_SALESFORCE.DIMENSION_TAGS AS B
        ON A.DIMENSION_TAG = B.ID;


CREATE OR REPLACE VIEW PRODUCTION.MART_OPPORTUNITY_DIMENSION_TAGS.OPPORTUNITY_DIMENSION_TAGS (
    "ODT.Id",
    "ODT.OwnerId",
    "ODT.IsDeleted",
    "ODT.Name",
    "ODT.CreatedDate",
    "ODT.CreatedById",
    "ODT.LastModifiedDate",
    "ODT.LastModifiedById",
    "ODT.SystemModstamp",
    "ODT.LastActivityDate",
    "ODT.Dimension_Tag__c",
    "ODT.Object_Lookup__c",
    "ODT.Removal_Requested_By__c",
    "ODT.Request_for_Removal__c",
    "ODT.Tag__c",
    "ODT.Visibility__c",
    "ODT.OpportunityID__c",
    "ODT.Tag_Unique__c",
    "DT.ID",
    "DT.OWNER_ID",
    "DT.IS_DELETED",
    "DT.NAME",
    "DT.RECORD_TYPE_ID",
    "DT.DESCRIPTION",
    "DT.OBJECT_API_NAME",
    "DT.TYPE",
    "DT.LAST_ACTIVITY_DATE",
    "DT.MARKETING_EXPORT",
    "DT.STATUS",
    "DT.SRC_SYS_ID",
    "DT.SRC_RECORD_ID",
    "DT.SRC_CREATED_DATE",
    "DT.CREATED_BY_ID",
    "DT.SRC_LAST_UPDATED_DATE",
    "DT.LAST_MODIFIED_BY_ID",
    "DT.SRC_START_DATE",
    "DT.SRC_END_DATE",
    "DT.IS_TEST",
    "DT.TEST_METADATA",
    "DT.DW_ID",
    "DT.DW_CREATED_DATE",
    "DT.DW_LAST_UPDATED_DATE",
    "DT.DW_START_DATE",
    "DT.DW_END_DATE",
    "DT.AACR_ID",
    "DT.MASTER_ID",
    "DT.IS_MASTERED",
    "DT.IS_CONFORMED",
    "DT.EXCEPTION_CODES",
    "DT.SYSTEM_MODSTAMP"
) AS
SELECT
    A.*,
    B.*
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY_DIMENSION_TAG__C AS A
    LEFT JOIN PRODUCTION.REPL_SALESFORCE.DIMENSION_TAGS AS B
        ON A."Dimension_Tag__c" = B.ID;

*/
CREATE OR REPLACE VIEW PRODUCTION.MART_CONTACT_DIMENSION_TAGS.CONTACT_DIMENSION_TAGS_BACKUP
AS
SELECT
    A."Id",
    A."OwnerId",
    A."IsDeleted",
    A."Name",
    A."CreatedDate",
    A."CreatedById",
    A."LastModifiedDate",
    A."LastModifiedById",
    A."SystemModstamp",
    A."LastActivityDate",
    A."Conversion_Tag__c",
    A."Dimension_Tag__c",
    A."Object_Lookup__c",
    A."Removal_Requested_By__c",
    A."Request_for_Removal__c",
    A."Tag__c",
    A."Visibility__c",
    A."ContactID__c",
    B."Id" AS DIMENSION_TAG_ID,
    B."OwnerId" AS DIMENSION_TAG_OWNER_ID,
    B."IsDeleted" AS DT_IS_DELETED,
    B."Name" DIMESNION_TAG_NAME,
    B."RecordTypeId",
    B."CreatedDate" AS DIMENSION_TAG_CREATED_DATE,
    B."CreatedById" AS DIMESNION_TAG_CREATED_BY_ID,
    B."LastModifiedDate" AS DIMENSION_TAG_LAST_MODIFIED_DATE,
    B."LastModifiedById" AS DIMENSION_TAG_LAST_MODIFIED_BY_ID,
    B."LastActivityDate" AS DIMENSION_TAG_LAST_ACTIVITY_DATE,
    B."Description__c",
    B."Marketing_Export__c",
    B."Object_API_Name__c",
    B."Status__c",
    B."Type__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT_DIMENSION_TAG__C AS A
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.DIMENSION_TAG__C AS B
        ON A."Dimension_Tag__c" = B."Id";

CREATE OR REPLACE VIEW PRODUCTION.MART_ACCOUNT_DIMENSION_TAGS.ACCOUNT_DIMENSION_TAGS_BACKUP
AS
SELECT
    A.*,
    B."Id" AS DIMENSION_TAG_ID,
    B."OwnerId" AS DIMENSION_TAG_OWNER_ID,
    B."IsDeleted" AS DT_IS_DELETED,
    B."Name" DIMESNION_TAG_NAME,
    B."RecordTypeId",
    B."CreatedDate" AS DIMENSION_TAG_CREATED_DATE,
    B."CreatedById" AS DIMESNION_TAG_CREATED_BY_ID,
    B."LastModifiedDate" AS DIMENSION_TAG_LAST_MODIFIED_DATE,
    B."LastModifiedById" AS DIMENSION_TAG_LAST_MODIFIED_BY_ID,
    B."LastActivityDate" AS DIMENSION_TAG_LAST_ACTIVITY_DATE,
    B."Description__c",
    B."Marketing_Export__c",
    B."Object_API_Name__c",
    B."Status__c",
    B."Type__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT_DIMENSION_TAG__C AS A
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.DIMENSION_TAG__C AS B
        ON A."Dimension_Tag__c" = B."Id";


DROP VIEW PRODUCTION.MART_CONTACT_DIMENSION_TAGS.ACCOUNT_DIMENSION_TAGS_BACKUP;





CREATE OR REPLACE VIEW PRODUCTION.MART_OPPORTUNITY_DIMENSION_TAGS.OPPORTUNITY_DIMENSION_TAGS_BACKUP
AS
SELECT
    A.*,
    B."Id" AS DIMENSION_TAG_ID,
    B."OwnerId" AS DIMENSION_TAG_OWNER_ID,
    B."IsDeleted" AS DT_IS_DELETED,
    B."Name" DIMESNION_TAG_NAME,
    B."RecordTypeId",
    B."CreatedDate" AS DIMENSION_TAG_CREATED_DATE,
    B."CreatedById" AS DIMESNION_TAG_CREATED_BY_ID,
    B."LastModifiedDate" AS DIMENSION_TAG_LAST_MODIFIED_DATE,
    B."LastModifiedById" AS DIMENSION_TAG_LAST_MODIFIED_BY_ID,
    B."LastActivityDate" AS DIMENSION_TAG_LAST_ACTIVITY_DATE,
    B."Description__c",
    B."Marketing_Export__c",
    B."Object_API_Name__c",
    B."Status__c",
    B."Type__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY_DIMENSION_TAG__C AS A
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.DIMENSION_TAG__C AS B
        ON A."Dimension_Tag__c" = B."Id";




DROP VIEW PRODUCTION.MART_CONTACT_DIMENSION_TAGS.OPPORTUNITY_DIMENSION_TAGS_BACKUP;










with Terms AS(
SELECT
    *
FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_DATA_TERM
WHERE "TERM YEAR" IN (2022, 2023, 2024)
)
SELECT T.*, SC."Name" FROM Terms AS T
    LEFT JOIN PRODUCTION.REPL_SALESFORCE.SALES_ORDERS AS SO
        ON T."SALES ORDER ID" = SO.ID
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__SOURCE_CODE__C AS SC
        ON SO.SOURCE_CODE_ID = SC."Id"
WHERE SC."Name" = 'BOGO';

SELECT DISTINCT "Name" FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__SOURCE_CODE__C ;



SELECT * FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_DATA_TERM WHERE "SALESFORCE ID" = '0031I00000WsFBhQAN';

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__RECEIPT__C WHERE "OrderApi__Contact__c" = '0031I00000WsFBhQAN';

SELECT * FROM  TEST.IMIS_ACTIVITIES.COMMITTEE;

SELECT DISTINCT ITEM_NAME FROM PRODUCTION.MART_JOURNAL_SALES.JOURNAL_SALES;