CREATE OR REPLACE DYNAMIC TABLE PRODUCTION.REPL_DONORDRIVE.DISCREPANCIES
    target_lag = '4 hours'
    warehouse = COMPUTE_WH
    refresh_mode = AUTO
AS
with NPC AS (
    SELECT 
        A."Name" AS GT_NAME,
        A."CreatedDate" AS GT_CREATEDDATE,
        A."Id" AS GT_ID,
        A."CampaignId" AS GT_CAMPAIGN_ID,
        A."Donor_Drive_Revenue_Type__c" AS NPC_DD_REVENUE_TYPE,
        A."Donor_Drive_Payment_Description__c" AS NPC_DD_PAYMENT_DESCRIPTION,
        A."DD_Recurring_Profile_ID__c" AS NPC_DD_RECURRING_PROFILE,
        A."OwnerId" AS NPC_OWNER_ID,
        A."CampaignId" AS NPC_CAMPAIGN_ID,
        A."OriginalAmount" AS NPC_TRANS_AMOUNT,
        A."TransactionDate" AS NPC_TRANSACTION_DATE,
        A."DonorDrive_Receipt_Id__c" AS NPC_DD_RECEIPT_ID,
        A."OwnerId"
    FROM PRODUCTION.REPL_NPC.GIFTTRANSACTION A
        LEFT JOIN PRODUCTION.REPL_NPC.USER U
            ON A."OwnerId" = U."Id"
    WHERE A."CreatedDate" > '2025-10-01' 
        AND U."Name" LIKE '%Integration%'
        AND A."RecordTypeId" = '012Vq000001Id46IAC' --Standard gifts
),
DONORDRIVE AS (
    SELECT 
        A."donationtransactionid" AS DD_TRANSACTION_ID,
        A."donationmodifieddate" AS DD_MODIFIED_DATE_RAW,
        A."donationentereddate" AS DD_ENTERED_DATE,
        A."donationdepositdate" AS DD_DEPOSIT_DATE,
        A."donationreceiptdate" AS DD_RECEIPT_DATE,
        A."donationpaymentdescription" AS DD_PAYMENT_DESCRIPTION,
        A."donationgiftdescription" AS DD_GIFT_DESCRIPTION,
        A."campid"  AS DD_CAMPAIGN_ID,
        A."letter_recipient_name" AS DD_RECIPIENT_NAME,
        A."donorconstituentid" AS DD_CONSTITUENT_ID,
        A."donationamount" AS DD_DONATION_AMOUNT,
        A."appeal_code" AS DD_APPEAL_CODE,
        A."donationreceiptid" AS DD_RECEIPT_ID,
        A."donorfirstname"  AS DD_FIRSTNAME,
        A."donorlastname" AS DD_LASTNAME,
        A."donationmessage" AS DD_DONATION_MESSAGE
    FROM PRODUCTION.REPL_DONORDRIVE.DD_DONATIONS_NEW A
    WHERE A."donationmodifieddate" > '2025-10-01'
        AND A."donationcreditcardtype" <> 'N/A'
        --AND A."donationpaymentdescription" NOT LIKE '%Recurring%'
    QUALIFY ROW_NUMBER() OVER(
        PARTITION BY A."donationtransactionid" 
        ORDER BY TRY_TO_TIMESTAMP_NTZ(A."donationmodifieddate") DESC
    ) = 1
)
SELECT
    *
FROM DONORDRIVE
    LEFT JOIN NPC
        ON DONORDRIVE.DD_RECEIPT_ID = NPC.NPC_DD_RECEIPT_ID
WHERE NPC.NPC_DD_RECEIPT_ID IS NULL
ORDER BY DD_RECEIPT_DATE;


SELECT * FROM PRODUCTION.REPL_DONORDRIVE.DD_DONATIONS A WHERE A.DONOR_FIRST_NAME LIKE '%Virginia%'



SELECT
    *
FROM PRODUCTION.REPL_NPC.MEMBERSHIP_FORM_SUBMISSION__C

SELECT
    *
FROM PRODUCTION.REPL_NPC.MEMBERSHIP_PRICE_BOOK_ENTRY__C

SELECT * FROM PRODUCTION.REPL_NPC.GIFTDESIGNATION WHERE "Description" ILIKE '%member%'


SELECT
    *
FROM PRODUCTION.REPL_NPC.TRANSACTION_LINE_ITEM__C
    LEFT JOIN PRODUCTION.REPL_NPC.MEMBERSHIP_FORM_SUBMISSION__C


SELECT * FROM PRODUCTION.REPL_NPC.GIFTTRANSACTION A 
    JOIN PRODUCTION.REPL_NPC.ACCOUNT B 
        ON A."DonorId" = B."Id" 


SELECT 
    A.*
FROM PRODUCTION.REPL_NPC.TRANSACTION_LINE_ITEM__C A
    LEFT JOIN PRODUCTION.REPL_NPC.GIFTTRANSACTION B
        ON A."Gift_Transaction__c" = B."Id"
    LEFT JOIN PRODUCTION.REPL_NPC.ACCOUNT C
        ON B."DonorId" = C."Id"

SELECT * FROM PRODUCTION.REPL_NPC.MEMBERSHIP__C







SELECT * FROM PRODUCTION.REPL_NPC.TRANSACTION_LINE_ITEM__C



SELECT * FROM TEST.PUBLICATIONS_AUTHOR_MANUSCRIPT.RESEARCHER_GRID_MATCH












/*
Testing
*/
with NPC AS (
    SELECT 
        A."Name" AS GT_NAME,
        A."CreatedDate" AS GT_CREATEDDATE,
        A."Id" AS GT_ID,
        A."CampaignId" AS GT_CAMPAIGN_ID,
        A."Donor_Drive_Revenue_Type__c" AS NPC_DD_REVENUE_TYPE,
        A."Donor_Drive_Payment_Description__c" AS NPC_DD_PAYMENT_DESCRIPTION,
        A."DD_Recurring_Profile_ID__c" AS NPC_DD_RECURRING_PROFILE,
        A."OwnerId" AS NPC_OWNER_ID,
        A."CampaignId" AS NPC_CAMPAIGN_ID,
        A."OriginalAmount" AS NPC_TRANS_AMOUNT,
        A."TransactionDate" AS NPC_TRANSACTION_DATE,
        A."DonorDrive_Receipt_Id__c" AS NPC_DD_RECEIPT_ID,
        A."OwnerId"
    FROM PRODUCTION.REPL_NPC.GIFTTRANSACTION A
        LEFT JOIN PRODUCTION.REPL_NPC.USER U
            ON A."OwnerId" = U."Id"
    WHERE A."CreatedDate" > '2025-10-01' 
        AND U."Name" LIKE '%Integration%'
        AND A."RecordTypeId" = '012Vq000001Id46IAC' --Standard gifts
),
DONORDRIVE AS (
    SELECT 
        A."donationtransactionid" AS DD_TRANSACTION_ID,
        A."donationmodifieddate" AS DD_MODIFIED_DATE_RAW,
        A."donationentereddate" AS DD_ENTERED_DATE,
        A."donationdepositdate" AS DD_DEPOSIT_DATE,
        A."donationreceiptdate" AS DD_RECEIPT_DATE,
        A."donationpaymentdescription" AS DD_PAYMENT_DESCRIPTION,
        A."donationgiftdescription" AS DD_GIFT_DESCRIPTION,
        A."campid"  AS DD_CAMPAIGN_ID,
        A."letter_recipient_name" AS DD_RECIPIENT_NAME,
        A."donorconstituentid" AS DD_CONSTITUENT_ID,
        A."donationamount" AS DD_DONATION_AMOUNT,
        A."appeal_code" AS DD_APPEAL_CODE,
        A."donationreceiptid" AS DD_RECEIPT_ID,
        A."donorfirstname"  AS DD_FIRSTNAME,
        A."donorlastname" AS DD_LASTNAME,
        A."donationmessage" AS DD_DONATION_MESSAGE
    FROM PRODUCTION.REPL_DONORDRIVE.DD_DONATIONS_NEW A
    WHERE A."donationmodifieddate" > '2025-10-01'
        AND A."donationcreditcardtype" <> 'N/A'
        --AND A."donationpaymentdescription" NOT LIKE '%Recurring%'
    QUALIFY ROW_NUMBER() OVER(
        PARTITION BY A."donationtransactionid" 
        ORDER BY TRY_TO_TIMESTAMP_NTZ(A."donationmodifieddate") DESC
    ) = 1
)
SELECT
    *,
    CASE WHEN NPC.NPC_DD_RECEIPT_ID IS NULL THEN 'Yes' ELSE 'No'  END AS NPC_RECEIPT_NULL,
    CASE WHEN NPC.NPC_CAMPAIGN_ID IS NULL THEN 'Yes' ELSE 'No' END AS NPC_CAMPAIGN_NULL
FROM DONORDRIVE
    LEFT JOIN NPC
        ON DONORDRIVE.DD_RECEIPT_ID = NPC.NPC_DD_RECEIPT_ID
            OR DONORDRIVE.DD_CAMPAIGN_ID = NPC.NPC_CAMPAIGN_ID
WHERE NPC.NPC_DD_RECEIPT_ID IS NULL OR NPC.NPC_CAMPAIGN_ID IS NULL
ORDER BY DD_RECEIPT_DATE;





SELECT * FROM PRODUCTION.REPL_DONORDRIVE.DD_DONATIONS_NEW A WHERE A."campid" NOT IN (SELECT )









SELECT DISTINCT LEN("DD_Campaign_ID__c") FROM PRODUCTION.REPL_NPC.CAMPAIGN;










SELECT * FROM  PRODUCTION.REPL_NPC.GIFTTRANSACTION

SELECT DISTINCT LEN("campid") FROM PRODUCTION.REPL_DONORDRIVE.DD_DONATIONS_NEW;


SELECT DISTINCT A."donationpaymentdescription" FROM PRODUCTION.REPL_DONORDRIVE.DD_DONATIONS_NEW A




GRANT USAGE ON DATABASE PRODUCTION TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA PRODUCTION.REPL_DONORDRIVE TO ROLE SYSADMIN;

-- Existing objects
GRANT SELECT ON ALL TABLES IN SCHEMA PRODUCTION.REPL_DONORDRIVE TO ROLE SYSADMIN;
GRANT SELECT ON ALL VIEWS  IN SCHEMA PRODUCTION.REPL_DONORDRIVE TO ROLE SYSADMIN;

-- New objects, going forward
GRANT SELECT ON FUTURE TABLES IN SCHEMA PRODUCTION.REPL_DONORDRIVE TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PRODUCTION.REPL_DONORDRIVE TO ROLE SYSADMIN;





GRANT SELECT ON FUTURE TABLES IN SCHEMA PRODUCTION.MART_DATACLOUD TO USER DATACLOUDSERVICE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA PRODUCTION.MART_DATACLOUD TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PRODUCTION.MART_DATACLOUD TO ROLE SYSADMIN;





DROP VIEW PRODUCTION.REPL_DONORDRIVE.DISCREPANCIES;









SELECT * FROM PRODUCTION.REPL_NPC.ACEM__EVENT_PACKAGE__C WHERE "acem__Event__c" = 'a33Vq0000002fErIAI' ORDER BY "acem__Sale_End_Date__c" DESC



SELECT * FROM

SELECT "Registra" FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_EVENT__C






SELECT 
    *
FROM PRODUCTION.REPL_DONORDRIVE.DD_DONATIONS_NEW A
WHERE A."donationmodifieddate" > '2025-10-01'
    AND "donationcreditcardtype" <> 'N/A'
    AND "donationpaymentdescription" NOT LIKE '%Recurring%';



    
SELECT * FROM LEAD_LISTS_DB.INBOUND_TABLE.INBOUND_UPLOADS
















SELECT * FROM PRODUCTION.REPL_NPC.ACEM__EVENT_TRANSACTION__C


SELECT * FROM TEST.NPC_MART_TEST.MART_MEETING_REGISTRATION











SELECT 
    A."Id", A."CreatedDate", A."Registration_Date__c", B."CreatedDate", A."Fon_Sales_Order__c", B.*
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_PARTICIPATION__C A 
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__SALES_ORDER__C B 
        ON A."Fon_Sales_Order__c" = B."Id"
WHERE A."Registration_Date__c"::DATE <> B."CreatedDate"::DATE
    --AND A."Id" = 'a4l8W000000f5DrQAI'




















SELECT 
    *
FROM PRODUCTION.REPL_NPC.ACEM__EVENT__C



SELECT * FROM PRODUCTION.REPL_NPC.ACEM__EVENT_BOOKING_ITEM__C


SELECT * FROM PRODUCTION.REPL_NPC.ACEM__EVENT_PARTICIPATION__C


SELECT * FROM PRODUCTION.REPL_NPC.ACEM__EVENT_PARTICIPATION__C A
    JOIN PRODUCTION.REPL_NPC.ACCOUNT B
        ON A."acem__Guest_As_Contact__c" = B.;






SELECT * FROM PRODUCTION.REPL_NPC.ACCOUNT A WHERE A."Name" LIKE '%Stryker%'





SELECT * FROM PRODUCTION.REPL_NPC.CONTACT


SELECT * FROM PRODUCTION.REPL_NPC.AACR_PROFESSIONAL_INVOLVEMENT__C

SELECT * FROM PRODUCTION.REPL_NPC.AACR_PROFESSIONAL_INVOLVEMENT_CATALOGUE__C



SELECT * FROM PRODUCTION.REPL_NPC.CONTACT_INTERESTS__C

SELECT * FROM 


SELECT 
    DISTINCT B."Name" 
FROM PRODUCTION.REPL_NPC.ACEM__EVENT__C A
LEFT JOIN PRODUCTION.REPL_NPC.RECORDTYPE B
    ON A."RecordTypeId" = B."Id"













SELECT * FROM PRODUCTION.REPL_NPC.MEMBERSHIP__C





SELECT * FROM PRODUCTION.REPL_NPC.TRANSACTION_LINE_ITEM__C






SELECT * FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_HISTORY_FINAL