-- raw dupes
select * from DEV.Craig.CutoverDeDupe

-- combined report based on raw dupes
select * from DEV.Craig.CUTOVERDEDUPE_FLAGS


SELECT * FROM TEST.TEST_AREA.REPROCESS_GRIDS where PERSONEMAIL = 'filipa.moreira@unibe.ch';

--


SELECT "Golden_Record_ID__c" FROM PRODUCTION.REPL_NPC.ACCOUNT WHERE "Id" IN (SELECT ID FROM TEST.TEST_AREA.REPROCESS_GRIDS)

SELECT * FROM IDR.RESULTS.UNIQUEID



SELECT * FROM TEST.TEST_AREA.IDR_EMAILS_TO_DELETE;


SELECT  FROM TEST.TEST_AREA.IDR_EMAILS_TO_DELETE A
    JOIN IDR.RESULTS.EMAIL B
        ON LOWER(TRIM(A.EMAIL)) = LOWER(TRIM(B."Email"))

SELECT * FROM TEST.TEST_AREA.IDR_EMAILS_TO_DELETE A
    JOIN IDR.RESULTS.PERSON B
        ON LOWER(TRIM(A.EMAIL)) = LOWER(TRIM(B.ORIGIN_LEGACY_ID))

--REGEXP_REPLACE("PersonEmail", '\\.invalid$', '')


SELECT * FROM TEST.TEST_AREA.IDR_EMAILS_TO_DELETE A
    JOIN IDR.RESULTS.EMAIL B
        ON LOWER(TRIM(REGEXP_REPLACE(A.EMAIL, '\\.invalid$', ''))) = LOWER(TRIM(REGEXP_REPLACE(B."Email", '\\.invalid$', '')))



with ToDelete AS (
    SELECT 
        A.*,
        REGEXP_REPLACE(A.PERSONEMAIL, '\\.invalid$', '') AS CLEAN_EMAIL,
        B."Legacy_ID__c" AS FONTEVA_ID 
    FROM TEST.TEST_AREA.REPROCESS_GRIDS A
        JOIN PRODUCTION.REPL_NPC.ACCOUNT B
            ON A.ID = B."Id"
    WHERE A.PERSONEMAIL IS NOT NULL
),
Emails AS (
    SELECT * FROM IDR.RESULTS.EMAIL A WHERE A."Email" IN (SELECT CLEAN_EMAIL FROM ToDelete)
),
Persons AS (
    SELECT * FROM IDR.RESULTS.EMAIL A WHERE A."Email" IN (SELECT CLEAN_EMAIL FROM ToDelete) 
)
SELECT * FROM Emails


with badpeople AS (
SELECT 
    *
FROM IDR.RESULTS.EMAIL B
    LEFT JOIN TEST.TEST_AREA.IDR_EMAILS_TO_DELETE A
        ON LOWER(TRIM(REGEXP_REPLACE(A.EMAIL, '\\.invalid$', ''))) = LOWER(TRIM(REGEXP_REPLACE(B."Email", '\\.invalid$', '')))
WHERE A.EMAIL IS NOT NULL
)
SELECT * FROM IDR.RESULTS.EMAIL WHERE "PersonId" IN (SELECT "PersonId" FROM badpeople)

with ToDelete AS (
    SELECT 
        CONCAT(A.FIRSTNAME, A.LASTNAME, LOWER(TRIM(REGEXP_REPLACE(A.PERSONEMAIL, '\\.invalid$', '')))) AS PERSON_KEY
    FROM TEST.TEST_AREA.REPROCESS_GRIDS A
    WHERE A.PERSONEMAIL IS NOT NULL
),
IDRS AS (
    SELECT 
        CONCAT(B."FirstName", B."LastName", LOWER(TRIM(REGEXP_REPLACE(A."Email", '\\.invalid$', '')))) AS PERSON_KEY
    FROM IDR.RESULTS.EMAIL A
        JOIN IDR.RESULTS.PERSON B
            ON A."PersonId" = B."Id"
)
SELECT * FROM IDRS
    JOIN ToDelete
        ON IDRS.PERSON_KEY = ToDelete.PERSON_KEY;


//Craigs master file below
        
//contains grids of people to delete 
SELECT * FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT


//discrepancies between grid fields, only 1 person - 1136951/1080417 Shoaib Ahmed AACR ID 1089110 NPC ID 001Vq00000U7mkPIAR
SELECT * FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT WHERE GOLDEN_RECORD_ID__C IS NOT NULL AND GOLDEN_RECORD_ID__C <> GOLDEN_RECORD_ID


with IDRS AS (
    SELECT 
        A."Email",
        B."Id",
        B.ORIGIN_LEGACY_ID,
        B."FirstName",
        B."LastName"
    FROM IDR.RESULTS.EMAIL A
        JOIN IDR.RESULTS.PERSON B
            ON A."PersonId" = B."Id"
)
SELECT * FROM IDRS A
    JOIN TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT B
        ON A."Email" = B.PERSONEMAIL
        OR A."Id" = B.GOLDEN_RECORD_ID
        OR A."Id" = B.GOLDEN_RECORD_ID
        OR A.ORIGIN_LEGACY_ID = B.ID
        OR A.ORIGIN_LEGACY_ID = B.PERSONEMAIL        

        
//person records to delete- 1,299
with GRIDS_TO_DELETE AS (
    SELECT DISTINCT GOLDEN_RECORD_ID AS GRID FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT
    UNION ALL 
    SELECT DISTINCT GOLDEN_RECORD_ID__C AS GRID FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT
)
SELECT * FROM IDR.RESULTS.PERSON 
WHERE "Id" IN (SELECT GRID FROM GRIDS_TO_DELETE)
    OR ORIGIN_LEGACY_ID IN (SELECT REGEXP_REPLACE(PERSONEMAIL, '\\.invalid$', '') FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT)

//email records to delete - 1,238
with GRIDS_TO_DELETE AS (
    SELECT DISTINCT GOLDEN_RECORD_ID AS GRID FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT
    UNION ALL 
    SELECT DISTINCT GOLDEN_RECORD_ID__C AS GRID FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT
)
SELECT * FROM IDR.RESULTS.EMAIL 
WHERE "PersonId" IN (SELECT GRID FROM GRIDS_TO_DELETE)
    OR "Email" IN (SELECT REGEXP_REPLACE(PERSONEMAIL, '\\.invalid$', '') FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT)



//to potentially delete from leads
with GRIDS_TO_DELETE AS (
    SELECT DISTINCT GOLDEN_RECORD_ID AS GRID FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT
    UNION ALL 
    SELECT DISTINCT GOLDEN_RECORD_ID__C AS GRID FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT
)
SELECT * FROM LEAD_LISTS_DB.RESULTS_TABLE.RESULTS
WHERE GOLDEN_RECORD_ID IN (SELECT GRID FROM IDR.BACKUP_TABLES.GRID_TO_DELETE)
    OR EMAIL IN (SELECT REGEXP_REPLACE(PERSONEMAIL, '\\.invalid$', '') FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT)








/********************************************************

PROCESS BELOW

-1. Create backups & test
0. Create table with all GRIDS to delete
1. Delete records from EMAIL
2. Delete records from PERSON
3. Delete records from UNIQUEID?
4. Delete records from LEADS?




********************************************************/
// -1. Create backups
CREATE OR REPLACE TABLE IDR.BACKUP_TABLES.EMAIL_BACKUP
AS
SELECT * FROM IDR.RESULTS.EMAIL;

CREATE OR REPLACE TABLE IDR.BACKUP_TABLES.PERSON_BACKUP
AS
SELECT * FROM IDR.RESULTS.PERSON;

CREATE OR REPLACE TABLE IDR.BACKUP_TABLES.UNIQUE_ID_BACKUP
AS
SELECT * FROM IDR.RESULTS.UNIQUEID;



// 0. Master table of GRIDS to delete
CREATE OR REPLACE TABLE IDR.BACKUP_TABLES.GRID_TO_DELETE
AS 
with GRIDS_TO_DELETE AS (
    SELECT DISTINCT GOLDEN_RECORD_ID AS GRID FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT
    UNION ALL 
    SELECT DISTINCT GOLDEN_RECORD_ID__C AS GRID FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT
),
PERSONS AS (
    SELECT DISTINCT "Id" AS GRID FROM IDR.RESULTS.PERSON WHERE "Id" IN (SELECT GRID FROM GRIDS_TO_DELETE)
),
EMAILS AS (
    SELECT DISTINCT "PersonId" AS GRID FROM IDR.RESULTS.EMAIL 
    WHERE "PersonId" IN (SELECT GRID FROM GRIDS_TO_DELETE)
        OR "Email" IN (SELECT REGEXP_REPLACE(PERSONEMAIL, '\\.invalid$', '') FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT)
),
FINAL_LIST AS (
    SELECT GRID FROM PERSONS UNION ALL SELECT GRID FROM EMAILS
)
SELECT DISTINCT GRID FROM FINAL_LIST
; --1,314


// 1. Delete records from EMAIL
DELETE FROM IDR.RESULTS.EMAIL e
WHERE e."PersonId" IN (
    SELECT GOLDEN_RECORD_ID        FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT
    UNION DISTINCT
    SELECT GOLDEN_RECORD_ID__C     FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT
)
OR REGEXP_REPLACE(e."Email", '\\.invalid$', '') IN (
    SELECT REGEXP_REPLACE(PERSONEMAIL, '\\.invalid$', '')
    FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT
    WHERE PERSONEMAIL IS NOT NULL
); --1,242


// 2. Delete records from PERSON
DELETE FROM IDR.RESULTS.PERSON p
WHERE p."Id" IN (
    SELECT GOLDEN_RECORD_ID        FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT
    UNION DISTINCT
    SELECT GOLDEN_RECORD_ID__C     FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT
)
OR REGEXP_REPLACE(p.ORIGIN_LEGACY_ID, '\\.invalid$', '') IN (
    SELECT REGEXP_REPLACE(PERSONEMAIL, '\\.invalid$', '')
    FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT
    WHERE PERSONEMAIL IS NOT NULL
); --1,299

DELETE FROM IDR.RESULTS.PERSON P WHERE P."Id" IN (SELECT GRID FROM IDR.BACKUP_TABLES.GRID_TO_DELETE); --5











// 4. Delete from leads - 422
DELETE FROM LEAD_LISTS_DB.RESULTS_TABLE.RESULTS
WHERE GOLDEN_RECORD_ID IN (SELECT GRID FROM IDR.BACKUP_TABLES.GRID_TO_DELETE)
    OR EMAIL IN (SELECT REGEXP_REPLACE(PERSONEMAIL, '\\.invalid$', '') FROM TEST.TEST_AREA.CUTOVER_DEDUPE_REPORT);
