/*Foundation Meeting Registration*/

CREATE OR REPLACE VIEW PRODUCTION.MART_MEETING_REGISTRATION.FOUNDATION_MEETING_REGISTRATION
AS
with RecentGift AS (
    SELECT
        "npe01__Contact_Id_for_Role__c" AS CONTACT_ID1,
        SUM("Amount") AS TOTAL_AMOUNT,
        COUNT("Id") AS TOTAL_OPPORTUNITIES
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY
GROUP BY 1
),
Recent AS (
    SELECT
        "npe01__Contact_Id_for_Role__c" AS CONTACT_ID,
        "CloseDate" DATE_OF_MOST_RECENT_DONATION,
        ROW_NUMBER() OVER(PARTITION BY "npe01__Contact_Id_for_Role__c" ORDER BY "CloseDate" DESC) AS ROW_ORDER,
        "Amount" AS MOST_RECENT_DONATION_AMOUNT
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY
),
MostRecent AS (
    SELECT 
        *
    FROM Recent
    WHERE ROW_ORDER = 1
)
SELECT
    MR.*,
    CON."Id",
    MostRecent.MOST_RECENT_DONATION_AMOUNT AS MOST_RECENT_DONATION_AMOUNT,
    MostRecent.DATE_OF_MOST_RECENT_DONATION AS DATE_OF_MOST_RECENT_DONATION,
    RecentGift.TOTAL_AMOUNT AS TOTAL_DONATION_AMOUNT,
    RecentGift.TOTAL_OPPORTUNITIES AS TOTAL_OPPORTUNITIES
FROM PRODUCTION.MART_MEETING_REGISTRATION.MEETING_REGISTRATIONS_BACKUP AS MR
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON
        ON MR.CONTACT_ID = CON."Id"
    LEFT JOIN MostRecent
        ON CON."Id" = MostRecent.CONTACT_ID
    LEFT JOIN RecentGift
        ON CON."Id" = RecentGift.CONTACT_ID1
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_EVENT__C AS EV
        ON MR.EVENT_ID = EV."Id";






SELECT 
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY AS OPP
WHERE OPP."npe01__Contact_Id_for_Role__c" IN (SELECT CONTACT_ID FROM PRODUCTION.MART_MEETING_REGISTRATION.MEETING_REGISTRATIONS_BACKUP);

SELECT 
    MAX("CloseDate")
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY AS OPP
WHERE OPP."npe01__Contact_Id_for_Role__c" = '0031I00000Wsp8CQAR';