/*

This file contains some example GRANT commands that are frequently used to 
add/edit permissions on views and tables in Snowflake. 

 */

GRANT usage ON ALL schemas in database PRODUCTION TO ROLE SYSADMIN;
GRANT select ON ALL tables in database PRODUCTION TO ROLE SYSADMIN;
GRANT select ON ALL views in database PRODUCTION TO ROLE SYSADMIN;


GRANT SELECT ON ALL TABLES IN SCHEMA PRODUCTION.REPL_RINGGOLD TO ROLE SYSADMIN;

GRANT SELECT ON ALL TABLES IN SCHEMA PRODUCTION.REPL_RINGGOLD TO ROLE INTERN;

GRANT usage ON schema PRODUCTION.MART_MEETING_REGISTRATION TO ROLE INTERN;

GRANT SELECT ON ALL VIEWS IN SCHEMA PRODUCTION.MART_MEETING_REGISTRATION TO ROLE INTERN;


SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_EVENT__C WHERE "Name" LIKE '%Disparities%';





SELECT 
    COUNT(*), 
    SUM(CASE WHEN A."BillingCity" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN A."BillingCity" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN A."BillingCity" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN A."BillingCity" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS A;

SELECT 
    COUNT(*), 
    SUM(CASE WHEN B."BillingCity" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN B."BillingCity" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN B."BillingCity" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN B."BillingCity" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT B;