USE WAREHOUSE COMPUTE_WH;

USE DATABASE IMISDATA;

SELECT * FROM IMISDATA.DBO.ACTIVITY
LIMIT 20;

SELECT
    ACTIVITY_TYPE,
    COUNT(*) AS activity_count
FROM IMISDATA.DBO.ACTIVITY
GROUP BY ACTIVITY_TYPE
ORDER BY 2 DESC;

SELECT
    PRODUCT_CODE,
    COUNT(*) AS prod_code_count
FROM IMISDATA.DBO.ACTIVITY
GROUP BY 1
ORDER BY 1 DESC;

SELECT MEMBER_TYPE, COUNT(*) FROM IMISDATA.DBO.ACTIVITY
GROUP BY 1
LIMIT 50;

SELECT * FROM IMISDATA.DBO.CONTACTMAIN
LIMIT 20;

SELECT * FROM IMISDATA.DBO.CONTACT
LIMIT 20;

SELECT * FROM IMISDATA.DBO.ACTIVITY
LIMIT 50;

SELECT 
    SUM(AMOUNT),
    MIN(THRU_DATE)
FROM IMISDATA.DBO.ACTIVITY
--WHERE ACTIVITY_TYPE = 'DUES'
--GROUP BY ORIGINATING_TRANS_NUM
--ORDER BY 1 DESC
LIMIT 50;

SELECT MEMBER_TYPE, COUNT(*)
FROM IMISDATA.DBO.ACTIVITY
GROUP BY MEMBER_TYPE
ORDER BY 2 DESC;

SELECT 
    COUNT(*)
FROM IMISDATA.DBO.EVENT_PARTICIPATION
LIMIT 50;

SELECT * FROM IMISDATA.DBO.DEMOGRAPHICS
LIMIT 50;

SELECT MIN(APP_DATE) FROM IMISDATA.DBO.DEMOGRAPHICS;

SELECT SPONSOR1, COUNT(*) FROM IMISDATA.DBO.DEMOGRAPHICS
GROUP BY SPONSOR1
ORDER BY 2 DESC
LIMIT 50;



SELECT * FROM IMISDATA.DBO.ACTIVITY
WHERE ID = '3966'
ORDER BY TRANSACTION_DATE ASC
LIMIT 50;


SELECT
    ACTIVITY_TYPE,
    COUNT(*) AS activity_count
FROM IMISDATA.DBO.ACTIVITY
WHERE ID = '3966'
GROUP BY ACTIVITY_TYPE
ORDER BY 2 DESC;

SELECT
    PRODUCT_CODE,
    COUNT(*)
FROM IMISDATA.DBO.ACTIVITY
WHERE PRODUCT_CODE IS NOT NULL
GROUP BY PRODUCT_CODE
ORDER BY 2 DESC
LIMIT 50;

SELECT
    COUNT(DISTINCT PRODUCT_CODE)
FROM IMISDATA.DBO.ACTIVITY
WHERE PRODUCT_CODE IS NOT NULL
LIMIT 50;



SELECT
    COUNT(DISTINCT ID)
FROM IMISDATA.DBO.ACTIVITY;



SELECT * FROM IMISDATA.DBO.ACTIVITY_TEMP
LIMIT 50;

SELECT MIN(CREATEDON)
FROM IMISDATA.DBO.CONTACTMAIN;

SELECT * FROM IMISDATA.DBO.APPEAL
LIMIT 50;

SELECT * FROM IMISDATA.DBO.CONTACTS2SALESFORCE LIMIT 20;

SELECT * FROM PRODUCTION.NCBI_STAGE.NCBI_PUBMEDARTICLE_MEDLINECITATION_AUTHOR 
WHERE AFFILIATION IS NOT NULL
LIMIT 20;

SELECT *
FROM PRODUCTION.REPL_SALESFORCE.EVENTS
WHERE EVENT_NAME LIKE '%AM%' OR EVENT_NAME LIKE '%Annual Meeting%'
LIMIT 50;

SELECT DISTINCT LOCATION FROM PRODUCTION.REPL_SALESFORCE.EVENTS LIMIT 50;

SELECT SRC_START_DATE, SRC_END_DATE
FROM PRODUCTION.REPL_SALESFORCE.EVENTS
LIMIT 20;

SELECT COUNT(DISTINCT EMAIL)
FROM PRODUCTION.REPL_SALESFORCE.CONTACTS;

/* important fields according to Kenan
'ABSINFRAC',
'ABSTRACT',
'AWARD',
'COMMITTEE',
'CV',
'DECEASED',
'DUES',
'EVENT',
'EVENTPART',
'EVENTSPONS',
'GRANT',
'MAJACC',
'MEETING',
'MEETINGS',
'MEMARCH',
'MEMBEN',
'MEMBERMERG',
'MEMNOTES',
'MEMSTATCHA',
'MENTOR',
'RECRUITMENT',
'RETENTION',
'SPA',
'SPEAKER',
'VOTE',
'WORKSHOP',
'WORKSHOPA'
*/


/* iMIS Activity Table split queries below */
CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."ABSINFRAC"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'ABSINFRAC';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."ABSTRACT"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'ABSTRACT';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."AWARD"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'AWARD';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."COMMITTEE"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'COMMITTEE';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."CV"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'CV';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."DECEASED"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'DECEASED';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."DUES"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'DUES'; --seems to be biggest, 1,131,573 records

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."EVENT"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'EVENT';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."EVENTPART"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'EVENTPART';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."EVENTSPONS"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'EVENTSPONS'; --4 rows

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."GRANT"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'GRANT'; --3 rows

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."MAJACC"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'MAJACC';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."MEETING"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'MEETING';


SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'MEETINGS'; --Empty

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."MEMARCH"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'MEMARCH';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."MEMBEN"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'MEMBEN';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."MEMBERMERG"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'MEMBERMERG';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."MEMNOTES"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'MEMNOTES';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."MEMSTATCHA"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'MEMSTATCHA';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."MENTOR"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'MENTOR';


SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'RECRUITMENT'; --Empty

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."RETENTION"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'RETENTION'; --Delinquent payments

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."SPA"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'SPA';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."SPEAKER"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'SPEAKER';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."VOTE"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'VOTE';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."WORKSHOP"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'WORKSHOP';

CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."WORKSHOPAP"
AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'WORKSHOPAP';


SELECT
    ACTIVITY_TYPE,
    MIN(UF_1),
    MAX(UF_1)
FROM IMISDATA.DBO.ACTIVITY
WHERE UF_1 IS NOT NULL
GROUP BY ACTIVITY_TYPE;

with Random10 AS (
    SELECT
        *,
        ROW_NUMBER() OVER(PARTITION BY ACTIVITY_TYPE ORDER BY RANDOM()) AS RowNo
    FROM IMISDATA.DBO.ACTIVITY
    WHERE UF_1 IS NOT NULL
)
SELECT
    ID,
    ACTIVITY_TYPE,
    UF_1
FROM Random10
WHERE RowNo <= 30 AND ACTIVITY_TYPE IN('ABSINFRAC',
'ABSTRACT',
'AWARD',
'COMMITTEE',
'CV',
'DECEASED',
'DUES',
'EVENT',
'EVENTPART',
'EVENTSPONS',
'GRANT',
'MAJACC',
'MEETING',
'MEETINGS',
'MEMARCH',
'MEMBEN',
'MEMBERMERG',
'MEMNOTES',
'MEMSTATCHA',
'MENTOR',
'RECRUITMENT',
'RETENTION',
'SPA',
'SPEAKER',
'VOTE',
'WORKSHOP',
'WORKSHOPA');


/*
JOURNAL_TITLE = 
VAR item_name = JOURNAL_SALES_FINAL[ITEM_NAME]
RETURN
SWITCH(
    TRUE()
    CONTAINSSTRING(item_name, "Blood Cancer Discovery"), "Blood Cancer Discovery"
    CONTAINSSTRING(item_name, "Cancer Discovery"), "Cancer Discovery"
    CONTAINSSTRING(item_name, "Clinical Cancer Research"), "Clinical Cancer Research"
    CONTAINSSTRING(item_name, "Molecular Cancer Research"), "Molecular Cancer Research"
    CONTAINSSTRING(item_name, "Cancer Research Communications"), "Cancer Research Communications"
    CONTAINSSTRING(item_name, "Cancer Research"), "Cancer Research"
    CONTAINSSTRING(item_name, "Cancer Epidemiology, Biomarkers, & Prevention"), "Cancer Epidemiology, Biomarkers, & Prevention"
    CONTAINSSTRING(item_name, "Cancer Immunology Research"), "Cancer Immunology Research"
    CONTAINSSTRING(item_name, "Cancer Prevention Research"), "Cancer Prevention Research"
    CONTAINSSTRING(item_name, "Molecular Cancer Therapeutics"), "Molecular Cancer Therapeutics"
)

 */

 with Distincts AS (
    SELECT DISTINCT
        ID,
        ACTIVITY_TYPE,
        UF_1
    FROM IMISDATA.DBO.ACTIVITY
    WHERE UF_1 IS NOT NULL
)
SELECT
    *
FROM Distincts
WHERE ACTIVITY_TYPE IN('ABSINFRAC',
'ABSTRACT',
'AWARD',
'COMMITTEE',
'CV',
'DECEASED',
'DUES',
'EVENT',
'EVENTPART',
'EVENTSPONS',
'GRANT',
'MAJACC',
'MEETING',
'MEETINGS',
'MEMARCH',
'MEMBEN',
'MEMBERMERG',
'MEMNOTES',
'MEMSTATCHA',
'MENTOR',
'RECRUITMENT',
'RETENTION',
'SPA',
'SPEAKER',
'VOTE',
'WORKSHOP',
'WORKSHOPA')
ORDER BY 1;




SELECT DISTINCT MEETING_YEAR FROM PRODUCTION.MART_AM_MEETING_REGISTRATION.REGISTRANTS;

SELECT DISTINCT I_WILL_BE_ATTENDING FROM PRODUCTION.MART_MEETING_REGISTRATION.MEETING_REGISTRATIONS;


SELECT * FROM PRODUCTION.REPL_SALESFORCE.SALES_ORDER_LINES ORDER BY RANDOM() LIMIT 1000;

SELECT * FROM  TEST.IMIS_ACTIVITIES.ABSINFRAC;

ALTER TABLE TEST.IMIS_ACTIVITIES.ABSINFRAC RENAME COLUMN "UF_1" TO "EVENT_CODE";
ALTER TABLE TEST.IMIS_ACTIVITIES.ABSINFRAC RENAME COLUMN "UF_2" TO "SP_DECLINE_ID";
ALTER TABLE TEST.IMIS_ACTIVITIES.ABSINFRAC RENAME COLUMN "UF_3" TO "STATUS";

ALTER TABLE TEST.IMIS_ACTIVITIES.ABSTRACT RENAME COLUMN "NOTE" TO "ABSTRACT_TITLE";
ALTER TABLE TEST.IMIS_ACTIVITIES.ABSTRACT RENAME COLUMN "SOURCE_CODE" TO "SPONSOR";
ALTER TABLE TEST.IMIS_ACTIVITIES.ABSTRACT RENAME COLUMN "UF_1" TO "STATUS";
ALTER TABLE TEST.IMIS_ACTIVITIES.ABSTRACT RENAME COLUMN "UF_2" TO "PRIMARY_CATEGORY";
ALTER TABLE TEST.IMIS_ACTIVITIES.ABSTRACT RENAME COLUMN "UF_3" TO "PROGRAM";
ALTER TABLE TEST.IMIS_ACTIVITIES.ABSTRACT RENAME COLUMN "DESCRIPTION" TO "ROLE";
ALTER TABLE TEST.IMIS_ACTIVITIES.ABSTRACT RENAME COLUMN "ACTION_CODES" TO "SESSION_NUMBER";
ALTER TABLE TEST.IMIS_ACTIVITIES.ABSTRACT RENAME COLUMN "UF_4" TO "CONTROL_NUMBER";
ALTER TABLE TEST.IMIS_ACTIVITIES.ABSTRACT RENAME COLUMN "UF_5" TO "PRESENTATION_NUMBER";


ALTER TABLE TEST.IMIS_ACTIVITIES.AWARD RENAME COLUMN "NOTE" TO "TITLE";
ALTER TABLE TEST.IMIS_ACTIVITIES.AWARD RENAME COLUMN "EFFECTIVE_DATE" TO "YEAR_OF_AWARD";
ALTER TABLE TEST.IMIS_ACTIVITIES.AWARD RENAME COLUMN "SOURCE_CODE" TO "ASSIGNED_TO";
ALTER TABLE TEST.IMIS_ACTIVITIES.AWARD RENAME COLUMN "UF_1" TO "APPLICANT_TYPE";
ALTER TABLE TEST.IMIS_ACTIVITIES.AWARD RENAME COLUMN "UF_2" TO "AWARD_TYPE";
ALTER TABLE TEST.IMIS_ACTIVITIES.AWARD RENAME COLUMN "UF_3" TO "SPECIAL_BENEFIT";
ALTER TABLE TEST.IMIS_ACTIVITIES.AWARD RENAME COLUMN "DESCRIPTION" TO "AWARD_NAME";
ALTER TABLE TEST.IMIS_ACTIVITIES.AWARD RENAME COLUMN "UF_4" TO "CANDIDATE_NOMINATED";
ALTER TABLE TEST.IMIS_ACTIVITIES.AWARD RENAME COLUMN "UF_5" TO "APPLICANT_ID";
ALTER TABLE TEST.IMIS_ACTIVITIES.AWARD RENAME COLUMN "UF_6" TO "AWARD_CHECK_SEN";


ALTER TABLE TEST.IMIS_ACTIVITIES.COMMITTEE RENAME COLUMN "EFFECTIVE_DATE" TO "FROM";
ALTER TABLE TEST.IMIS_ACTIVITIES.COMMITTEE RENAME COLUMN "UF_1" TO "RESPONSE";
ALTER TABLE TEST.IMIS_ACTIVITIES.COMMITTEE RENAME COLUMN "UF_2" TO "AFFIL_AT_INDUCT";
ALTER TABLE TEST.IMIS_ACTIVITIES.COMMITTEE RENAME COLUMN "UF_3" TO "USER_ID";
ALTER TABLE TEST.IMIS_ACTIVITIES.COMMITTEE RENAME COLUMN "DESCRIPTION" TO "COMMITTEE";
ALTER TABLE TEST.IMIS_ACTIVITIES.COMMITTEE RENAME COLUMN "ACTION_CODES" TO "POSITION";
ALTER TABLE TEST.IMIS_ACTIVITIES.COMMITTEE RENAME COLUMN "UF_6" TO "INVITATION_DATE";
ALTER TABLE TEST.IMIS_ACTIVITIES.COMMITTEE RENAME COLUMN "UF_7" TO "RESPONSE_DATE";



ALTER TABLE TEST.IMIS_ACTIVITIES.CV RENAME COLUMN "EFFECTIVE_DATE" TO "DATE_RECEIVED";
ALTER TABLE TEST.IMIS_ACTIVITIES.CV RENAME COLUMN "SOURCE_CODE" TO "ENTERED_BY";
ALTER TABLE TEST.IMIS_ACTIVITIES.CV RENAME COLUMN "UF_1" TO "CV_PURPOSE";
ALTER TABLE TEST.IMIS_ACTIVITIES.CV RENAME COLUMN "UF_2" TO "URL_TO_CV";


ALTER TABLE TEST.IMIS_ACTIVITIES.DECEASED RENAME COLUMN "NOTE" TO "AACR_ACKNOWLEDGMENTS";
ALTER TABLE TEST.IMIS_ACTIVITIES.DECEASED RENAME COLUMN "EFFECTIVE_DATE" TO "DATE_RECEIVED";
ALTER TABLE TEST.IMIS_ACTIVITIES.DECEASED RENAME COLUMN "SOURCE_CODE" TO "ASSIGNED_TO";
ALTER TABLE TEST.IMIS_ACTIVITIES.DECEASED RENAME COLUMN "UF_1" TO "SOURCE";
ALTER TABLE TEST.IMIS_ACTIVITIES.DECEASED RENAME COLUMN "UF_2" TO "TYPE_OF_FILE";


ALTER TABLE TEST.IMIS_ACTIVITIES.DUES RENAME COLUMN "EFFECTIVE_DATE" TO "BEGIN_DATE";
ALTER TABLE TEST.IMIS_ACTIVITIES.DUES RENAME COLUMN "UF_1" TO "BATCH_NUMBER";
ALTER TABLE TEST.IMIS_ACTIVITIES.DUES RENAME COLUMN "UF_2" TO "CHECK_NUMBER";
ALTER TABLE TEST.IMIS_ACTIVITIES.DUES RENAME COLUMN "UF_3" TO "USER_ID";
ALTER TABLE TEST.IMIS_ACTIVITIES.DUES RENAME COLUMN "LEVEL" TO "ACTION_CODES";
ALTER TABLE TEST.IMIS_ACTIVITIES.DUES RENAME COLUMN "UF_4" TO "YEAR_WAIVED";
ALTER TABLE TEST.IMIS_ACTIVITIES.DUES RENAME COLUMN "UF_6" TO "HW_DATE";



ALTER TABLE TEST.IMIS_ACTIVITIES.EVENT RENAME COLUMN "UF_1" TO "EVENT_LOCATION";
ALTER TABLE TEST.IMIS_ACTIVITIES.EVENT RENAME COLUMN "UF_4" TO "EVENT_YEAR";
ALTER TABLE TEST.IMIS_ACTIVITIES.EVENT RENAME COLUMN "UF_6" TO "BEGIN_DATE";
ALTER TABLE TEST.IMIS_ACTIVITIES.EVENT RENAME COLUMN "UF_7" TO "END_DATE";



ALTER TABLE TEST.IMIS_ACTIVITIES.EVENTPART RENAME COLUMN "NOTE" TO "PRESENTATION_INFO";
ALTER TABLE TEST.IMIS_ACTIVITIES.EVENTPART RENAME COLUMN "UF_1" TO "ROLE";
ALTER TABLE TEST.IMIS_ACTIVITIES.EVENTPART RENAME COLUMN "UF_2" TO "EVENT_CODE";
ALTER TABLE TEST.IMIS_ACTIVITIES.EVENTPART RENAME COLUMN "UF_3" TO "STATUS";
ALTER TABLE TEST.IMIS_ACTIVITIES.EVENTPART RENAME COLUMN "DESCRIPTION" TO "SESSION_NAME";


ALTER TABLE TEST.IMIS_ACTIVITIES."GRANT" RENAME COLUMN "SOURCE_CODE" TO "ASSIGNED_TO";
ALTER TABLE TEST.IMIS_ACTIVITIES."GRANT" RENAME COLUMN "UF_3" TO "ROLE";
ALTER TABLE TEST.IMIS_ACTIVITIES."GRANT" RENAME COLUMN "OTHER_CODE" TO "COMMITTEE";
ALTER TABLE TEST.IMIS_ACTIVITIES."GRANT" RENAME COLUMN "DESCRIPTION" TO "GRANT_ID";
ALTER TABLE TEST.IMIS_ACTIVITIES."GRANT" RENAME COLUMN "UF_6" TO "GRANT_YEAR";



ALTER TABLE TEST.IMIS_ACTIVITIES.MAJACC RENAME COLUMN "UF_1" TO "CATEGORY_CODE";


ALTER TABLE TEST.IMIS_ACTIVITIES.MEETING RENAME COLUMN "EFFECTIVE_DATE" TO "BEGIN_DATE";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEETING RENAME COLUMN "SOURCE_CODE" TO "BOOTH_VISIT";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEETING RENAME COLUMN "UF_1" TO "REG_CLASS";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEETING RENAME COLUMN "UF_2" TO "FUNCTION_CODE";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEETING RENAME COLUMN "UF_3" TO "ATTENDANCE";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEETING RENAME COLUMN "DESCRIPTION" TO "TITLE";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEETING RENAME COLUMN "AMOUNT" TO "FEE";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEETING RENAME COLUMN "UF_4" TO "EXT_REG_NUMBER";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEETING RENAME COLUMN "UF_6" TO "END_DATE";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEETING RENAME COLUMN "UF_7" TO "REG_DATE";


ALTER TABLE TEST.IMIS_ACTIVITIES.MEMARCH RENAME COLUMN "UF_1" TO "YEAR";


ALTER TABLE TEST.IMIS_ACTIVITIES.MEMBEN RENAME COLUMN "EFFECTIVE_DATE" TO "MAIL_DATE";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEMBEN RENAME COLUMN "SOURCE_CODE" TO "ASSIGNED_TO";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEMBEN RENAME COLUMN "UF_1" TO "REISSUE_REASON";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEMBEN RENAME COLUMN "UF_2" TO "JOURNAL";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEMBEN RENAME COLUMN "UF_3" TO "SOURCE";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEMBEN RENAME COLUMN "ACTION_CODES" TO "LEVEL";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEMBEN RENAME COLUMN "UF_4" TO "MEMBERSHIP_YEAR";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEMBEN RENAME COLUMN "UF_6" TO "REISSUE_DATE";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEMBEN RENAME COLUMN "UF_7" TO "REISSUE_REQUEST";




ALTER TABLE TEST.IMIS_ACTIVITIES.MEMBERMERG RENAME COLUMN "UF_1" TO "MERGED_ID";


ALTER TABLE TEST.IMIS_ACTIVITIES.MEMNOTES RENAME COLUMN "SOURCE_CODE" TO "ASSIGNED_TO";



ALTER TABLE TEST.IMIS_ACTIVITIES.MEMSTATCHA RENAME COLUMN "SOURCE_CODE" TO "ASSIGNED_TO";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEMSTATCHA RENAME COLUMN "UF_1" TO "MOVE_DESC";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEMSTATCHA RENAME COLUMN "UF_2" TO "REASON";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEMSTATCHA RENAME COLUMN "UF_3" TO "ReinResDelin_MT";
ALTER TABLE TEST.IMIS_ACTIVITIES.MEMSTATCHA RENAME COLUMN "ACTION_CODES" TO "SOURCE_CODE";


ALTER TABLE TEST.IMIS_ACTIVITIES.MENTOR RENAME COLUMN "EFFECTIVE_DATE" TO "BEGIN_DATE";
ALTER TABLE TEST.IMIS_ACTIVITIES.MENTOR RENAME COLUMN "SOURCE_CODE" TO "ASSIGNED_TO";
ALTER TABLE TEST.IMIS_ACTIVITIES.MENTOR RENAME COLUMN "UF_1" TO "ROLE";
ALTER TABLE TEST.IMIS_ACTIVITIES.MENTOR RENAME COLUMN "UF_2" TO "CONFERENCE_CODE";
ALTER TABLE TEST.IMIS_ACTIVITIES.MENTOR RENAME COLUMN "UF_3" TO "USER_ID";



ALTER TABLE TEST.IMIS_ACTIVITIES.RETENTION RENAME COLUMN "BEGIN_DATE" TO "EFFECTIVE_DATE";
ALTER TABLE TEST.IMIS_ACTIVITIES.RETENTION RENAME COLUMN "ASSIGNED_TO" TO "SOURCE_CODE";
ALTER TABLE TEST.IMIS_ACTIVITIES.RETENTION RENAME COLUMN "ROLE" TO "REASON";
ALTER TABLE TEST.IMIS_ACTIVITIES.RETENTION RENAME COLUMN "CONFERENCE_CODE" TO "MEMBER_TYPE_CODE";
ALTER TABLE TEST.IMIS_ACTIVITIES.RETENTION RENAME COLUMN "USER_ID" TO "TRANSFER_TO";



ALTER TABLE TEST.TEST_AREA."SURVIVOR_PATIENT_ADVOCATE" RENAME TO TEST.IMIS_ACTIVITIES."SURVIVOR_PATIENT_ADVOCATE";

ALTER TABLE TEST.IMIS_ACTIVITIES."SURVIVOR_PATIENT_ADVOCATE" RENAME COLUMN "SOURCE_CODE" TO "ASSIGNED_TO";
ALTER TABLE TEST.IMIS_ACTIVITIES."SURVIVOR_PATIENT_ADVOCATE" RENAME COLUMN "UF_1" TO "EVENT_CODE";
ALTER TABLE TEST.IMIS_ACTIVITIES."SURVIVOR_PATIENT_ADVOCATE" RENAME COLUMN "UF_2" TO "ROLE";
ALTER TABLE TEST.IMIS_ACTIVITIES."SURVIVOR_PATIENT_ADVOCATE" RENAME COLUMN "UF_3" TO "STATUS";



ALTER TABLE TEST.IMIS_ACTIVITIES.SPEAKER RENAME COLUMN "EFFECTIVE_DATE" TO "BEGIN_DATE";


ALTER TABLE TEST.IMIS_ACTIVITIES.VOTE RENAME COLUMN "UF_1" TO "IDENTIFIER";


ALTER TABLE TEST.IMIS_ACTIVITIES.WORKSHOP RENAME COLUMN "EFFECTIVE_DATE" TO "WORKSHOP_YEAR";
ALTER TABLE TEST.IMIS_ACTIVITIES.WORKSHOP RENAME COLUMN "SOURCE_CODE" TO "ASSIGNED_TO";
ALTER TABLE TEST.IMIS_ACTIVITIES.WORKSHOP RENAME COLUMN "UF_1" TO "SPECIAL_BENEFIT";
ALTER TABLE TEST.IMIS_ACTIVITIES.WORKSHOP RENAME COLUMN "UF_2" TO "OPTION";



ALTER TABLE TEST.IMIS_ACTIVITIES.WORKSHOPAP RENAME COLUMN "EFFECTIVE_DATE" TO "DATE";
ALTER TABLE TEST.IMIS_ACTIVITIES.WORKSHOPAP RENAME COLUMN "UF_1" TO "STATUS";
ALTER TABLE TEST.IMIS_ACTIVITIES.WORKSHOPAP RENAME COLUMN "DESCRIPTION" TO "WORKSHOP";


CREATE OR REPLACE TABLE TEST.IMIS_ACTIVITIES."SUBSCRIPTIONS" AS
SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'SUBSCRIPTIONS';

SELECT * FROM TEST.IMIS_ACTIVITIES."SUBSCRIPTIONS";



ALTER TABLE TEST.IMIS_ACTIVITIES.AWARD RENAME COLUMN "AWARD_CHECK_SEN" TO "AWARD_CHECK_SENT";

ALTER TABLE TEST.IMIS_ACTIVITIES.DECEASED RENAME COLUMN "DESCRIPTION" TO "NOTES";


ALTER TABLE TEST.IMIS_ACTIVITIES.MAJACC RENAME COLUMN "CATEGORY_CODE" TO "CATEGORY";

ALTER TABLE TEST.IMIS_ACTIVITIES.RETENTION RENAME COLUMN "MEMBER_TYPE_CODE1" TO "MEMBER_TYPE_CODE";

SELECT DISTINCT MEMBER_TYPE FROM TEST.IMIS_ACTIVITIES.RETENTION;


SELECT DISTINCT COUNT(SALES_ORDER_LINE_ID)
FROM PRODUCTION.MART_JOURNAL_SALES.JOURNAL_SALES;

SELECT COUNT(*)
FROM PRODUCTION.MART_JOURNAL_SALES.JOURNAL_SALES;

SELECT DISTINCT COUNT(SALES_ORDER_LINE_ID)
FROM PRODUCTION.MART_JOURNAL_SALES.JOURNAL_SALES
WHERE SALES_ORDER_LINE_ID IS NULL;

SELECT
    SUM(B.SALE_PRICE)
FROM PRODUCTION.MART_JOURNAL_SALES.JOURNAL_SALES AS A
    LEFT JOIN PRODUCTION.REPL_SALESFORCE.SALES_ORDER_LINES AS B;






SELECT * FROM IMISDATA.DBO.ACTIVITY ORDER BY RANDOM() LIMIT 100;

SELECT * FROM PRODUCTION.REPL_SALESFORCE.CONTACTS ORDER BY RANDOM() LIMIT 1000;



--Changing role in IMISDATA to sysadmin
GRANT ALL ON ALL schemas in database IMISDATA TO ROLE sysadmin;
GRANT ALL ON ALL TABLES IN SCHEMA IMISDATA.DBO TO ROLE sysadmin;


/*Pushing to PRODUCTION*/
CREATE OR REPLACE TABLE IMISDATA.DBO."ABSINFRAC"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."ABSINFRAC";

CREATE OR REPLACE TABLE IMISDATA.DBO."ABSTRACT"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."ABSTRACT";

CREATE OR REPLACE TABLE IMISDATA.DBO."AWARD"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."AWARD";

CREATE OR REPLACE TABLE IMISDATA.DBO."COMMITTEE"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."COMMITTEE";

CREATE OR REPLACE TABLE IMISDATA.DBO."CV"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."CV";

CREATE OR REPLACE TABLE IMISDATA.DBO."DECEASED"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."DECEASED";

CREATE OR REPLACE TABLE IMISDATA.DBO."DUES"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."DUES"; --seems to be biggest, 1,131,573 records

CREATE OR REPLACE TABLE IMISDATA.DBO."EVENT"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."EVENT";

CREATE OR REPLACE TABLE IMISDATA.DBO."EVENTPART"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."EVENTPART";

CREATE OR REPLACE TABLE IMISDATA.DBO."EVENTSPONS"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."EVENTSPONS"; --4 rows

CREATE OR REPLACE TABLE IMISDATA.DBO."GRANT"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."GRANT"; --3 rows

CREATE OR REPLACE TABLE IMISDATA.DBO."MAJACC"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."MAJACC";

CREATE OR REPLACE TABLE IMISDATA.DBO."MEETING"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."MEETING";


SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'MEETINGS'; --Empty

CREATE OR REPLACE TABLE IMISDATA.DBO."MEMARCH"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."MEMARCH";

CREATE OR REPLACE TABLE IMISDATA.DBO."MEMBEN"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."MEMBEN";

CREATE OR REPLACE TABLE IMISDATA.DBO."MEMBERMERG"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."MEMBERMERG";

CREATE OR REPLACE TABLE IMISDATA.DBO."MEMNOTES"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."MEMNOTES";

CREATE OR REPLACE TABLE IMISDATA.DBO."MEMSTATCHA"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."MEMSTATCHA";

CREATE OR REPLACE TABLE IMISDATA.DBO."MENTOR"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."MENTOR";


SELECT 
    *
FROM IMISDATA.DBO.ACTIVITY
WHERE ACTIVITY_TYPE = 'RECRUITMENT'; --Empty

CREATE OR REPLACE TABLE IMISDATA.DBO."RETENTION"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."RETENTION"; --Delinquent payments

CREATE OR REPLACE TABLE IMISDATA.DBO."SURVIVOR_PATIENT_ADVOCATE"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."SURVIVOR_PATIENT_ADVOCATE";

CREATE OR REPLACE TABLE IMISDATA.DBO."SPEAKER"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."SPEAKER";


CREATE OR REPLACE TABLE IMISDATA.DBO."VOTE"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."VOTE";

CREATE OR REPLACE TABLE IMISDATA.DBO."WORKSHOP"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."WORKSHOP";

CREATE OR REPLACE TABLE IMISDATA.DBO."WORKSHOPAP"
AS
SELECT 
    *
FROM TEST.IMIS_ACTIVITIES."WORKSHOPAP";






















































