SELECT * FROM TEST.CONTACT_SNAPSHOTS.CS_MEMBERSHIP_MERGE_T LIMIT 1;

SELECT "Initial_Join_Date__c", "Paid_thru_date__c" FROM TEST.CONTACT_SNAPSHOTS.CS_MEMBERSHIP_MERGE_T  WHERE "Id" = '0031I00000WrwhlQAB'
GROUP BY 1,2;

--list if membership status changed

--combine mh datamart combine with kenan's push file and see if they match
--
SELECT 
    *
FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_HISTORY_FINAL AS MH
WHERE MH."SALESFORCE ID" = '0031I00000WrwhlQAB';

SELECT MIN("TERM YEAR") FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_HISTORY_FINAL;


SELECT GET_DDL('table', 'TEST.TEST_AREA.CANCER_TODAY_SUBSCRIBERS');

SELECT * FROM TEST.TEST_AREA.CANCER_TODAY_SUBSCRIBERS;


/*******8

KEY: AACR_ID-YEAR-MEMBER_TYPE

******** */

CREATE OR REPLACE TABLE TEST.MEMBERSHIP_PUSHES.ALL_PUSHES
AS
SELECT *, '2020' AS PUSH_YEAR FROM TEST.MEMBERSHIP_PUSHES.PUSHES_2020
UNION ALL
SELECT *, '2021' AS PUSH_YEAR FROM TEST.MEMBERSHIP_PUSHES.PUSHES_2021
UNION ALL
SELECT *, '2022' AS PUSH_YEAR FROM TEST.MEMBERSHIP_PUSHES.PUSHES_2022
UNION ALL
SELECT *, '2023' AS PUSH_YEAR FROM TEST.MEMBERSHIP_PUSHES.PUSHES_2023
UNION ALL
SELECT *, '2024' AS PUSH_YEAR FROM TEST.MEMBERSHIP_PUSHES.PUSHES_2024
UNION ALL
SELECT *, '2025' AS PUSH_YEAR FROM TEST.MEMBERSHIP_PUSHES.PUSHES_2025;




--join all_pushes ap to mem_history mh on ap.
CREATE OR REPLACE TABLE TEST.TEST_AREA.MEMBERSHIP_PUSH_MERGE
AS
with MEM_HISTORY AS (
    SELECT
        MH.*,
        SUB."OrderApi__Current_Term_Start_Date__c" AS CURRENT_TERM_START_DATE,
        SUB."OrderApi__Current_Term_End_Date__c" AS CURRENT_TERM_END_DATE,
        SUB."OrderApi__Status__c" AS SUBSCRIPTION_STATUS,
        CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_HISTORY_FINAL AS MH
        LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
            ON MH."SALESFORCE ID" = CONC."Id"
        LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__SUBSCRIPTION__C AS SUB
            ON MH."SUBSCRIPTION" = SUB."Id"
)
SELECT
    MMH.*,
    AP.MEMBER_TYPE AS MEM_TYPE_AT_PUSH,
    AP.PUSH_YEAR,
    CASE WHEN AP.AACR_ID IS NOT NULL THEN 1 ELSE 0 END AS PUSH_FLAG,
    CONCAT(AP.AACR_ID, '-', AP.PUSH_YEAR, '-', AP.MEMBER_TYPE) AS PUSH_KEY
FROM MEM_HISTORY AS MMH
    LEFT JOIN TEST.MEMBERSHIP_PUSHES.ALL_PUSHES AS AP
        ON MMH.AACR_ID = AP.AACR_ID
        AND MMH."TERM YEAR" = AP.PUSH_YEAR;








create or replace view TEST.CTI_2025_EXTRACTS.CONTACT_SPEAKER_MERGE
as
with CON AS (
    SELECT
        CONC.*,
        CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
)
SELECT
    CON.AACR_ID,
    S.*
FROM TEST.CTI_2025_EXTRACTS.INVITED_SPEAKERS_CHAIRS AS S
    LEFT JOIN CON
        ON S.PRIMARYAUTHOR_MEMBERNUMBER = CON.AACR_ID
;

GRANT SELECT ON ALL TABLES IN SCHEMA TEST.CTI_2025_EXTRACTS TO ROLE SYSADMIN;

GRANT USAGE ON ALL TABLES IN SCHEMA TEST.CTI_2025_EXTRACTS TO ROLE SYSADMIN;



SELECT * FROM TEST.CTI_2025_EXTRACTS.INVITED_SPEAKERS_CHAIRS;




















SELECT AACR_ID FROM TEST.MEMBERSHIP_PUSHES.PUSHES_2022 ORDER BY RANDOM() LIMIT 5;

/*
'410634',
'345197',
'349913',
'351396',
'376357'
 */

SELECT 
    "TERM ID",
    "TERM YEAR",
    "TERM CREATED DATE",
    "SUBSCRIPTION",
    "SALES ORDER",
    "SALES ORDER LINE",
    "SUBSCRIPTION PLAN",
    "ITEM NAME",
    "Transaction Line ID",
    "Transaction Line C",
    "Transaction Id",
    "Transaction Date", 
    AACR_ID,
    MEM_TYPE_AT_PUSH,
    PUSH_YEAR,
    PUSH_FLAG
FROM TEST.TEST_AREA.MEMBERSHIP_PUSH_MERGE
WHERE AACR_ID IN ('410634', '345197', '349913', '351396', '376357')
ORDER BY AACR_ID, "TERM YEAR";



with MEMS AS (
    SELECT
        MH.*,
        CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_HISTORY_FINAL AS MH
        LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
            ON MH."SALESFORCE ID" = CONC."Id"
)
SELECT
    *
FROM TEST.MEMBERSHIP_PUSHES.ALL_PUSHES AS AP
--WHERE AP.AACR_ID NOT IN (SELECT AACR_ID FROM MEMS)
WHERE CONCAT(AP.AACR_ID, AP.PUSH_YEAR) NOT IN (SELECT CONCAT(AACR_ID, "TERM YEAR") FROM MEMS);



/*
- Refocused on business decisions, asked ‘Which three decisions will this dashboard drive next quarter?’ drove 5 needed key metrics; Defined an MVP; Instituted a change-request template - New Report Request; Enabled self-service filters; Set up scheduled refresh


 */









SELECT "TERM YEAR", COUNT(*) FROM TEST.TEST_AREA.MEMBERSHIP_PUSH_MERGE WHERE "TERM YEAR" BETWEEN 2018 AND 2026 GROUP BY 1 ORDER BY 1;







with MEM_HISTORY AS (
    SELECT
        MH.*,
        CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_HISTORY_FINAL AS MH
        LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
            ON MH."SALESFORCE ID" = CONC."Id"
)
SELECT
    MMH.*,
    AP.MEMBER_TYPE AS MEM_TYPE_AT_PUSH,
    AP.PUSH_YEAR,
    CASE WHEN AP.AACR_ID IS NOT NULL THEN 1 ELSE 0 END AS PUSH_FLAG,
    CONCAT(AP.AACR_ID, '-', AP.PUSH_YEAR, '-', AP.MEMBER_TYPE) AS PUSH_KEY
FROM MEM_HISTORY AS MMH
    FULL OUTER JOIN TEST.MEMBERSHIP_PUSHES.ALL_PUSHES AS AP
        ON MMH.AACR_ID = AP.AACR_ID
        AND MMH."TERM YEAR" = AP.PUSH_YEAR
WHERE MMH."ITEM NAME" <> 'Emeritus Membership';

SELECT COUNT(*) FROM TEST.TEST_AREA.MEMBERSHIP_PUSH_MERGE WHERE "ITEM NAME" <> 'Emeritus Membership';