SELECT * FROM  LEAD_LISTS_DB.RESULTS_TABLE.RESULTS;


--find all distinct first, delete all golden record ids that are not lowest distinct 

with dupes AS (
    SELECT 
        *,
        LOWER(CONCAT(FIRST_NAME, LAST_NAME, EMAIL)) AS IDRK --LOWER 
    FROM LEAD_LISTS_DB.RESULTS_TABLE.RESULTS
)
SELECT 
    IDRK,
    COUNT(DISTINCT GOLDEN_RECORD_ID) --do distinct
FROM dupes
GROUP BY 1
HAVING COUNT(DISTINCT GOLDEN_RECORD_ID) > 1
ORDER BY 2 DESC;

--keep only lowest golden record id; other golden record ids DELETE FROM EVERYWHERE (lead results, idr tables person email)

SELECT 
    GOLDEN_RECORD_ID,
    LOWER(CONCAT(FIRST_NAME, LAST_NAME, EMAIL)) AS IDRK
FROM LEAD_LISTS_DB.RESULTS_TABLE.RESULTS
GROUP BY 2, 1
ORDER BY 2, 1;

--callumoddycallum.oddy.22@ucl.ac.uk
SELECT
    GOLDEN_RECORD_ID,
    LOWER(CONCAT(FIRST_NAME, LAST_NAME, EMAIL)) AS IDRK
FROM LEAD_LISTS_DB.RESULTS_TABLE.RESULTS
WHERE LOWER(CONCAT(FIRST_NAME, LAST_NAME, EMAIL)) = 'callumoddycallum.oddy.22@ucl.ac.uk'
ORDER BY GOLDEN_RECORD_ID;

--masumisuzuisuzui@med.nagoya-cu.ac.jp DISTINCTS 

--Below is list of distinct GRID and IDRK 
SELECT
    GOLDEN_RECORD_ID,
    LOWER(CONCAT(FIRST_NAME, LAST_NAME, EMAIL)) AS IDRK
FROM LEAD_LISTS_DB.RESULTS_TABLE.RESULTS
WHERE LOWER(CONCAT(FIRST_NAME, LAST_NAME, EMAIL)) = 'masumisuzuisuzui@med.nagoya-cu.ac.jp'
GROUP BY 1, 2
ORDER BY 1; --target grid is 1022790

--another check charleswisemancw@briacell.com
SELECT
    GOLDEN_RECORD_ID,
    LOWER(CONCAT(FIRST_NAME, LAST_NAME, EMAIL)) AS IDRK
FROM LEAD_LISTS_DB.RESULTS_TABLE.RESULTS
WHERE LOWER(CONCAT(FIRST_NAME, LAST_NAME, EMAIL)) = 'charleswisemancw@briacell.com'
GROUP BY 1, 2
ORDER BY 1; --target grid is 1025079




/****************************************************************

PROD RUN

****************************************************************/

--1. Create backup of current lead list table 
CREATE SCHEMA LEAD_LISTS_DB.BACKUPS;

GRANT ALL ON SCHEMA LEAD_LISTS_DB.BACKUPS TO ROLE SYSADMIN;

CREATE TABLE IF NOT EXISTS LEAD_LISTS_DB.BACKUPS.RESULTS_BACKUP
AS 
SELECT * FROM LEAD_LISTS_DB.RESULTS_TABLE.RESULTS;

SELECT * FROM LEAD_LISTS_DB.BACKUPS.RESULTS_BACKUP; --confirm


--test version
CREATE OR REPLACE TABLE TEST.TEST_AREA.RESULTS_BACKUP
AS 
SELECT * FROM LEAD_LISTS_DB.RESULTS_TABLE.RESULTS;



--2. Dedupe whole lead list results table on f/l/e & Split table into min GRID and non-min GRID

--min-GRID (deduped)
CREATE OR REPLACE TABLE LEAD_LISTS_DB.BACKUPS.RESULTS_DEDUPED
AS
with dupes AS (
    SELECT 
        *,
        LOWER(CONCAT(FIRST_NAME, LAST_NAME, EMAIL)) AS IDRK --LOWER 
    FROM LEAD_LISTS_DB.BACKUPS.RESULTS_BACKUP --pull from backup table, original with all the dupes
),
nums AS (
    --partition by GRID
    SELECT 
        *,
        ROW_NUMBER() OVER (PARTITION BY GOLDEN_RECORD_ID ORDER BY IDRK) AS rnum
    FROM dupes
),
unq_grids AS ( --unique GRIDs, dupes here are on IDR key
    SELECT
        *
    FROM nums
    WHERE rnum = 1
),
unq_final AS (
    SELECT 
        *,
        ROW_NUMBER() OVER (PARTITION BY IDRK ORDER BY GOLDEN_RECORD_ID) AS FINAL_ROW
    FROM unq_grids
)
SELECT
    *
FROM unq_final
WHERE FINAL_ROW = 1
;

SELECT * FROM LEAD_LISTS_DB.BACKUPS.RESULTS_DEDUPED;


--non-min GRID (to delete)
CREATE TABLE IF NOT EXISTS LEAD_LISTS_DB.BACKUPS.RESULTS_TO_DELETE
AS 
SELECT * FROM LEAD_LISTS_DB.BACKUPS.RESULTS_BACKUP WHERE GOLDEN_RECORD_ID NOT IN (SELECT GOLDEN_RECORD_ID FROM LEAD_LISTS_DB.BACKUPS.RESULTS_DEDUPED);

SELECT * FROM LEAD_LISTS_DB.BACKUPS.RESULTS_TO_DELETE;


--3. Update lead list table with min-GRID records from step 4 (overwrite leads table with results_deduped, DO NOT delete from)
--empty lead list table & overwrite with deduped table

SELECT * FROM LEAD_LISTS_DB.RESULTS_TABLE.RESULTS;

TRUNCATE TABLE LEAD_LISTS_DB.RESULTS_TABLE.RESULTS;

INSERT INTO LEAD_LISTS_DB.RESULTS_TABLE.RESULTS (
    GOLDEN_RECORD_ID,
	AACR_ID,
	FIRST_NAME,
	LAST_NAME,
	GENDER,
	RACE,
	EMAIL,
	COMPANY_NAME,
	STREET,
	STREET_2,
	CITY,
	STATE_PROVINCE,
	COUNTRY,
	ZIP,
	MOBILE_NUMBER,
	CONSENT_DECLARATION,
	SOURCE_NAME,
	DATE_COLLECTED,
	LEAD_USE,
	LEAD_DESCRIPTION,
	TICKET_NUMBER,
	SUBMITTER_NAME,
	DEPARTMENT,
	DOUBLE_OPT_IN
)
SELECT 
    GOLDEN_RECORD_ID,
	AACR_ID,
	FIRST_NAME,
	LAST_NAME,
	GENDER,
	RACE,
	EMAIL,
	COMPANY_NAME,
	STREET,
	STREET_2,
	CITY,
	STATE_PROVINCE,
	COUNTRY,
	ZIP,
	MOBILE_NUMBER,
	CONSENT_DECLARATION,
	SOURCE_NAME,
	DATE_COLLECTED,
	LEAD_USE,
	LEAD_DESCRIPTION,
	TICKET_NUMBER,
	SUBMITTER_NAME,
	DEPARTMENT,
	DOUBLE_OPT_IN
FROM LEAD_LISTS_DB.BACKUPS.RESULTS_DEDUPED;




--4. Delete non-min GRIDs from everywhere

--create extra person and email backups in test to be totally safe, not critical after first run
SELECT * FROM LEAD_LISTS_DB.BACKUPS.RESULTS_TO_DELETE;

CREATE OR REPLACE TABLE TEST.TEST_AREA.IDR_EMAIL_BACKUP
AS 
SELECT * FROM IDR.RESULTS.EMAIL;

CREATE OR REPLACE TABLE TEST.TEST_AREA.IDR_PERSON_BACKUP
AS 
SELECT * FROM IDR.RESULTS.PERSON;

SELECT * FROM TEST.TEST_AREA.IDR_EMAIL_BACKUP;
SELECT * FROM TEST.TEST_AREA.IDR_PERSON_BACKUP;



--person table
DELETE FROM IDR.RESULTS.PERSON A 
WHERE A."Id" IN (SELECT DISTINCT GOLDEN_RECORD_ID FROM LEAD_LISTS_DB.BACKUPS.RESULTS_TO_DELETE);
SELECT * FROM IDR.RESULTS.PERSON;

--email table
DELETE FROM IDR.RESULTS.EMAIL A 
WHERE A."PersonId" IN (SELECT DISTINCT GOLDEN_RECORD_ID FROM LEAD_LISTS_DB.BACKUPS.RESULTS_TO_DELETE);
SELECT * FROM IDR.RESULTS.EMAIL;


SELECT * FROM IDR.RESULTS.UNIQUEID;







--Final deduped list, overwrite current lead list table with this
CREATE TABLE IF NOT EXISTS TEST.TEST_AREA.RESULTS_DEDUPED
AS
with dupes AS (
    SELECT 
        *,
        LOWER(CONCAT(FIRST_NAME, LAST_NAME, EMAIL)) AS IDRK --LOWER 
    FROM LEAD_LISTS_DB.RESULTS_TABLE.RESULTS
),
nums AS (
    --partition by GRID
    SELECT 
        *,
        ROW_NUMBER() OVER (PARTITION BY GOLDEN_RECORD_ID ORDER BY IDRK) AS rnum
    FROM dupes
),
unq_grids AS ( --unique GRIDs, dupes here are on IDR key
    SELECT
        *
    FROM nums
    WHERE rnum = 1
),
unq_final AS (
    SELECT 
        *,
        ROW_NUMBER() OVER (PARTITION BY IDRK ORDER BY GOLDEN_RECORD_ID) AS FINAL_ROW
    FROM unq_grids
)
SELECT
    *
FROM unq_final
WHERE FINAL_ROW = 1
;
