--CREATE OR REPLACE TABLE TEST.TEST_AREA.MEMBERSHIP_PUSH_MERGE
--AS
with MEM_HISTORY AS (
    SELECT
        MH.*,
        TERM."OrderApi__Term_Start_Date__c" AS TERM_START_DATE,
        TERM."OrderApi__Term_End_Date__c" AS TERM_END_DATE,
        TERM."OrderApi__Renewed_Date__c" AS TERM_RENEWED_DATE,
        TERM."OrderApi__Grace_Period_End_Date__c" AS TERM_GRACE_PERIOD_END_DATE,
        SUB."OrderApi__Status__c" AS SUBSCRIPTION_STATUS,
        SUB."OrderApi__Item__c" AS ITEM_ID,
        SUB."OrderApi__Item_Class__c" AS ITEM_CLASS_ID,
        CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_HISTORY_FINAL AS MH
        LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
            ON MH."SALESFORCE ID" = CONC."Id"
        LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__SUBSCRIPTION__C AS SUB
            ON MH."SUBSCRIPTION" = SUB."Id"
        LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__RENEWAL__C AS TERM
            ON MH."TERM ID" = TERM."Id"
)
SELECT
    MMH.*,
    AP.MEMBER_TYPE AS MEM_TYPE_AT_PUSH,
    AP.PUSH_YEAR,
    CASE WHEN AP.AACR_ID IS NOT NULL THEN 1 ELSE 0 END AS PUSH_FLAG,
    CONCAT(AP.AACR_ID, '-', AP.PUSH_YEAR, '-', AP.MEMBER_TYPE) AS PUSH_KEY
FROM MEM_HISTORY AS MMH
    LEFT JOIN TEST.MEMBERSHIP_PUSHES.ALL_PUSHES AS AP
        ON MMH.AACR_ID = AP.AACR_ID
        AND MMH."TERM YEAR" = AP.PUSH_YEAR;


SELECT * FROM TEST.TEST_AREA.MEMBERSHIP_PUSH_MERGE;

SELECT * FROM TEST.MART_MEMBERSHIP_HISTORY.DEMOS_BACKUP;

SELECT * FROM TEST.MART_MEMBERSHIP_HISTORY.TRANSACTION_LINE_MERGE_BACKUP WHERE "Transaction Id" IN (
SELECT "Transaction Id" FROM TEST.MART_MEMBERSHIP_HISTORY.TRANSACTION_LINE_MERGE_BACKUP GROUP BY "Transaction Id" HAVING COUNT("Transaction Line ID") > 1);



SELECT * FROM TEST.TEST_AREA.MEMBERSHIP_PUSH_MERGE WHERE "SALESFORCE ID" = '0031I00000hm1HxQAI';


SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__SUBSCRIPTION__C WHERE "Id" = 'a1O1I0000024q18UAA';

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__SUBSCRIPTION_LINE__C  AS SL WHERE SL."OrderApi__Subscription__c" = 'a1O1I0000024q18UAA';



SELECT *
FROM TEST.TEST_AREA.MEMBERSHIP_PUSH_MERGE
WHERE "SALESFORCE ID" = '0031I00000WsqAxQAJ';



SELECT COUNT(*) FROM TEST.MART_MEMBERSHIP_HISTORY.TRANSACTION_LINE_MERGE_BACKUP;




with Lines AS (
    SELECT *
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION_LINE__C AS TL
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__ITEM_CLASS__C AS IC
    ON TL."OrderApi__Item_Class__c" = IC."Id"
    --LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__RECEIPT__C AS RC
    --ON TL."OrderApi__Receipt__c" = RC."Id"
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__ITEM__C AS Itemn
    ON TL."OrderApi__Item__c" = Itemn."Id"
    WHERE IC."Name" IN ('Individual Memberships', 'Internal Staff Use Only')
    --LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__SALES_ORDER__C AS SO
    --ON RC."OrderApi__Sales_Order__c" = SO."Id"
)
SELECT
    TR.*
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION__C AS TR
--LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__GL_ACCOUNT__C AS GL
--    ON TL."OrderApi__GL_Account__c" = GL."Id"
LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON
    ON TR."OrderApi__Contact__c" = CON."Id"
LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
    ON CON."AccountId" = ACC."Id"
/*LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__ITEM__C AS Itemn
    ON TL."OrderApi__Item__c" = Itemn."Id"
LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__SOURCE_CODE__C AS SC
    ON SO."OrderApi__Source_Code__c" = SC."Id"*/
WHERE TR."Id" IN (SELECT DISTINCT "OrderApi__Transaction__c" FROM Lines)
AND ACC."Name" NOT LIKE '%AACR TEST%'
ORDER BY TR."Id";
--where any transaction line in the transaction 












SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION_LINE__C;

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION__C;
--has reciept and sales order and source code





SELECT COUNT(*), "REGISTRATION_CATEGORY" FROM PRODUCTION.REPL_CSI.CSI_REGISTRATIONS GROUP BY 2;
--2 lines in snowflake if cnacelled reg
--ask craig for extract from csi
--



SELECT TR. FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION__C AS TR;

SELECT TL.c FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION_LINE__C AS TL;

SELECT RC.credi FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__RECEIPT__C AS RC;

SELECT COUNT(*) FROM TEST.TEST_AREA.MEMBERSHIP_PUSH_MERGE;

SELECT COUNT(*) FROM TEST.MART_MEMBERSHIP_HISTORY.TRANSACTION_LINE_MERGE_BACKUP;

SELECT COUNT(*) FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.TRANSACTION_LINE_MERGE_BACKUP;





SELECT TL FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION__C AS TL;

/*
Total:
CASE
    WHEN SOL."OrderApi__Sale_Price__c" IS NOT NULL AND SOL."OrderApi__Quantity__c" IS NOT NULL THEN SOL."OrderApi__Sale_Price__c"*SOL."OrderApi__Quantity__c"
    ELSE SOL."OrderApi__Total__c"
END AS SUBTOTAL,
 */