/*

Account

 */

SELECT 
    COUNT(*), 
    SUM(CASE WHEN "Family_Member_with_Cancer__c" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN "Family_Member_with_Cancer__c" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN "Family_Member_with_Cancer__c" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN "Family_Member_with_Cancer__c" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT;

SELECT 
    COUNT(*), 
    SUM(CASE WHEN A."Family_Member_with_Cancer__c" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN A."Family_Member_with_Cancer__c" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN A."Family_Member_with_Cancer__c" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN A."Family_Member_with_Cancer__c" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT A;

----

SELECT 
    COUNT(*), 
    SUM(CASE WHEN A."BillingCity" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN A."BillingCity" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN A."BillingCity" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN A."BillingCity" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS A;


SELECT 
    COUNT(*), 
    SUM(CASE WHEN B."BillingCity" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN B."BillingCity" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN B."BillingCity" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN B."BillingCity" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT B;

----

SELECT 
    COUNT(*), 
    SUM(CASE WHEN A."BillingCountry" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN A."BillingCountry" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN A."BillingCountry" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN A."BillingCountry" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT A;

SELECT 
    COUNT(*), 
    SUM(CASE WHEN B."BillingCountry" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN B."BillingCountry" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN B."BillingCountry" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN B."BillingCountry" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT B;

SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT WHERE "RecordTypeId" = '012Vq000000sGUQIA2' ORDER BY RANDOM();

----

SELECT 
    COUNT(*), 
    SUM(CASE WHEN A."BillingPostalCode" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN A."BillingPostalCode" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN A."BillingPostalCode" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN A."BillingPostalCode" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT A;

SELECT 
    COUNT(*), 
    SUM(CASE WHEN B."BillingPostalCode" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN B."BillingPostalCode" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN B."BillingPostalCode" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN B."BillingPostalCode" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT B;

----

SELECT 
    COUNT(*), 
    SUM(CASE WHEN A."BillingState" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN A."BillingState" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN A."BillingState" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN A."BillingState" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT A;

SELECT 
    COUNT(*), 
    SUM(CASE WHEN B."BillingPostalCode" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN B."BillingPostalCode" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN B."BillingPostalCode" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN B."BillingPostalCode" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT B;


SELECT 
    A."Id",
    C."Id",
    ACC."BillingCity",
    C."BillingCity"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."BillingCity" <>  C."BillingCity";

SELECT 
    A."Id",
    C."Id",
    ACC."BillingPostalCode",
    C."BillingPostalCode"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."BillingPostalCode" <>  C."BillingPostalCode";

SELECT 
    A."Id",
    C."Id",
    ACC."Description",
    C."Description"
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.FONTEVA_CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."Description" <>  C."Description";

/*Account ID*/
SELECT
    A."Id" AS OWNBACKUP_CONTACT_ID,
    B.*,
    ACC."Id" AS OWNBACKUP_ACCOUNT_ID,
    C."Fonteva_Account_ID__c"
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.FONTEVA_CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.FONTEVA_ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."Id" <>  C."Fonteva_Account_ID__c";







/*Account Name */
SELECT 
    A."Id",
    C."Id",
    ACC."Name",
    C."Name"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."Name" <>  C."Name";

/*Phone*/
SELECT 
    A."Id",
    C."Id",
    ACC."Phone",
    C."Phone"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."Phone" <>  C."Phone";

/*Shipping City*/
SELECT 
    A."Id",
    C."Id",
    ACC."ShippingCity",
    C."ShippingCity"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."ShippingCity" <>  C."ShippingCity";

/*Shipping Country*/
SELECT 
    A."Id",
    C."Id",
    ACC."ShippingCountry",
    C."ShippingCountry"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."ShippingCountry" <>  C."ShippingCountry";

/*Shipping Postal */
SELECT 
    A."Id",
    C."Id",
    ACC."ShippingPostalCode",
    C."ShippingPostalCode"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."ShippingPostalCode" <>  C."ShippingPostalCode";

/*Shipping State*/
SELECT 
    A."Id",
    C."Id",
    ACC."ShippingState",
    C."ShippingState"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."ShippingState" <>  C."ShippingState";

/*Shipping Street*/
SELECT 
    A."Id",
    C."Id",
    ACC."ShippingStreet",
    C."ShippingStreet"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."ShippingStreet" <>  C."ShippingStreet";

/*Website*/
SELECT 
    A."Id",
    C."Id",
    ACC."Website",
    C."Website"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."Website" <>  C."Website";

/*Institution Type*/
SELECT 
    A."Id",
    C."Id",
    ACC."Institution_Type__c",
    C."Type"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."Institution_Type__c" <>  C."Type";

/*Account Email*/
SELECT 
    A."Id",
    C."Id",
    ACC."OrderApi__Account_Email__c",
    C."Account_Email__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."OrderApi__Account_Email__c" <>  C."Account_Email__c";

/*Minority Institution*/
SELECT 
    A."Id",
    C."Id",
    ACC."Minority_Institution__c",
    C."Minority_Serving_Institution_Type__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = Acc."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id"
WHERE ACC."Minority_Institution__c" <>  C."Minority_Serving_Institution_Type__c";

/*MSI*/
SELECT 
    A."Id",
    C."Id",
    ACC."Id",
    C."Company__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.CONTACT_ID_FONTEVA
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON A."AccountId" = ACC."Id"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_IND_ID_FULL = C."Id";

/*Rionggold id*/
SELECT 
    ACC."Ringgold_ID__c",
    C."Ringgold_ID__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON ACC."Id" = B.ACCOUNT_ID_FONTEVA
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT AS C
        ON B.ACCOUNT_ORG_ID_FULL = C."Id"
WHERE ACC."Ringgold_ID__c" <> C."Ringgold_ID__c"
;


/*

Account Contact Relationship

 */
SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE5__AFFILIATION__C;
SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNTCONTACTRELATION;

SELECT 
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE5__AFFILIATION__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNTCONTACTRELATION B
        ON A."Id" = B."Legacy_Id__c";

/*Contact*/
SELECT 
    COUNT(*), 
    SUM(CASE WHEN A."npe5__Contact__c" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN A."npe5__Contact__c" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN A."npe5__Contact__c" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN A."npe5__Contact__c" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE5__AFFILIATION__C A;

SELECT 
    COUNT(*), 
    SUM(CASE WHEN A."ContactId" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN A."ContactId" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN A."ContactId" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN A."ContactId" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNTCONTACTRELATION A;

/*Description*/
SELECT 
    A."npe5__Description__c",
    B."Description__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE5__AFFILIATION__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNTCONTACTRELATION B
        ON A."Id" = B."Legacy_Id__c"
WHERE A."npe5__Description__c" <> B."Description__c";

/*End Date*/
SELECT 
    A."npe5__EndDate__c",
    B."EndDate"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE5__AFFILIATION__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNTCONTACTRELATION B
        ON A."Id" = B."Legacy_Id__c"
WHERE A."npe5__EndDate__c" <> B."EndDate";

/*Org*/
SELECT 
    COUNT(*), 
    SUM(CASE WHEN A."npe5__Organization__c" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN A."npe5__Organization__c" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN A."npe5__Organization__c" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN A."npe5__Organization__c" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE5__AFFILIATION__C A;

SELECT 
    COUNT(*), 
    SUM(CASE WHEN A."AccountId" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN A."AccountId" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN A."AccountId" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN A."AccountId" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNTCONTACTRELATION A;

/*Primary*/
SELECT 
    A."npe5__Primary__c",
    B."IsPrimaryMember"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE5__AFFILIATION__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNTCONTACTRELATION B
        ON A."Id" = B."Legacy_Id__c"
WHERE A."npe5__Primary__c" <> B."IsPrimaryMember";

/*Primary*/
SELECT 
    A."npe5__Primary__c",
    B."IsPrimaryMember"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE5__AFFILIATION__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNTCONTACTRELATION B
        ON A."Id" = B."Legacy_Id__c"
WHERE A."npe5__Primary__c" <> B."IsPrimaryMember";

/*Relationship Type*/
SELECT 
    A."Relationships_to_Disclose__c",
    B."Relationships_To_Disclose__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE5__AFFILIATION__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNTCONTACTRELATION B
        ON A."Id" = B."Legacy_Id__c"
WHERE A."Relationships_to_Disclose__c" <> B."Relationships_To_Disclose__c";

/*Start Date*/
SELECT 
    A."npe5__StartDate__c",
    B."StartDate"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE5__AFFILIATION__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNTCONTACTRELATION B
        ON A."Id" = B."Legacy_Id__c"
WHERE A."npe5__StartDate__c" <> B."StartDate";

/*Status*/
SELECT 
    A."npe5__Status__c",
    B."IsActive"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE5__AFFILIATION__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNTCONTACTRELATION B
        ON A."Id" = B."Legacy_Id__c"
WHERE A."npe5__Status__c" <> B."IsActive";

/*

Gift Commitment

 */

SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION_COMMITMENT A;

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE01__OPPPAYMENT__C;


SELECT
    B."EffectiveStartDate",
    C."npe01__Scheduled_Date__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION_COMMITMENT B
        ON A."Id" = B."Legacy_Opportunity_Id__c"
    JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE01__OPPPAYMENT__C C
        ON A."Id" = C."npe01__Opportunity__c"
;

SELECT 
    * 
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_OPPORTUNITY A
    JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY B
        ON A."Legacy_Id__c" = B."Id"
;


/*

Gift Refunds

 */

SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_REFUNDS;

SELECT R."OrderApi__Type__c",* FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__RECEIPT__C R WHERE R."OrderApi__Type__c" = 'Refund';

/*Date*/
SELECT 
    A."OrderApi__Date__c",
    B."Date"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__RECEIPT__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_REFUNDS B
        ON A."OrderApi__Sales_Order__c" = B."Legacy_Sales_Order_Id__c"
WHERE A."OrderApi__Date__c" <> B."Date";

SELECT 
    A."OrderApi__Date__c",
    B."Date"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__RECEIPT__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_REFUNDS B
        ON A."Id" = B."Legacy_Receipt_Id__c"
WHERE A."OrderApi__Date__c" <> B."Date";

/*Total*/
SELECT 
    A."Id",
    B."Legacy_Receipt_Id__c",
    A."OrderApi__Total__c",
    B."Amount"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__RECEIPT__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_REFUNDS B
        ON A."Id" = B."Legacy_Receipt_Id__c"
WHERE A."OrderApi__Total__c" <> B."Amount";


/*Completed*/
SELECT 
    B.*
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__RECEIPT__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_REFUNDS B
        ON A."Id" = B."Legacy_Receipt_Id__c";


/*

Gift Soft Credit

 */

SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.FONTEVA_PARTIAL_SOFT_CREDIT;
SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_SOFT_CREDIT;

/*Opportunity id*/
SELECT 
    *
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.FONTEVA_PARTIAL_SOFT_CREDIT A 
WHERE A."npsp__Opportunity__c" NOT IN (SELECT B."Legacy_Opportunity_Id__c" FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_SOFT_CREDIT B);

/*contact id*/
SELECT 
    *
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.FONTEVA_PARTIAL_SOFT_CREDIT A 
WHERE A."npsp__Contact__c" NOT IN (SELECT B."RecipientId_Match" FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_SOFT_CREDIT B);

/*Amount*/
SELECT 
    * 
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.FONTEVA_PARTIAL_SOFT_CREDIT A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_SOFT_CREDIT B
        ON A."Id" = B."Legacy_Soft_Credit_Id__c"
WHERE A."npsp__Amount__c" <> B."SoftCreditAmount";


SELECT 
    COUNT(DISTINCT B."Legacy_Contact_Id__c"),
    COUNT(DISTINCT A."npsp__Contact__c")
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.FONTEVA_PARTIAL_SOFT_CREDIT A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_SOFT_CREDIT B
        ON A."npsp__Contact__c" = B."Legacy_Contact_Id__c";

/*

Gift Transaction

 */
SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__INVOICE__C;

SELECT A FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION_LINE__C AS A;

SELECT A FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION A;

/*Due Date*/
SELECT
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__SALES_ORDER__C AS SO
    JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__INVOICE__C AS INV
        ON SO."Id" = INV."OrderApi__Sales_Order__c"
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION AS GT
        ON SO."Id" = GT."Legacy_Sales_Order_ID__c"
WHERE INV."OrderApi__Due_Date__c" <> GT.TRANSACTIONDUEDATE;

/*Reference Number*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__RECEIPT__C AS RC
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION AS GT
        ON RC."Id" = GT."Legacy_Receipt_ID__c"
WHERE RC."OrderApi__Reference_Number__c" <> GT.PAYMENTIDENTIFIER;

/*Gateway trans id*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__RECEIPT__C AS RC
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION AS GT
        ON RC."Id" = GT."Legacy_Receipt_ID__c"
WHERE RC."OrderApi__Gateway_Transaction_Id__c" <> GT.GATEWAYREFERENCE;


/*Description*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."Description" <> B.DESCRIPTION;


SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C;
        

SELECT DISTINCT B."PaymentMethod" FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B;


/*Acknowledgement status*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."npsp__Acknowledgment_Status__c" <> B.ACKNOWLEDGEMENTSTATUS;

/*Tribute type*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."npsp__Tribute_Type__c" <> B.DONORDRIVE_HONOR_OR_MEMORY__C;

/*GL Account*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."GL_Account__c" <> B.DISTRIBUTION_CODE__C;

/*Donation Receipt*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."ddrive__Donation_Receipt_ID__c" <> B.LEGACY_DD_RECEIPT_ID__C;

/*Honoree name*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."npsp__Honoree_Name__c" <> B.DONORDRIVE_HONOR_NAME__C;

/*in kind desc*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."npsp__In_Kind_Description__c" <> B.IN_KIND_DESCRIPTION__C;

/*check number*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."c4g_Check_Number__c" <> B.CHECK_NUMBER__C;

/*donor drive trans id*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."ddrive__Donation_Transaction_ID__c" <> B.LEGACY_DONORDRIVE_TRANSACTION_ID__C;

/*Appeal code*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."c4g_Appeal_Code__c" <> B.LEGACY_APPEAL_CODE__C;

/*notification recipient name*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."npsp__Notification_Recipient_Name__c" <> B.DONORDRIVE_TRIBUTE_RECIPIENT_NAME__C;

/*matching employer*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."npsp__Matching_Gift_Employer__c" <> B.DONORDRIVE_MATCHING_EMPLOYER__C;

/*in kind type*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."npsp__In_Kind_Type__c" <> B.IN_KIND_TYPE__C;

/*recurring profile*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."ddrive__DonorDrive_Recurring_Profile_ID__c" <> B.DD_RECURRING_PROFILE_ID__C;

/*Acknowledgment_Date*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."npsp__Acknowledgment_Date__c" <> B.ACKNOWLEDGEMENTDATE;

/*ticket type*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."ddrive__Ticket_Type__c" <> B.DONORDRIVE_TICKET_TYPE__C;

/*notification message*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."npsp__Notification_Message__c" <> B.DONATION_MESSAGE__C;

/*notification message*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B."Legacy_Transaction_ID__c"
WHERE A."OrderApi__Date__c" <> B.TRANSACTIONDATE;

/*gift type*/
SELECT  
    A."OrderApi__Entity__c",
    B."GiftType"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B."Legacy_Transaction_ID__c"
WHERE A."OrderApi__Entity__c" <> B."GiftType";



SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION_OPPORTUNITY;


/*original amount*/
SELECT  
    A."OrderApi__Is_Posted__c",
    B."Status"
FROM TEST.MEMBERSHIP_MIGRATION_TABLES.MEMBERSHIP_TRANSACTIONS A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Transaction Id" = B."Legacy_Transaction_ID__c"
WHERE A."OrderApi__Is_Posted__c" <> B."Status";


/*Donor*/
SELECT 
    COUNT(*), 
    SUM(CASE WHEN A."DonorId" IS NOT NULL THEN 1 ELSE 0 END) AS NON_NULL_COUNT,
    SUM(CASE WHEN A."DonorId" IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT,
    SUM(CASE WHEN A."DonorId" IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS populated_pct,
    SUM(CASE WHEN A."DonorId" IS NULL THEN 1 ELSE 0 END)/COUNT(*)*1.0 AS null_pct
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION A;

/*RecordType*/
SELECT A."RecordTypeID", COUNT(*) FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION A GROUP BY 1;

/*Revenue Line*/
SELECT A."Revenue_Line__c", COUNT(*) FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION A GROUP BY 1;

/*Name*/
SELECT A."Name" FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION A;

/*GP Batch*/
SELECT  
    A."GP_Batch_Number__c",
    B."GP_Batch_ID__c"
FROM TEST.MEMBERSHIP_MIGRATION_TABLES.MEMBERSHIP_TRANSACTIONS A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Transaction Id" = B."Legacy_Transaction_ID__c"
WHERE A."GP_Batch_Number__c" <> B."GP_Batch_ID__c";

/*GP Batch*/
SELECT  
    A.SALES_ORDER_STATUS,
    B."IsPaid"
FROM TEST.MEMBERSHIP_MIGRATION_TABLES.MEMBERSHIP_TRANSACTIONS A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Transaction Id" = B."Legacy_Transaction_ID__c"
WHERE A."GP_Batch_Number__c" <> B."GP_Batch_ID__c";

/*Payment method*/
SELECT  
    A.RECEIPT_PAYMENT_TYPE,
    B."PaymentMethod"
FROM TEST.MEMBERSHIP_MIGRATION_TABLES.MEMBERSHIP_TRANSACTIONS A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Transaction Id" = B."Legacy_Transaction_ID__c"
WHERE A."RECEIPT_PAYMENT_TYPE" <> B."PaymentMethod";

/*Payment method*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."ddrive__DD_Original_Processing_Fee_Amount__c" <> B.PROCESSORTRANSACTIONFEE;

/*Payment method*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."ddrive__Donation_Receipt_Date__c" <> B.TAX_RECEIPT_DATE__C;

/*Contact Id*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK CW
        ON A."npe01__Contact_Id_for_Role__c" = CW.CONTACT_ID_FONTEVA
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."npe01__Contact_Id_for_Role__c" = B.LEGACY_OPPORTUNITY_CONTACT__C;

/*Sales order id*/
SELECT B."Legacy_Sales_Order_ID__c" FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B WHERE B."Legacy_Sales_Order_ID__c" IS NOT NULL;

/*Total credits*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B."Legacy_Transaction_ID__c"
WHERE A. <> B.TRANSACTIONDATE;
SELECT B.TOTAL_ITEM_AMOUNT__C FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B WHERE B.TOTAL_ITEM_AMOUNT__C IS NOT NULL;

/*Fair market value*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."npsp__Fair_Market_Value__c" <> B.FAIR_MARKET_VALUE__C;

/*Payment method */
SELECT B."PaymentMethod", COUNT(*) FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B GROUP BY 1;

/*campaign id*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."CampaignId" <> B.CAMPAIGNID;

/*close date*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."CloseDate" <> B."TransactionDate";


/*original amount */
SELECT B."OriginalAmount" FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B WHERE B."OriginalAmount" IS NOT NULL;

/*tax deduction*/
SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."ddrive__Sum_Tax_Deduction__c" <> B.TAXDEDUCTIONAMOUNT;

SELECT B.TAXDEDUCTIONAMOUNT FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B WHERE B.TAXDEDUCTIONAMOUNT IS NOT NULL;


/*

Membership

 */
SELECT COUNT(*) FROM TEST.MEMBERSHIP_MIGRATION_TABLES.MEMBERSHIP_PUSH_MERGE;
SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_MEMBERSHIP AS M;

SELECT M."Status__c", COUNT(*) FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_MEMBERSHIP AS M GROUP BY 1;

SELECT M."Membership_Product__c", COUNT(*) FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_MEMBERSHIP AS M GROUP BY 1;

SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_MEMBERSHIP AS M WHERE M."End_Date__c" IS NULL;

SELECT M."Previous_Membership__c", COUNT(*) FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_MEMBERSHIP AS M GROUP BY 1;


SELECT 
    COUNT(*)
FROM TEST.MEMBERSHIP_MIGRATION_TABLES.MEMBERSHIP_PUSH_MERGE A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK B
        ON A."SALESFORCE ID" = B.CONTACT_ID_FONTEVA
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_MEMBERSHIP C
        ON C."Account__c" = B.ACCOUNT_IND_ID_FULL
;

SELECT M."Membership_Type__c", COUNT(*) FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_MEMBERSHIP AS M GROUP BY 1;

/*

Transaction lines

 */

SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B;

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION_LINE__C A;

SELECT
    A."OrderApi__Sales_Order_Line__c",
    B."Sales_Order_Line_Legacy_Id__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION_LINE__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B
        ON A."Id" = B."Legacy_Transaction_Line_Item_Id__c"
WHERE A."OrderApi__Sales_Order_Line__c" IS NOT NULL
;

SELECT B."Sales_Order_Line_Legacy_Id__c", COUNT(*) FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B WHERE B."Sales_Order_Line_Legacy_Id__c" GROUP BY 1;

SELECT
    A."OrderApi__Memo__c",
    B."Description__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION_LINE__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B
        ON A."Id" = B."Legacy_Transaction_Line_Item_Id__c"
WHERE A."OrderApi__Memo__c" <> B."Description__c"
;

SELECT
    A."OrderApi__Item_Class__c",
    B."Legacy_Item_Class_Name__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION_LINE__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B
        ON A."Id" = B."Legacy_Transaction_Line_Item_Id__c"
WHERE A."OrderApi__Memo__c" <> B."Description__c"
;

SELECT B."Legacy_Item_Class_Name__c", COUNT(*) FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B GROUP BY 1;

SELECT
    A."OrderApi__Debit__c",
    A."OrderApi__Credit__c",
    B."Sales_Price__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION_LINE__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B
        ON A."Id" = B."Legacy_Transaction_Line_Item_Id__c"
WHERE A."OrderApi__Debit__c" <> B."Sales_Price__c" OR A."OrderApi__Credit__c" <> B."Sales_Price__c";

SELECT B."Subscription_Line_Legacy_Id__c" FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B WHERE B."Subscription_Line_Legacy_Id__c" IS NOT NULL;

SELECT B."Legacy_Transaction_Id__c" FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B WHERE B."Legacy_Transaction_Id__c" IS NOT NULL;

SELECT B."Receipt_Line_Legacy_ID__c" FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B WHERE B."Receipt_Line_Legacy_ID__c" IS NOT NULL;

SELECT B."Receipt_Legacy_ID__c" FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B WHERE B."Receipt_Legacy_ID__c" IS NOT NULL;

SELECT B."Sales_Order_Line_Legacy_Id__c" FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B WHERE B."Sales_Order_Line_Legacy_Id__c" IS NOT NULL;

SELECT
    A."OrderApi__Receipt_Line__c",
    B."Receipt_Line_Legacy_ID__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION_LINE__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B
        ON A."Id" = B."Legacy_Transaction_Line_Item_Id__c"
WHERE A."OrderApi__Receipt_Line__c" IS NOT NULL;


SELECT B."Membership_Product__c", COUNT(*) FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B GROUP BY 1;

SELECT
    A."OrderApi__Receipt__c",
    B."Receipt_Legacy_ID__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION_LINE__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B
        ON A."Id" = B."Legacy_Transaction_Line_Item_Id__c"
WHERE A."OrderApi__Receipt__c" <> B."Receipt_Legacy_ID__c";

SELECT B."TLI_Type__c" FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B WHERE B."TLI_Type__c" IS NULL;

SELECT B."TLI_Type__c", COUNT(*) FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B GROUP BY 1 ORDER BY 1;

SELECT "TLI_Type__c", COUNT(*) FROM TEST.REPL_NPC_OWN_FULL.TRANSACTION_LINE_ITEM__C GROUP BY 1 ORDER BY 1;

SELECT B. FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B WHERE B."TLI_Type__c" IS NULL;

SELECT
    A."OrderApi__GL_Account__c",
    B."Legacy_GL_Code__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION_LINE__C A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES B
        ON A."Id" = B."Legacy_Transaction_Line_Item_Id__c"
WHERE A."OrderApi__GL_Account__c" <> B."Legacy_GL_Code__c";



SELECT 
    * 
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION A
    JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY B
        ON A."DonorIdMatch" = B."npsp__Primary_Contact__c"
;

SELECT 
    * 
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION A;


SELECT A."npe01__Preferred_Email__c" FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A;

SELECT * FROM FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A WHERE A.;


SELECT DISTINCT A."npe01__Preferred_Email__c" FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A WHERE A."npe01__Preferred_Email__c" NOT LIKE '%@%';

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A WHERE A."npe01__Preferred_Email__c" IS NULL;





SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A WHERE A."OrderApi__Other_Email__c" = 'erin.scheidemann@gmail.com';














SELECT  
    A."AccountId",
    B.LEGACY_OPPORTUNITY_ACCOUNT__C
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B
        ON A."Id" = B.OPPORTUNITY__C
WHERE A."AccountId" <> B.LEGACY_OPPORTUNITY_ACCOUNT__C;





SELECT 
    A."Company__c",
    A."Id",
    A."Fonteva_Account_ID__c" 
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT A 
WHERE A."Company__c" IS NOT NULL;



SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION B JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_MEMBERSHIP C ON B."Membership__c" = C."Id";






with E AS ( --Unpivots email fields for new row for each email per Fonteva ID from Cass' view
    SELECT 
        "Id", --Fonteva ID
        email_address AS "Email",
        email_type AS "ET",
        CURRENT_TIMESTAMP AS "CreatedDate"
    FROM TEST.DATA_FOR_IDR_SEEDING.PERSON_DATA --Cass' view
    UNPIVOT (email_address FOR email_type IN (
        "OrderApi__Work_Email__c",
        "OrderApi__Personal_Email__c",
        "OrderApi__Other_Email__c"
        )) AS unpvt
    WHERE email_address IS NOT NULL
    ),
People AS ( --Grabs PersonId from Person IDR table, joins Cass' view on Fonteva ID = Origin Legacy ID
    SELECT 
        P."Id" AS "PersonId",
        E."Email",
        CASE 
            WHEN E."ET" = 'OrderApi__Work_Email__c' THEN 'Work'
            WHEN E."ET" = 'OrderApi__Personal_Email__c' THEN 'Personal'
            WHEN E."ET" = 'OrderApi__Other_Email__c' THEN 'Other'
        END AS "EmailType",
        E."CreatedDate"
    FROM IDR.RESULTS.PERSON AS P
        JOIN E
            ON P.ORIGIN_LEGACY_ID = E."Id" --E."Id" is fonteva ID, ORIGING_LEGACY_ID should match for data added yesterday
    )
SELECT
    "PersonId",
    COUNT(DISTINCT "Email")
FROM People
GROUP BY 1
HAVING COUNT(DISTINCT "Email") > 1
ORDER BY 2 DESC;

with E AS ( --Unpivots email fields for new row for each email per Fonteva ID from Cass' view
    SELECT 
        "Id", --Fonteva ID
        email_address AS "Email",
        email_type AS "ET",
        CURRENT_TIMESTAMP AS "CreatedDate"
    FROM TEST.DATA_FOR_IDR_SEEDING.PERSON_DATA --Cass' view
    UNPIVOT (email_address FOR email_type IN (
        "OrderApi__Work_Email__c",
        "OrderApi__Personal_Email__c",
        "OrderApi__Other_Email__c"
        )) AS unpvt
    WHERE email_address IS NOT NULL
    ),
People AS ( --Grabs PersonId from Person IDR table, joins Cass' view on Fonteva ID = Origin Legacy ID
    SELECT 
        P."Id" AS "PersonId",
        E."Email",
        CASE 
            WHEN E."ET" = 'OrderApi__Work_Email__c' THEN 'Work'
            WHEN E."ET" = 'OrderApi__Personal_Email__c' THEN 'Personal'
            WHEN E."ET" = 'OrderApi__Other_Email__c' THEN 'Other'
        END AS "EmailType",
        E."CreatedDate"
    FROM IDR.RESULTS.PERSON AS P
        JOIN E
            ON P.ORIGIN_LEGACY_ID = E."Id" --E."Id" is fonteva ID, ORIGING_LEGACY_ID should match for data added yesterday
    )
SELECT
    *
FROM People
WHERE "PersonId" = '805278';



SELECT
    A."Wire_Type__c",
    B."Wire_Type__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION_OPPORTUNITY B
        ON A."Id" = B."Legacy_Opportunity_ID__c"
WHERE A."Wire_Type__c" IS NOT NULL OR B."Wire_Type__c" IS NOT NULL;



SELECT
    B."EffectiveStartDate",
    C."npe01__Scheduled_Date__c"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION_COMMITMENT B
        ON A."Id" = B."Legacy_Opportunity_Id__c"
    JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE01__OPPPAYMENT__C C
        ON A."Id" = C."npe01__Opportunity__c";


SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION_COMMITMENT;


SELECT A."iMIS_ID__c"  FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT A WHERE A."Name" LIKE '%Individual%';

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT A WHERE A."iMIS_ID__c" IS NULL AND A."Name" NOT LIKE '%Individual%';

SELECT 
    CON."Name", 
    CASE
        WHEN CON."iMIS_ID__c" IS NULL THEN CON."Salesforce_ID__c"
        ELSE CON."iMIS_ID__c"
    END AS AACR_ID
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON;

SELECT 
    ACC."Name", 
    CASE
        WHEN ACC."Name" NOT LIKE '%Individual%' THEN ACC."iMIS_ID__c"
    END AS ACCOUNT_AACR_ID
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC;


SELECT A. FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES A WHERE A."Gift_Transaction__c" IS NOT NULL;

--Legacy_Transaction_Line_Item_Id__c
SELECT A."Legacy_Transaction_Line_Item_Id__c" FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_TRANSACTION_LINES A WHERE A."Legacy_Transaction_Line_Item_Id__c" IS  NULL;





SELECT * FROM TEST.REPL_NPC_OWN_FULL.PREMIUMS_ASSIGNMENT__C WHERE "Name" NOT LIKE '%Journal%' AND "RecordTypeId" = '012Vq000000yGYCIA2';





SELECT A."Membership_Premium_Type__c" FROM TEST.REPL_NPC_OWN_FULL.PREMIUMS_ASSIGNMENT__C A WHERE A."Membership_Premium_Type__c" IS NOT NULL;

SELECT * FROM TEST.REPL_NPC_OWN_FULL.PREMIUMS_ASSIGNMENT__C A WHERE A."Transaction_Date__c" IS NULL; --222/269


SELECT A."CloseDate" FROM TEST.REPL_NPC_OWN_FULL.OPPORTUNITY A;


SELECT ."TransactionDate" FROM TEST.REPL_NPC_OWN_FULL.GIFTTRANSACTION A WHERE A."Legacy_Receipt_ID__c" IS NOT NULL;


SELECT T."OrderApi__Receipt__c" FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__TRANSACTION__C AS T WHERE T."OrderApi__Receipt__c" IS NULL;




/*********************************************
*
* Full audit, programmatic in SQL
*
**********************************************/

create schema if not exists TEST.ANALYTICS_AUDIT;

create or replace table TEST.ANALYTICS_AUDIT.COLUMN_QUALITY (
  captured_at           timestamp_ntz default current_timestamp(),
  database_name         string,
  schema_name           string,
  table_name            string,
  column_name           string,
  data_type             string,
  row_count             number,
  null_count            number,
  non_null_count        number,
  null_pct              number(5,2),
  approx_distinct_count number,          -- optional but useful
  sample_value          variant          -- tiny sanity check
);


-- Change these:
set DB_NAME     = 'TEST';
set SCHEMA_NAME = 'REPL_NPC_OWN_FULL';
set TABLE_LIST  = 'GIFTTRANSACTION,ACCOUNT,MEMBERSHIP__C,OPPORTUNITY,TRANSACTION_LINE_ITEM__C';

begin
  let v_sql string;

  create or replace temporary table TMP_TABLES as
  select table_catalog as database_name,
         table_schema  as schema_name,
         table_name
  from   information_schema.tables
  where  table_catalog = $DB_NAME
    and  table_schema  = $SCHEMA_NAME
    and  table_type    = 'BASE TABLE'
    and ( $TABLE_LIST = '' or table_name in (
          select value::string from table(split_to_table($TABLE_LIST, ','))
        ));

  for rec in (select database_name, schema_name, table_name from TMP_TABLES) do
    -- Copy record values into scalar variables
    let db  string := rec.database_name;
    let sch string := rec.schema_name;
    let tbl string := rec.table_name;

    -- Option A: ACCOUNT_USAGE (may have ~90 min latency)
    let cols resultset := (
      select column_name, data_type
      from SNOWFLAKE.ACCOUNT_USAGE.COLUMNS
      where table_catalog = :db
        and table_schema  = :sch
        and table_name    = :tbl
      order by ordinal_position
    );

    /* Option B (immediate metadata). If you prefer this, comment Option A above and uncomment below:
    let cols_sql string := 
      'select column_name, data_type
       from ' || :db || '.information_schema.columns
       where table_schema = ''' || :sch || '''
         and table_name   = ''' || :tbl || '''
       order by ordinal_position';
    let cols resultset := (execute immediate :cols_sql);
    */

    let unions string := '';
    let sep string := '';

    for c in cols do
      let col_name   string := c.COLUMN_NAME;
      let data_type  string := c.DATA_TYPE;
      let col_quoted string := '"' || col_name || '"';  -- quote identifiers

      -- Build the UNION clause using scalar variables only
      unions := unions || sep || '
        select
          ''' || db || '''  as database_name,
          ''' || sch || ''' as schema_name,
          ''' || tbl || ''' as table_name,
          ''' || col_name || '''  as column_name,
          ''' || data_type || ''' as data_type,
          count(*)                                     as row_count,
          sum(iff(' || col_quoted || ' is null, 1, 0))     as null_count,
          sum(iff(' || col_quoted || ' is not null, 1, 0)) as non_null_count,
          approx_count_distinct(' || col_quoted || ')      as approx_distinct_count,
          any_value(' || col_quoted || ')                  as sample_value
        from ' || db || '.' || sch || '.' || tbl;

      sep := ' union all ';
    end for;

    if (unions is not null and length(unions) > 0) then
      v_sql := '
        insert into TEST.ANALYTICS_AUDIT.COLUMN_QUALITY
        (database_name, schema_name, table_name, column_name, data_type,
         row_count, null_count, non_null_count, null_pct, approx_distinct_count, sample_value)
        select database_name, schema_name, table_name, column_name, data_type,
               row_count, null_count, non_null_count,
               iff(row_count=0, 0, round(null_count*100.0/row_count, 2)) as null_pct,
               approx_distinct_count, sample_value
        from (' || unions || ')
      ';
      execute immediate :v_sql;
    end if;

  end for;
end;




-- Browse results
select *
from ANALYTICS_AUDIT.COLUMN_QUALITY
where schema_name = $SCHEMA_NAME
order by null_pct desc, table_name, column_name;




--Legacy_Item_Class_Name__c
SELECT DISTINCT "Legacy_Item_Class_Name__c" FROM TEST.REPL_NPC_OWN_FULL.PREMIUMS_ASSIGNMENT__C;

--Legacy_Receipt_ID__c
SELECT * FROM TEST.REPL_NPC_OWN_FULL.PREMIUMS_ASSIGNMENT__C WHERE "Legacy_Receipt_ID__c" IS NULL;

--LastActivityDate
SELECT * FROM TEST.REPL_NPC_OWN_FULL.PREMIUMS_ASSIGNMENT__C WHERE "Transaction_Date__c" IS NULL;

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A WHERE A."Name" LIKE '%Test%'; --173k vs. 165k

SELECT * FROM TEST.REPL_NPC_OWN_FULL.OPPORTUNITY; --2k

SELECT DISTINCT A."Status" FROM TEST.REPL_NPC_OWN_FULL.GIFTTRANSACTION A; --163.6k


SELECT * FROM TEST.REPL_NPC_OWN_FULL.PREMIUMS_ASSIGNMENT__C WHERE "Name" LIKE 'a%';

SELECT 
    * 
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
WHERE A."Id" NOT IN (SELECT B."Legacy_Id__c" FROM TEST.REPL_NPC_OWN_FULL.OPPORTUNITY B)
    OR A."Id" NOT IN (SELECT C."Legacy_Opportunity_ID__c" FROM TEST.REPL_NPC_OWN_FULL.GIFTTRANSACTION C);

with NPCOpps AS (
    SELECT B."Legacy_Id__c" AS OPP_ID FROM TEST.REPL_NPC_OWN_FULL.OPPORTUNITY B
    UNION ALL 
    SELECT C."Legacy_Opportunity_ID__c" AS OPP_ID FROM TEST.REPL_NPC_OWN_FULL.GIFTTRANSACTION C
)
SELECT 
    * 
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
WHERE A."Id" NOT IN (SELECT OPP_ID FROM NPCOpps)
;

SELECT 
    A."ExpectedRevenue"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY A
WHERE A."ExpectedRevenue" IS NULL;

SELECT A."Fiscal" FROM TEST.REPL_NPC_OWN_FULL.OPPORTUNITY A;


SELECT A."CreatedDate" FROM TEST.REPL_NPC_OWN_FULL.GIFTTRANSACTION A WHERE A."CreatedDate" IS NOT NULL;


/*

select 
'012Vq000001Id46IAC' RecordTypeId, o."CampaignId" CampaignId, o."CloseDate" TransactionDate, o."StageName" Status, o."npsp__Acknowledgment_Status__c" AcknowledgementStatus, o."Amount" OriginalAmount, o."npsp__Acknowledgment_Date__c" AcknowledgementDate, o."ddrive__DD_Original_Processing_Fee_Amount__c" ProcessorTransactionFee, o."ddrive__Sum_Tax_Deduction__c" TaxDeductionAmount, o."npsp__In_Kind_Type__c" In_Kind_Type__c, o."npsp__In_Kind_Description__c" 
In_Kind_Description__c, o."ddrive__Donation_Receipt_ID__c" Legacy_Receipt_ID__c, o."npsp__Notification_Message__c" Donation_Message__c, o."ddrive__DonorDrive_Recurring_Profile_ID__c" DD_Recurring_Profile_ID__c, o."ddrive__DonorDrive_Matching_Employer__c" DonorDrive_Matching_Employer__c, o."ddrive__Ticket_Type__c" DonorDrive_Ticket_Type__c, o."npsp__Tribute_Type__c" DonorDrive_Honor_or_Memory__c, o."npsp__Honoree_Name__c" 
DonorDrive_Honor_Name__c, o."npsp__Notification_Recipient_Name__c" DonorDrive_Tribute_Recipient_Name__c, o."ddrive__DonorDrive_Gift_Description__c" 
Legacy_DD_Description__c, o."ddrive__Donation_Receipt_ID__c" Legacy_DD_Receipt_ID__c, o."ddrive__Donation_Transaction_ID__c" Legacy_DonorDrive_Transaction_ID__c, o."AccountId" Legacy_Opportunity_Account__c, o."ContactId" Legacy_Opportunity_Contact__c, 
o."ddrive__Donation_Receipt_Date__c" Tax_Receipt_Date__c, o."Wire_Type__c" Wire_Type__c, o."c4g_Check_Number__c" Check_Number__c, o."Description" Long_Description__c, o."npsp__Fair_Market_Value__c" Fair_Market_Value__c, o."Name" Name, o."AccountId" DonorIdAcct, o."npsp__Primary_Contact__c" DonorIdCont, 
o."c4g_Payment_Method__c" PaymentMethod, ac."Name" Legacy_Appeal_Code__c, o."GL_Account__c" Legacy_Distribution_Code__c
from Opportunity o
join recordtype rt on o."RecordTypeId" = rt."Id"
Left Outer Join orderapi__sales_order__c so on o."Id" = so."Opportunity__c"
Left Outer Join orderapi__sales_order_line__c sol on o."Id" = sol."Opportunity__c"
Left Outer Join appeal_code__c ac on o."c4g_Appeal_Code__c" = ac."Id"
where so."Id" is null and sol."Id" is null and o."StageName" IN ('Posted','Closed Won') and o."Amount" > 0

 */


SELECT A."BillingStreet" FROM TEST.REPL_NPC_OWN_FULL.ACCOUNT A WHERE A."BillingStreet" IS NOT NULL;

SELECT A."Name", A."Type", A."BillingStreet" FROM TEST.REPL_NPC_OWN_FULL.ACCOUNT A WHERE A."RecordTypeId" = '012Vq000000sGUQIA2';

SELECT A."BillingStreet" FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT A WHERE "Name" LIKE '%New Green Livestock Co., Ltd.%';



SELECT
    A."BillingStreet",
    C."BillingStreet",
    A."Id" AS FONTEVA_ID,
    C."Id" AS NPC_ID
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS A
    JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.IDCROSSWALK AS B
        ON A."Id" = B.ACCOUNT_ID_FONTEVA
    JOIN TEST.REPL_NPC_OWN_FULL.ACCOUNT AS C
        ON B.ACCOUNT_ORG_ID_FULL = C."Id"
WHERE A."BillingStreet" <> C."BillingStreet" 
;




SELECT * FROM TEST.REPL_NPC_OWN_FULL.OPPORTUNITY;



SELECT * FROM TEST.REPL_NPC_OWN_FULL.PREMIUMS_ASSIGNMENT__C P; WHERE P."Account__c" IS NULL;


SELECT * FROM TEST.REPL_NPC_OWN_FULL.PREMIUMS_ASSIGNMENT__C P WHERE P."Transaction_Date__c" IS NULL AND "Name" LIKE '%Journal%';


SELECT DISTINCT P."RecordTypeId" FROM TEST.REPL_NPC_OWN_FULL.PREMIUMS_ASSIGNMENT__C P WHERE P."Name" NOT LIKE '%Journal%';

SELECT DISTINCT P."Name" FROM TEST.REPL_NPC_OWN_FULL.PREMIUMS_ASSIGNMENT__C P;





SELECT * FROM TEST.REPL_NPC_OWN_FULL.TRANSACTION_LINE_ITEM__C A;


SELECT * FROM TEST.REPL_NPC_OWN_FULL.GIFTTRANSACTION WHERE "Legacy_Transaction_ID__c" IS NULL;


SELECT * FROM TEST.REPL_NPC_OWN_8PAUL.CAMPAIGN WHERE "Name" NOT LIKE '%Test %';





SELECT * FROM IDR.RESULTS.PERSON WHERE "Id" IN ();

SELECT * FROM IDR.RESULTS.UNIQUEID B WHERE "SourceSystem" = 'Fonteva' AND "PersonId" IS NULL;



SELECT  
    *
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__RECEIPT__C AS RC
    LEFT JOIN ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION AS GT
        ON RC."Id" = GT."Legacy_Receipt_ID__c";

SELECT 
    COUNT(*),
    SUM(CASE WHEN A."Legacy_Receipt_ID__c" IS NOT NULL THEN 1 ELSE 0 END)
FROM TEST.REPL_NPC_OWN_FULL.GIFTTRANSACTION A;

SELECT 
    COUNT(*),
    SUM(CASE WHEN A.GIFT_TRANSACTION__C IS NOT NULL THEN 1 ELSE 0 END)
FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_PREMIUM_ASSIGNMENT_GROUPS A;

SELECT 
    COUNT(*),
    SUM(CASE WHEN A."Receipt_Legacy_ID__c" IS NOT NULL THEN 1 ELSE 0 END)
FROM TEST.REPL_NPC_OWN_FULL.TRANSACTION_LINE_ITEM__C A;


SELECT * FROM TEST.REPL_NPC_OWN_FULL.ACEM__EVENT__C;

SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_GIFT_TRANSACTION;

--TEST.REPL_NPC_OWN_8PAUL.ACEM__EVENT_PARTICIPATION__C and TEST.REPL_NPC_OWN_8PAUL.ACEM__EVENT__C

SELECT * FROM TEST.REPL_NPC_OWN_8PAUL.ACEM__EVENT_PARTICIPATION__C;

SELECT * FROM TEST.REPL_NPC_OWN_FULL.PREMIUMS_ASSIGNMENT__C;

SELECT * FROM TEST.REPL_NPC_OWN_FULL.ORGANIZATION;





SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__RECEIPT__C;



SELECT * FROM TEST.REPL_NPC_OWN_FULL.GIFTTRANSACTION;

SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_MEMBERSHIP;

SELECT *, B."AACR_ID__c" FROM TEST.REPL_NPC_OWN_FULL.MEMBERSHIP__C A
    JOIN TEST.REPL_NPC_OWN_FULL.ACCOUNT B
        ON A."Account__c" = B."Id"
WHERE B."AACR_ID__c" = '1292769';

SELECT * FROM TEST.REPL_NPC_OWN_FULL.ACCOUNT A WHERE A."AACR_ID__c" = '1292769';

SELECT "Id" FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_ACCOUNT A WHERE A."AACR_Id__c" = '1292769';



SELECT * FROM TEST.REPL_NPC_OWN_FULL.MEMBERSHIP__C A WHERE A."Account__c" = '001WA00000OSAi0YAH';

SELECT * FROM TEST.REPL_NPC_OWN_8PAUL.MEMBERSHIP__C A WHERE A."Account__c" = '001WA00000OSAi0YAH';

SELECT * FROM PRODUCTION.MART_MEMBERSHIP_HISTORY.MEMBERSHIP_HISTORY_FINAL A WHERE A."SALESFORCE ID" = '0038W00002MADU0QAP';

SELECT * FROM TEST.MEMBERSHIP_MIGRATION_TABLES.MEMBERSHIP_TRANSACTIONS;


SELECT DISTINCT A."Legacy_Item_Name__c" FROM TEST.REPL_NPC_OWN_FULL.PREMIUMS_ASSIGNMENT__C A;



/*
SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT,
SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT,
SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE5__AFFILIATION__C,
SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.NPE4__RELATIONSHIP__C,
SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__KNOWN_ADDRESS__C,
SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.COMMITTEE__C,
SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.COMMITTEE_MEMBER__C,
SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CASE,
SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.TASK,
SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.EDUCATION__C


 */



SELECT 
    * 
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT A WHERE A."Name" NOT LIKE '%Individual%';


SELECT 
    * 
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT
WHERE "Name" IN ('Ivan Horak',
'Na Ding',
'Tony Cheung',
'Manju George',
'Beverly Lyn-Cook',
'Patricia LoRusso',
'Judith Abramson',
'Kristin Altwegg',
'Phillip Greenberg');

SELECT * FROM PRODUCTION.REPL_NPC.ACCOUNT WHERE "FirstName" LIKE '%John%' AND "LastName" LIKE '%Carpten%';


SELECT * FROM TEST.TEST_AREA.MEMBERSHIP_PUSH_MERGE WHERE "SALESFORCE ID" = '0031I00000WsoMPQAZ';

SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_MEMBERSHIP A WHERE A."Account__c"= '001Vq00000U8hKWIAZ';

select *  from TEST.TEST_AREA.MEMBERSHIP_PUSH_MERGE where "TERM ID" = 'a1DRm0000004wTdMAI'
;

SELECT * FROM ATTAIN_MIGRATION.MIGRATION_TO_NPC.STG_MEMBERSHIP A WHERE A."Primary_Contact__c_Match1" = '0038W00001vqiehQAA';


/*
'Ivan Horak',
'Na Ding',
'Tony Cheung',
'Manju George',
'Beverly Lyn-Cook',
'Patricia LoRusso',
'Judith Abramson',
'Kristin Altwegg',
'Phillip Greenberg'


 */



SELECT 
    CON."Name", 
    CASE
        WHEN CON."iMIS_ID__c" IS NULL THEN CON."Salesforce_ID__c"
        ELSE CON."iMIS_ID__c"
    END AS AACR_ID,
    LEN(CASE
        WHEN CON."iMIS_ID__c" IS NULL THEN CON."Salesforce_ID__c"
        ELSE CON."iMIS_ID__c"
    END) AS AACR_LEN
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON
ORDER BY 3 DESC, 2 DESC;

with conac AS (
    SELECT 
        CON."Name", 
        CON."Id",
        CASE
            WHEN CON."iMIS_ID__c" IS NULL THEN CON."Salesforce_ID__c"
            ELSE CON."iMIS_ID__c"
        END AS AACR_ID,
        LEN(CASE
            WHEN CON."iMIS_ID__c" IS NULL THEN CON."Salesforce_ID__c"
            ELSE CON."iMIS_ID__c"
        END) AS AACR_LEN
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON
)
SELECT
    "Name",
    "Id",
    CAST(AACR_ID AS NUMBER) AS AACR_CORRECTED
FROM conac
ORDER BY 3 DESC;



SELECT * FROM PRODUCTION.REPL_NPC.ACEM__EVENT_PARTICIPATION__C;








SELECT
    A."Id" AS FONTEVA_ID,
    CASE
        WHEN A."iMIS_ID__c" IS NULL THEN A."Salesforce_ID__c"
        ELSE A."iMIS_ID__c"
    END AS AACR_ID,
    A."Paid_thru_date__c",
    A."FirstName",
    A."MiddleName",
    A."LastName"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS A
    JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__BADGE__C AS B
        ON A."Id" = B."OrderApi__Contact__c"
    JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__BADGE_TYPE__C C
        ON B."OrderApi__Badge_Type__c" = C."Id"
WHERE C."Name" = 'AACR Fellow'
;


SELECT "ContactId" FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP."USER" 
WHERE "Id" IN ('0051I000002qWeDQAU',
'0051I000002pqO0QAI',
'0051I000002pvjfQAA',
'0051I000006GoGbQAK',
'0051I000006Gr1ZQAS',
'0051I000006GsWxQAK',
'0051I000006GtN3QAK',
'0051I000006H6ygQAC',
'0051I000006hkCYQAY',
'0051I000006Gso8QAC',
'0051I000006hv3mQAA',
'0051I000006mpqnQAA',
'0051I000007GL6aQAG',
'0051I000007HAOBQA4',
'0051I000007JULcQAO',
'0051I000007nD8aQAE',
'0058W000008YbxaQAC',
'0058W000008YhtkQAC',
'0058W000008YlL8QAK',
'0051I000008XsA4QAK',
'0058W00000EwCU6QAN',
'0058W00000FDxyNQAT',
'0058W00000FDwlSQAT',
'0051I000000bGnSQAU',
'0051I000002F0U6QAK',
'0051I000002oAGAQA2',
'0051I000002oAFJQA2',
'0051I000002pbplQAA',
'0051I000003wBXKQA2',
'0051I000005WpRIQA0',
'0051I000005Y9iYQAS',
'0051I000006FiuXQAS',
'0051I000006Fnm5QAC',
'0051I000006GPCoQAO');




/*
'0051I000002qWeDQAU',
'0051I000002pqO0QAI',
'0051I000002pvjfQAA',
'0051I000006GoGbQAK',
'0051I000006Gr1ZQAS',
'0051I000006GsWxQAK',
'0051I000006GtN3QAK',
'0051I000006H6ygQAC',
'0051I000006hkCYQAY',
'0051I000006Gso8QAC',
'0051I000006hv3mQAA',
'0051I000006mpqnQAA',
'0051I000007GL6aQAG',
'0051I000007HAOBQA4',
'0051I000007JULcQAO',
'0051I000007nD8aQAE',
'0058W000008YbxaQAC',
'0058W000008YhtkQAC',
'0058W000008YlL8QAK',
'0051I000008XsA4QAK',
'0058W00000EwCU6QAN',
'0058W00000FDxyNQAT',
'0058W00000FDwlSQAT',
'0051I000000bGnSQAU',
'0051I000002F0U6QAK',
'0051I000002oAGAQA2',
'0051I000002oAFJQA2',
'0051I000002pbplQAA',
'0051I000003wBXKQA2',
'0051I000005WpRIQA0',
'0051I000005Y9iYQAS',
'0051I000006FiuXQAS',
'0051I000006Fnm5QAC',
'0051I000006GPCoQAO')



 */


SELECT E."Name", E."Id", E."Start_Date__c", E."End_Date__c" FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_EVENT__C AS E ORDER BY 1;

SELECT * FROM PRODUCTION.REPL_NPC.




























