with CONAACR AS (
    SELECT *, CASE
        WHEN CON."iMIS_ID__c" IS NULL THEN CON."Salesforce_ID__c"
        ELSE CON."iMIS_ID__c"
    END AS AACR_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON
),
CTI_ALL AS (
    SELECT AACRID, MEETING_ID, MEETING_NAME, MEETING_YEAR, SESSION_TYPE_NAME, ACTIVITY_NAME, PROGRAM_STATUS_NAME FROM PRODUCTION.MART_CTI_MATCHES.ABSTRACT_PRESENTERS__V
    UNION ALL
    SELECT AACRID, MEETING_ID, MEETING_NAME, MEETING_YEAR, SESSION_TYPE_NAME, ACTIVITY_NAME, PROGRAM_STATUS_NAME FROM PRODUCTION.MART_CTI_MATCHES.INVITED_SPEAKERS__V
)
SELECT
    CTI.*,
    ACC."Name"
FROM PRODUCTION.MART_OPEN_WATER.APPLICANTS AS APP
    LEFT JOIN CONAACR AS CON
        ON APP.AACR_ID = CON.AACR_ID
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT AS ACC
        ON CON."AccountId" = ACC."Id"
    LEFT JOIN CTI_ALL AS CTI
        ON CON.AACR_ID = CTI.AACRID
WHERE ACC."Name" LIKE '%Astra%' AND CTI.AACRID IS NOT NULL
;


SELECT * FROM TEST.TEST_AREA.MERGESQA
WHERE CONTACT_ID = '0031I000017VbYcQAK';



CREATE SCHEMA TEST.CONTACT_USER_MERGE;

CREATE OR REPLACE VIEW TEST.CONTACT_USER_MERGE.CONTACT_USER_MERGE
AS
with PART_COUNT AS (
        SELECT
        BRP."Contact__c",
        COUNT(*) AS PARTICIPATION_COUNT,
        BRP."User__c" AS USER_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_PARTICIPATION__C AS BRP
    WHERE BRP."Contact__c" IS NOT NULL AND BRP."User__c" IS NOT NULL
    GROUP BY 1, 3
)
SELECT
    CON.*,
    US."Id" AS USER_ID,
    RT."Id" AS RECORD_TYPE_ID,
    RT."Name" AS RECORD_TYPE_NAME,
    PART_COUNT.PARTICIPATION_COUNT AS PARTICIPATION_COUNT
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.USER AS US
        ON CON."Id" = US."ContactId"
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.RECORDTYPE AS RT
        ON CON."RecordTypeId" = RT."Id"
    LEFT JOIN PART_COUNT
        ON US."Id" = PART_COUNT.USER_ID;


SELECT COUNT(*) FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON WHERE CON.Use;



SELECT
    BRP."Contact__c",
    COUNT(*) AS PARTICIPATION_COUNT,
    BRP."User__c" AS USER_ID
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_PARTICIPATION__C AS BRP
WHERE BRP."Contact__c" IS NOT NULL AND BRP."User__c" IS NOT NULL
GROUP BY 1, 3
;


SELECT DISTINCT("Id") FROM TEST.CONTACT_USER_MERGE.CONTACT_USER_MERGE WHERE PARTICIPATION_COUNT IS NOT NULL;

SELECT * FROM TEST.CONTACT_USER_MERGE.CONTACT_USER_MERGE;


SELECT "Id", COUNT(*) FROM TEST.CONTACT_USER_MERGE.CONTACT_USER_MERGE GROUP BY "Id" HAVING COUNT(*) > 1;







SELECT DISTINCT REGISTRATION_CATEGORY FROM PRODUCTION.MART_CSI_AM24_REG.AM24_REG_V ORDER BY 1 DESC;



SELECT * FROM PRODUCTION.MART_CSI_AM24_REG.AM24_REG_V;

with Speakers AS (
SELECT * FROM PRODUCTION.MART_CTI_MATCHES.INVITED_SPEAKERS__V 
WHERE MEETING_NAME = '2024 Annual Meeting' AND ACTIVITY_NAME = 'Invited Speaker' AND SESSION_ROLE_STATUS = 'Confirmed' AND MATCH = true)
SELECT DISTINCT PUBLISHING_TITLE, LEN(PUBLISHING_TITLE) FROM Speakers
ORDER BY 2 DESC
;

SELECT * FROM PRODUCTION.MART_CTI_MATCHES.INVITED_SPEAKERS__V;

SELECT DISTINCT CON."Title" FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON;


SELECT * FROM PRODUCTION.REPL_CTI.INVITED_SPEAKERS_CHAIRS WHERE ACTIVITY_NAME = 'Invited Speaker' AND MEETING_YEAR = 2024;






select * from boomi_golden_contact_user_merge where user_id is NULL and "Member_Type__c" is NULL and record_type_name = 'Nonmember';



CREATE OR REPLACE VIEW PRODUCTION.MART_CTI_MATCHES.SPEAKER_DEMOGRAPHICS
AS
SELECT 
    *
FROM PRODUCTION.MART_CTI_MATCHES.INVITED_SPEAKERS__V
WHERE MEETING_NAME = '2024 Annual Meeting'
AND SESSION_TYPE_NAME IN ('Awards and Lectures',
'Awards and Lectures ',
'Advances in Diagnostics and Therapeutics',
'Advances in Organ Site Research',
'Advances in Population Research',
'Advances in Technologies',
'Advances in the Science of Cancer Disparities',
'Clinical Trials Minisymposium',
'Clinical Trials Plenary',
'Educational Session',
'Forum',
'Late-Breaking Minisymposium',
'Major Symposium',
'Methods Workshop',
'Minisymposium',
'Plenary Session',
'Special Session')
AND MATCH = true
AND SESSION_TITLE IN ('Presidential Address: Engineering T Cells to Eradicate Tumors - Identifying and Overcoming the Obstacles', 'AACR-Irving Weinstein Foundation Distinguished Lectureship')
;



CREATE OR REPLACE VIEW PRODUCTION.MART_CTI_MATCHES.SPEAKER_DEMOGRAPHICS
AS
with Awards AS (
    SELECT 
        *
    FROM PRODUCTION.MART_CTI_MATCHES.INVITED_SPEAKERS__V
    WHERE MEETING_NAME = '2024 Annual Meeting'
    AND SESSION_TYPE_NAME = 'Awards and Lectures'
    AND SESSION_TITLE IN 
        ('Presidential Address: Engineering T Cells to Eradicate Tumors - Identifying and Overcoming the Obstacles', 
        'AACR-Irving Weinstein Foundation Distinguished Lectureship')
    AND MATCH = true
),
    Other AS (
        SELECT 
            *
        FROM PRODUCTION.MART_CTI_MATCHES.INVITED_SPEAKERS__V
        WHERE MEETING_NAME = '2024 Annual Meeting'
        AND SESSION_TYPE_NAME IN 
        ('Advances in Diagnostics and Therapeutics',
        'Advances in Prevention Research',
        'Advances in Population Sciences',
        'Advances in Hematologic Malignancies',
        'Advances in Technologies',
        'Advances in Organ Site Research',
        'Advances in Population Research',
        'Advances in Technologies',
        'Advances in the Science of Cancer Disparities',
        'Clinical Trials Minisymposium',
        'Clinical Trials Plenary',
        'Educational Session',
        'Forum',
        'Late-Breaking Minisymposium',
        'Major Symposium',
        'Methods Workshop',
        'Meet the Expert Session',
        'Meet-the-Expert Session',
        'Meet-the-Expert Sunrise Session',
        'Minisymposium',
        'Plenary Session',
        'Special Session')
        AND MATCH = true
    )
SELECT * FROM Awards
UNION ALL 
SELECT * FROM Other;



SELECT COUNT(*) FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT;


/*Less filters*/
CREATE OR REPLACE VIEW PRODUCTION.MART_CTI_MATCHES.SPEAKER_DEMOGRAPHICS
AS
SELECT 
    *
FROM PRODUCTION.MART_CTI_MATCHES.INVITED_SPEAKERS__V
WHERE MEETING_NAME = '2024 Annual Meeting'
AND SESSION_TYPE_NAME IN 
('Advances in Diagnostics and Therapeutics',
'Advances in Prevention Research',
'Advances in Population Sciences',
'Advances in Hematologic Malignancies',
'Advances in Technologies',
'Advances in Organ Site Research',
'Advances in Population Research',
'Advances in Technologies',
'Advances in the Science of Cancer Disparities',
'Awards and Lectures',
'Clinical Trials Minisymposium',
'Clinical Trials Plenary Session',
'Educational Session',
'Forum',
'Late-Breaking Minisymposium',
'Major Symposium',
'Methods Workshop',
'Meet the Expert Session',
'Meet-the-Expert Session',
'Meet-the-Expert Sunrise Session',
'Minisymposium',
'Plenary Session',
'Special Session')
AND MATCH = true;


SELECT 
    DISTINCT SESSION_TYPE_NAME
FROM PRODUCTION.MART_CTI_MATCHES.INVITED_SPEAKERS__V
WHERE MEETING_NAME = '2024 Annual Meeting'
AND SESSION_TYPE_NAME LIKE '%Clinical%';


/*
5 Plenary Sessions (2 hr) and 1 Wrap-up Plenary (90 min)
56 Major Symposia (90 min)
37 Advances Sessions (90 min)
-	9 Advances in Diagnostics and Therapeutics *
-	3 Advances in Prevention Research *
-	2 Advances in the Science of Cancer Disparities *
-	2 Advances in Population Sciences *
-	10 Advances in Organ Site Research *
-	6 Advances in Hematologic Malignancies * (NEW!)
-	7 Advances in Technologies *(NEW!)
9 Forums (90 min) and 8 Special Sessions (Pediatric, AACR-JCA, AACR-ASCO, SU2C, New Drugs)
5 Meet the Expert Sessions (45 min)
52 Educational Sessions and 16 Methods Workshops (90 min; Educational Program)

 */


SELECT DISTINCT SESSION_TYPE_NAME FROM PRODUCTION.MART_CTI_MATCHES.INVITED_SPEAKERS__V WHERE SESSION_TYPE_NAME LIKE '%Plenary%';



SELECT 
    COUNT(DISTINCT AACRID),
    ACTIVITY_NAME
 FROM PRODUCTION.MART_CTI_MATCHES.SPEAKER_DEMOGRAPHICS
 GROUP BY ACTIVITY_NAME
 ;



SELECT * FROM PRODUCTION.MART_CTI_MATCHES.SPEAKER_DEMOGRAPHICS WHERE AACRID NOT IN (SELECT PERSONMEMBERSPECIFICATION FROM TEST.TEST_AREA.SPEAKER_DATA_DEDUPED);

with CON AS (
    SELECT *, CASE
        WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
        ELSE CONC."iMIS_ID__c"
    END AS AACR_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
),
RN AS 
(SELECT 
    CON."Name",
    CON."Member_Type__c",
    CON.AACR_ID,
    CTI.AACRID,
    CTI.AUTHOR_FIRST_NAME,
    CTI.AUTHOR_LAST_NAME,
    CTI.ACTIVITY_NAME,
    FROM PRODUCTION.MART_CTI_MATCHES.SPEAKER_DEMOGRAPHICS AS CTI
        LEFT JOIN CON
            ON CTI.AACRID = CON.AACR_ID
WHERE AACRID NOT IN (SELECT PERSONMEMBERSPECIFICATION FROM TEST.TEST_AREA.SPEAKER_DATA_DEDUPED)
ORDER BY CON."Name")
SELECT DISTINCT * FROM RN;



with CON AS (
    SELECT *, CASE
        WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
        ELSE CONC."iMIS_ID__c"
    END AS AACR_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
)
SELECT
    CTI.AACRID,
    CTI.AUTHOR_FIRST_NAME,
    CTI.AUTHOR_LAST_NAME,
    CTI.ACTIVITY_NAME
FROM PRODUCTION.MART_CTI_MATCHES.SPEAKER_DEMOGRAPHICS AS CTI
WHERE CTI.AACRID NOT IN (SELECT CTIS.AACRID FROM PRODUCTION.MART_CTI_MATCHES.SPEAKER_DEMOGRAPHICS AS CTIS
                                                    INNER JOIN CON
                                                        ON CTIS.AACRID = CON.AACR_ID);


SELECT COUNT(*) FROM PRODUCTION.MART_CTI_MATCHES.SPEAKER_DEMOGRAPHICS AS AD WHERE AD.;

SELECT COUNT(DISTINCT PERSONMEMBERSPECIFICATION) FROM TEST.TEST_AREA.SPEAKER_DATA_DEDUPED;









SELECT * FROM PRODUCTION.MART_CTI_MATCHES.SPEAKER_DEMOGRAPHICS WHERE SESSION_ROLE_STATUS = 'Confirmed' AND ACTIVITY_NAME = 'Invited Speaker';

/*
'Awards and Lectures',
'Awards and Lectures ',
'Advances in Diagnostics and Therapeutics',
'Advances in Organ Site Research',
'Advances in Population Research',
'Advances in Technologies',
'Advances in the Science of Cancer Disparities',
'Clinical Trials Minisymposium',
'Clinical Trials Plenary',
'Educational Session',
'Forum',
'Late-Breaking Minisymposium',
'Major Symposium',
'Methods Workshop',
'Minisymposium',
'Plenary Session',
'Special Session',
*/



SELECT * FROM TEST.CONTACT_USER_MERGE.CONTACT_MERGE_TO_CLEAR;


SELECT * FROM PRODUCTION.MART_CTI_MATCHES.SPEAKER_DEMOGRAPHICS ORDER BY AACRID, ACTIVITY_NAME;



SELECT COUNT(*), CSR.MAILING_COUNTRY_NAME FROM PRODUCTION.MART_CSI_AM24_REG.AM24_REG_V AS CSR WHERE CSR.MAILING_COUNTRY_NAME IN (
'Algeria',
'Argentina',
'Chile',
'India',
'Jordan',
'Malaysia',
'Morocco',
'Nigeria',
'Poland',
'Taiwan',
'Uruguay',
'Ukraine')
GROUP BY CSR.MAILING_COUNTRY_NAME;

with CON AS (
    SELECT
        *,
            CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
)
SELECT 
    CON."MailingCountry",
    COUNT(*) + 0 AS "Count"
FROM PRODUCTION.MART_CSI_AM24_REG.AM24_REG_V AS CSR 
    LEFT JOIN CON
        ON CSR.AACR_ID = CON.AACR_ID
WHERE CON."MailingCountry" IN 
('Algeria',
'Argentina',
'Chile',
'India',
'Jordan',
'Malaysia',
'Morocco',
'Nigeria',
'Poland',
'Taiwan',
'Uruguay',
'Ukraine')
GROUP BY 1
ORDER BY 1;


SELECT DISTINCT CSR.MAILING_COUNTRY_NAME FROM PRODUCTION.MART_CSI_AM24_REG.AM24_REG_V AS CSR;


SELECT DISTINCT CON."Member_Type__c" FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON;


with CON AS (
    SELECT
        *,
            CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
)
SELECT 
    RT."Name",
    COUNT(*)
FROM PRODUCTION.MART_CTI_MATCHES.SPEAKER_DEMOGRAPHICS AS SPK
    LEFT JOIN CON
        ON SPK.AACRID = CON.AACR_ID
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.RECORDTYPE AS RT
        ON CON."RecordTypeId" = RT."Id"
GROUP BY RT."Name";


CREATE OR REPLACE VIEW TEST.TEST_AREA.CONTACT_WITH_CTI
AS
with CON AS (
    SELECT
        *,
            CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
)
SELECT 
    CON.*,
    ABS.MEETING_ID,
    ABS.MEETING_NAME,
    ABS.MEETING_YEAR,
    ABS.SESSION_TYPE_NAME,
    ABS.SESSION_NUMBER,
    ABS.SESSION_TITLE,
    ABS.CONTROL_NUMBER,
    ABS.ACTIVITY_NAME,
    ABS.SESSION_ROLE_STATUS,
    ABS.PROGRAM_STATUS_NAME,
    ABS.PUBLISHING_TITLE,
    ABS.AUTHOR_FIRST_NAME,
    ABS.AUTHOR_MIDDLE_INITIAL,
    ABS.AUTHOR_LAST_NAME,
    ABS.AUTHOR_GENERATION,
    ABS.INSTITUTION_NAME,
    ABS.CONTACT_CITY,
    ABS.CONTACT_STATE,
    ABS.CONTACT_COUNTRY_NAME,
    ABS.CONTACT_EMAIL,
    ABS.SESSION_ROLE_ORDER,
    ABS.SESSION_ID,
    ABS.SESSION_START_DATE,
    ABS.AUTHOR_MEMBER_SPECIFICATION,
    ABS.PERSON_MEMBER_SPECIFICATION,
    ABS.PRESENTATION_NUMBER,
    ABS.SRC_SYS_ID,
    ABS.SRC_RECORD_ID,
    ABS.SRC_CREATED_DATE,
    ABS.CREATED_BY_ID,
    ABS.SRC_LAST_UPDATED_DATE,
    ABS.LAST_MODIFIED_BY_ID,
    ABS.SRC_START_DATE,
    ABS.SRC_END_DATE,
    ABS.IS_TEST,
    ABS.TEST_METADATA,
    ABS.DW_ID,
    ABS.DW_CREATED_DATE,
    ABS.DW_LAST_UPDATED_DATE,
    ABS.DW_START_DATE,
    ABS.DW_END_DATE,
    ABS.MASTER_ID,
    ABS.IS_MASTERED,
    ABS.IS_CONFORMED,
    ABS.EXCEPTION_CODES,
    ABS.SYSTEM_MODSTAMP,
    ABS.COMPLETE_STATUS,
    ABS.PROGRAM_STATUS_COMMENT,
    ABS.REVIEWER_ASSIGNED_COUNT,
    ABS.RECORD_ID,
    ABS.STAGE_ID,
    ABS.GOLDEN_RECORDID,
    ABS.SOURCE,
    ABS.SOURCE_ENTITYID,
    ABS.AACRID,
    ABS.MERGETO_GOLDEN_RECORDID,
    ABS.CREATEDATE,
    ABS.UPDATEDATE,
    ABS.CREATE_USER,
    ABS.UPDATE_USER,
    ABS.MATCH,
FROM CON
    INNER JOIN PRODUCTION.MART_CTI_MATCHES.ABSTRACT_PRESENTERS__V AS ABS
        ON CON.AACR_ID = ABS.AACRID
ORDER BY RANDOM()
LIMIT 10;





SELECT * FROM PRODUCTION.REPL_PUBS_SALESFORCE_OWNBACKUP.OPPORTUNITY;





with Everyone AS (
SELECT 
    CON.*,
    SUM
    ROW_NUMBER() OVER(PARTITION BY CON."Id" ORDER BY OPP."CloseDate" DESC) AS DATE_ROW
FROM PRODUCTION.MART_MEETING_REGISTRATION.MEETING_REGISTRATIONS_BACKUP AS MR
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON
        ON MR.CONTACT_ID = CON."Id"
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_EVENT__C AS EV
        ON MR.EVENT_ID = EV."Id"
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY AS OPP
       ON OPP."npe01__Contact_Id_for_Role__c" = CON."Id"
WHERE EV."Name" LIKE '%Bladder%' AND MR.PARTICIPANT_STATUS = 'Yes'
)
SELECT 
    *,
 FROM Everyone WHERE DATE_ROW = 1;

--ROW_NUMBER() OVER(PARTITION BY CON."Id" ORDER BY OPP."CloseDate" DESC) AS DATE_ROW


SELECT 
    CON.*,
    SUM(OPP."Amount") AS TOTAL_AMOUNT,
    COUNT(OPP."Id") AS TOTAL_OPPORTUNITIES,
    MAX(OPP."CloseDate")
FROM PRODUCTION.MART_MEETING_REGISTRATION.MEETING_REGISTRATIONS_BACKUP AS MR
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON
        ON MR.CONTACT_ID = CON."Id"
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_EVENT__C AS EV
        ON MR.EVENT_ID = EV."Id"
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY AS OPP
       ON OPP."npe01__Contact_Id_for_Role__c" = CON."Id"
WHERE EV."Name" LIKE '%Bladder%' AND MR.PARTICIPANT_STATUS = 'Yes'
GROUP BY CON."Id";





/*DATAMART BELOW FOR FOUNDATION */
CREATE OR REPLACE VIEW PRODUCTION.MART_MEETING_REGISTRATION.FOUNDATION_MEETING_REGISTRATION
AS
with RecentGift AS (
    SELECT
        "npe01__Contact_Id_for_Role__c" AS CONTACT_ID1,
        SUM("Amount") AS TOTAL_AMOUNT,
        COUNT("Id") AS TOTAL_OPPORTUNITIES
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY
GROUP BY 1
),
Recent AS (
SELECT
    "npe01__Contact_Id_for_Role__c" AS CONTACT_ID,
    "CloseDate" DATE_OF_MOST_RECENT_DONATION,
    ROW_NUMBER() OVER(PARTITION BY "npe01__Contact_Id_for_Role__c" ORDER BY "CloseDate" DESC) AS ROW_ORDER,
    "Amount" AS MOST_RECENT_DONATION_AMOUNT
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY),
OPP AS (
    SELECT 
        Recent.CONTACT_ID,
        Recent.MOST_RECENT_DONATION_AMOUNT AS MOST_RECENT_DONATION_AMOUNT,
        Recent.DATE_OF_MOST_RECENT_DONATION AS DATE_OF_MOST_RECENT_DONATION,
        RecentGift.TOTAL_AMOUNT AS TOTAL_DONATION_AMOUNT,
        RecentGift.TOTAL_OPPORTUNITIES AS TOTAL_OPPORTUNITIES
    FROM RecentGift JOIN Recent ON RecentGift.CONTACT_ID1 = Recent.CONTACT_ID
    WHERE Recent.ROW_ORDER = 1
)
SELECT
    MR.*,
    CON."Id",
    OPP.MOST_RECENT_DONATION_AMOUNT,
    OPP.DATE_OF_MOST_RECENT_DONATION,
    OPP.TOTAL_DONATION_AMOUNT,
    OPP.TOTAL_OPPORTUNITIES
FROM PRODUCTION.MART_MEETING_REGISTRATION.MEETING_REGISTRATIONS_BACKUP AS MR
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON
        ON MR.CONTACT_ID = CON."Id"
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_EVENT__C AS EV
        ON MR.EVENT_ID = EV."Id"
    LEFT JOIN OPP
       ON OPP.CONTACT_ID = CON."Id"
;


/*

OPP.MOST_RECENT_DONATION_AMOUNT,
OPP.DATE_OF_MOST_RECENT_DONATION,
OPP.TOTAL_DONATION_AMOUNT,
OPP.TOTAL_OPPORTUNITIES,

 */


SELECT * FROM PRODUCTION.MART_MEETING_REGISTRATION.FOUNDATION_MEETING_REGISTRATION WHERE EVENT_ID = 'a4j8W000000OLXmQAO';

SELECT
    "Object_Lookup__c",
    COUNT(*)
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT_DIMENSION_TAG__C AS CON
GROUP BY 1
HAVING COUNT(*) > 1
ORDER BY 2 DESC;

SELECT * FROM PRODUCTION.MART_CONTACT_DIMENSION_TAGS.CONTACT_DIMENSION_TAGS_BACKUP;


SELECT "Object_Lookup__c", LISTAGG("Tag__c", ', ') WITHIN GROUP (ORDER BY "Tag__c") AS tags
FROM PRODUCTION.MART_CONTACT_DIMENSION_TAGS.CONTACT_DIMENSION_TAGS_BACKUP
GROUP BY 1;



SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT WHERE "LastName" LIKE '%ker%' ORDER BY "LastName";

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_EVENT__C WHERE "Name" LIKE '%Patient%' AND YEAR("Start_Date__c") = 2023;

SELECT * FROM PRODUCTION.MART_MEETING_REGISTRATION.MEETING_REGISTRATIONS_BACKUP ORDER BY RANDOM() LIMIT 1000;

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.AC_USER_SEGMENT__C;


GRANT usage ON ALL schemas in database TEST TO ROLE useradmin;
GRANT select ON ALL tables in database TEST TO ROLE useradmin;


SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__BADGE_TYPE__C;

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__BADGE__C;


enWhzefc8vuFSx_



SELECT DISTINCT EMAIL FROM TEST.TEST_AREA.AM24_LIVE_ATTENDANCE;

SELECT DISTINCT EMAIL FROM TEST.TEST_AREA.AM24_RECORDED_ATTENDANCE;


SELECT DISTINCT EMAIL FROM TEST.TEST_AREA.AM24LIVESESSIONTEST;









SELECT COUNT(*) FROM PRODUCTION.MART_MEETING_REGISTRATION.MEETING_REGISTRATIONS_BACKUP AS MR
LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_EVENT__C AS EV
ON MR.EVENT_ID = EV."Id"
WHERE EV."Name" LIKE '%Annual Meeting 2021%';



SELECT EV."Name", COUNT(*) FROM PRODUCTION.MART_MEETING_REGISTRATION.MEETING_REGISTRATIONS_BACKUP AS MR
LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_EVENT__C AS EV
ON MR.EVENT_ID = EV."Id"
WHERE EV."Name" LIKE '%Annual Meeting%'
GROUP BY 1;


SELECT * FROM PRODUCTION.MART_AM_MEETING_REGISTRATION.REGISTRANTS
WHERE AACR_ID IS NOT NULL;


with CON AS (
    SELECT
        *,
            CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
)
SELECT
    AMR.MEETING_YEAR,
    COUNT(*)
FROM PRODUCTION.MART_AM_MEETING_REGISTRATION.REGISTRANTS AS AMR
    LEFT JOIN CON
        ON AMR.AACR_ID = CON.AACR_ID
GROUP BY 1
ORDER BY 1;


/*
WHERE CON."MailingCountry" IN (
    'Algeria',
    'Argentina',
    'Chile',
    'India',
    'Jordan',
    'Malaysia',
    'Morocco',
    'Nigeria',
    'Poland',
    'Taiwan',
    'Uruguay',
    'Ukraine '
)
*/


SELECT
    COUNT(*)
FROM TEST.MART_AM_MEETING_REGISTRATION.REGISTRANTS_PREP_TO_MDH
WHERE AACR_ID IS NULL;






SELECT * FROM PRODUCTION.MART_MEETING_REGISTRATION.MEETING_REGISTRATIONS_BACKUP;


SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT;
SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ACCOUNT;

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__SALES_ORDER__C;

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.ORDERAPI__BADGE__C;

SELECT * FROM PRODUCTION.REPL_SALESFORCE.CONTACTS;


select TABLE_NAME, ROW_COUNT from information_schema.tables where table_schema LIKE '%REPL_SALESFORCE_OWNBACKUP%' ORDER BY 1;




with CON AS (
    SELECT
        *,
            CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
)
SELECT
    AMR.MEETING_YEAR,
    CON."MailingCountry",
    COUNT(*)
FROM PRODUCTION.MART_AM_MEETING_REGISTRATION.REGISTRANTS AS AMR
    LEFT JOIN CON
        ON AMR.MEMBER_ID = CON.AACR_ID
WHERE CON."MailingCountry" IN (
    'Algeria',
    'Argentina',
    'Chile',
    'India',
    'Jordan',
    'Malaysia',
    'Morocco',
    'Nigeria',
    'Poland',
    'Taiwan',
    'Uruguay',
    'Ukraine'
)
GROUP BY 1,2 
ORDER BY 1;


SELECT * FROM PRODUCTION.MART_AM_MEETING_REGISTRATION.REGISTRANTS;


SELECT DISTINCT MEETING_YEAR FROM TEST.MART_AM_MEETING_REGISTRATION.REGISTRANTS_PREP_TO_MDH;


SELECT DISTINCT ACTIVITY_TYPE FROM IMISDATA.DBO.ACTIVITY;


SELECT 
    * 
FROM IMISDATA.DBO.ACTIVITY 
WHERE ACTIVITY_TYPE IN ('GIFTRECORD', 'GIFT');




with CON AS (
    SELECT
        *,
            CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
)
SELECT * FROM CON WHERE AACR_ID = 1251720;


SELECT 
    * 
FROM IMISDATA.DBO.ACTIVITY 
WHERE ACTIVITY_TYPE IN ('GIFTRECORD', 'GIFT', 'DONNOTES');


/*
OPP."Description" AS DESCRIPTION,
OPP."Amount" AS AMOUNT,
OPP."Type" AS "TYPE",
OPP."CreatedDate" AS "TRANSACTION_DATE",
CON.AACR_ID AS AACR_ID,
'SALESFORCE' AS "SOURCE"





"DESCRIPTION",
"AMOUNT",
"ACTIVITY_TYPE" AS "TYPE",
"TRANSACTION_DATE",
"ID" AS AACR_ID,
'IMIS' AS "SOURCE"
*/

CREATE OR REPLACE SCHEMA TEST.MART_DONATIONS_HISTORY;




CREATE OR REPLACE VIEW TEST.MART_DONATIONS_HISTORY.DONATIONS
AS
with CON AS (
    SELECT
        *,
            CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
),
OPPS AS (
SELECT 
    OPP."Description" AS DESCRIPTION,
    OPP."Id" AS DONATION_ID,
    OPP."Amount" AS AMOUNT,
    OPP."Type" AS "TYPE",
    OPP."CreatedDate" AS "TRANSACTION_DATE",
    CON.AACR_ID AS "AACR_ID",
    'SALESFORCE' AS "SOURCE"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY AS OPP
    JOIN CON
        ON OPP."ContactId" = CON."Id"
),
IMISDONATIONS AS (
    SELECT 
        "DESCRIPTION",
        "ID" AS DONATION_ID,
        "AMOUNT",
        "ACTIVITY_TYPE" AS "TYPE",
        "TRANSACTION_DATE",
        "CO_ID" AS AACR_ID,
        'IMIS' AS "SOURCE"
    FROM IMISDATA.DBO.ACTIVITY 
    WHERE ACTIVITY_TYPE IN ('GIFTRECORD', 'GIFT', 'DONNOTES')
)
SELECT * FROM OPPS
UNION ALL 
SELECT * FROM IMISDONATIONS;







SELECT 
        "DESCRIPTION",
        "AMOUNT",
        "ACTIVITY_TYPE" AS "TYPE",
        "TRANSACTION_DATE",
        "ID" AS AACR_ID,
        'IMIS' AS "SOURCE"
    FROM IMISDATA.DBO.ACTIVITY 
    WHERE ACTIVITY_TYPE IN ('GIFTRECORD', 'GIFT', 'DONNOTES');



with CON AS (
    SELECT
        *,
            CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
)
SELECT * FROM CON WHERE AACR_ID = 292375;


SELECT COUNT(*) FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY WHERE "ContactId" IS NULL;

SELECT AACR_ID FROM TEST.MART_DONATIONS_HISTORY.DONATIONS GROUP BY 1 HAVING COUNT(DISTINCT SOURCE) > 1;


SELECT * FROM TEST.MART_DONATIONS_HISTORY.DONATIONS WHERE AACR_ID IN (SELECT AACR_ID FROM TEST.MART_DONATIONS_HISTORY.GRANTEES);

CREATE OR REPLACE VIEW TEST.MART_DONATIONS_HISTORY.GRANTEE_DONATIONS
AS
SELECT
    GR.*,
    DN.AMOUNT,
    DN.DONATION_ID,
    DN.DESCRIPTION,
    DN.SOURCE,
    DN.TRANSACTION_DATE,
    DN.TYPE,
    CONCAT(DN.DONATION_ID, DN.TRANSACTION_DATE, DN.AACR_ID) AS UNIQUE_KEY
FROM TEST.MART_DONATIONS_HISTORY.GRANTEES AS GR
    LEFT JOIN TEST.MART_DONATIONS_HISTORY.DONATIONS AS DN
        ON GR.AACR_ID = DN.AACR_ID;



CREATE SCHEMA TEST.MART_AM_MEETING_REG_ALL_DATA;

CREATE OR REPLACE VIEW TEST.MART_AM_MEETING_REG_ALL_DATA.ALL_REG
AS
select
    meeting_year,
    member_id as "AACR_ID",
    comp_code
from
    production.mart_am_meeting_registration.registrants
union
    select
        "AM21"."MEETING_YEAR",
        "AM21".aacr_id,
        "AM21".comp_code
    from (
        select
            '2021' as "MEETING_YEAR",
            "Meeting Registration".*
        from
            production.mart_meeting_registration.meeting_registrations_backup as "Meeting Registration"
        left join
            production.repl_salesforce_ownbackup.BR_EVENT__C as "Events"
            on "Meeting Registration".Event_Id = "Events"."Id"
        where
            "Events"."Name" = 'AACR Annual Meeting 2021'
    ) as "AM21"
order by
    meeting_year;


SELECT * FROM TEST.MART_AM_MEETING_REG_ALL_DATA.ALL_REG;

with CON AS (
    SELECT
        *,
            CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
)
SELECT
    AMR.MEETING_YEAR,
    CON."MailingCountry",
    COUNT(*)
FROM TEST.MART_AM_MEETING_REG_ALL_DATA.ALL_REG AS AMR
    LEFT JOIN CON
        ON AMR.AACR_ID = CON.AACR_ID
WHERE CON."MailingCountry" IN (
    'Algeria',
    'Argentina',
    'Chile',
    'India',
    'Jordan',
    'Malaysia',
    'Morocco',
    'Nigeria',
    'Poland',
    'Taiwan',
    'Uruguay',
    'Ukraine'
)
GROUP BY 1,2 
ORDER BY 1;



SELECT
    CON."Name",
    MIN(OPP."LastModifiedDate") AS "FIRST_DONATION",
    MAX(OPP."LastModifiedDate") AS "LAST_DONATION"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY AS OPP
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON
        ON OPP."ContactId" = CON."Id"
WHERE OPP."Amount" >= 500
GROUP BY 1;

SELECT
    CON."Name",
    OPP."Amount",
    OPP."CloseDate"
FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY AS OPP
    LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON
        ON OPP."ContactId" = CON."Id"
WHERE OPP."Amount" >= 500
ORDER BY 1,3;



create or replace view TEST.MART_AM_MEETING_REG_ALL_DATA.ALL_REG
AS
select
    meeting_year,
    member_id as "AACR_ID",
    comp_code
from
    production.mart_am_meeting_registration.registrants
union
    select
        "AM21"."MEETING_YEAR",
        "AM21".aacr_id,
        "AM21".comp_code
    from (
        select
            '2021' as "MEETING_YEAR",
            CASE
            WHEN CON."iMIS_ID__c" IS NULL THEN CON."Salesforce_ID__c"
            ELSE CON."iMIS_ID__c"
        END AS AACR_ID,
            "Meeting Registration".*
        from
            production.mart_meeting_registration.meeting_registrations_backup as "Meeting Registration"
        left join
            production.repl_salesforce_ownbackup.BR_EVENT__C as "Events"
            on "Meeting Registration".Event_Id = "Events"."Id"
        LEFT JOIN PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CON
            ON "Meeting Registration"."CONTACT_ID" = CON."Id"
        where
            "Events"."Name" = 'AACR Annual Meeting 2021'
    ) as "AM21"
order by
    meeting_year;





SELECT "Id", "Name" FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT ORDER BY RANDOM() LIMIT 100;


/*
437086.1069626262
955642.8757689246
758794.5476302645
638792.6357773329
240416.77639819286
240395.0683025824
152275.2509513795
879558.5311974416
641003.5105688879
737265.3200164409
118526.0448662222
972918.8669457949
849198.3767203796
291105.19961044856
263642.4704863905
265064.05886809045
373818.01866358396
$572,280.79
488750.5167779042
362106.2261782377
650667.6052501415
225544.47458683763
362930.18368169636
429725.65896432253
510462.98579533235
806658.3652537123
279706.40394252376
562810.9945722504
633173.1119758382
141805.37144799795
646790.3667112945
253471.7113185624
158546.43368675158
$953,996.98
969068.8297671034
$827,557.61
374152.3922560336
187904.90260574548
715809.7238609412
496137.24436564115
209834.41136030096
545659.2191001432
130949.66900369656
918388.3618709039
332901.98344001523
696270.0559185838
380539.96848046983
568061.2190600297
592039.2514089517
266369.0099729743
972626.1649881027
797619.5410250031
945549.0474077702
$905,344.62
638109.9809299767
929686.8115208051
179643.25184672757
276384.5761772307
140704.56001948426
392797.2976869379
449809.56072053383
344214.1285965063
845863.7582367364
421077.99402423034
352841.0587186427
588426.4748424236
226831.80247728637
821977.2826786357
167095.57931179373
988198.2429404656
795020.2923669916
278844.1133807552
104969.90541124216
833915.2856093508
736171.6094628554
756106.4512368885
794143.3120173512
166640.18656068132
422619.1556898453
204282.15357261675
876793.0832880342
660968.3141448022
397808.2223673843
157202.51525742127
$379,884.09
392664.98982407234
756645.5605042577
673801.7242196918
898491.4683186939
524993.4326457544
207634.82134447154
741920.3085006955
784706.5437552077
605149.4778125465
793870.4619591049
544416.0367279516
570459.5464437946
484786.9165226947
122877.21406968567
197,102.28



*/


SELECT * FROM TEST.MART_DONATIONS_HISTORY.GRANTEE_DONATIONS WHERE AACR_ID = '7963';


SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.OPPORTUNITY WHERE "ContactId" = '0031I00000Ws0X5QAJ';

CREATE OR REPLACE VIEW TEST.MART_DONATIONS_HISTORY.GRANTEE_DONATIONS_FINAL
AS
with CON AS (
    SELECT
        *,
            CASE
            WHEN CONC."iMIS_ID__c" IS NULL THEN CONC."Salesforce_ID__c"
            ELSE CONC."iMIS_ID__c"
        END AS AACR_ID
    FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT AS CONC
)
SELECT
    GD.*,
    CON."Email",
    CON."wf_net_worth__c"
FROM TEST.MART_DONATIONS_HISTORY.GRANTEE_DONATIONS AS GD
    JOIN CON
        ON GD.AACR_ID = CON.AACR_ID
WHERE GD.AACR_ID IS NOT NULL;


SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.BR_EVENT__C WHERE "Name" LIKE '%GENIE%';

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.EVENT;




SELECT * FROM PRODUCTION.REPL_PUBS_SALESFORCE_OWNBACKUP.CONTACT;

SELECT * FROM PRODUCTION.REPL_PUBS_SALESFORCE_OWNBACKUP.OPPORTUNITY;

SELECT * FROM PRODUCTION.REPL_SALESFORCE_OWNBACKUP.CONTACT WHERE "Email" = 'fabrice.andre@gustaveroussy.fr';

enWhzefc8vuFSx_
SELECT * FROM PRODUCTION.MART_CTI_MATCHES.INVITED_SPEAKERS__V WHERE GOLDEN_RECORDID = '218bf6cf-2845-4aa7-8edc-d82b4afa9df3' AND MEETING_NAME = '2024 Annual Meeting';